/-
  THE CLOSURE C8 (THE_CLOSURE_PLAN.md) — downstream payoff (ii): the crossed-product
  von Neumann closure, NAMED and PACKAGED.

  The project's crossed product M⋊_σℝ (matter representation π(a) = `matterRep` and clock
  translations λ_t = `clockTransl`, both bounded operators on L²(ℝ;H) — built in
  `CrossedProductRep`/`CrossedProductTranslation`) now gets its genuine von Neumann algebra:
  `crossedProductVN := generatedBy (range π ∪ range λ)` — with C7's density theorem giving the
  concrete membership characterization (the carrier IS the SOT closure of the generated
  ⋆-algebra).

  ⚠ SCOPE (binding verdict): PACKAGING ONLY. The dual-weight trace of the TYPE-II ladder
  (W1–W4, `TypeIITrace`) lives on the ALGEBRAIC CORE and is NOT claimed to extend to this weak
  closure — `DualWeightTraceExtension` (normal weights / affiliated operators) remains the
  carried frontier. No type is classified; no normality is claimed; the continuum is not done.
-/
import Mathlib
import QIQTH.VonNeumann.Bicommutant
import QIQTH.CrossedProductRep
import QIQTH.CrossedProductTranslation

namespace QIQTH.VonNeumann

open MeasureTheory QIQTH.StandardSubspaceModular

variable {H : Type*} [NormedAddCommGroup H] [InnerProductSpace ℂ H] [CompleteSpace H]
  [MeasurableSpace H] [BorelSpace H] [SecondCountableTopology H]

/-- **The crossed-product von Neumann algebra**: the vN algebra on `L²(ℝ;H)` generated by the
    matter representation and the clock translations. -/
noncomputable def crossedProductVN (S : StandardSubspace H) :
    VonNeumannAlgebra (Lp H 2 (volume : Measure ℝ)) :=
  generatedBy (Set.range (matterRep S) ∪ Set.range (clockTransl (H := H)))

/-- The matter operators lie in the closure. -/
theorem matterRep_mem_crossedProductVN (S : StandardSubspace H) (a : H →L[ℂ] H) :
    matterRep S a ∈ crossedProductVN S :=
  subset_generatedBy _ (Set.mem_union_left _ ⟨a, rfl⟩)

/-- The clock translations lie in the closure. -/
theorem clockTransl_mem_crossedProductVN (S : StandardSubspace H) (t : ℝ) :
    clockTransl (H := H) t ∈ crossedProductVN S :=
  subset_generatedBy _ (Set.mem_union_right _ ⟨t, rfl⟩)

/-- The algebraic-core monomials `π(a)·λ_t` lie in the closure (the vN algebra is an algebra). -/
theorem matterRep_mul_clockTransl_mem_crossedProductVN (S : StandardSubspace H)
    (a : H →L[ℂ] H) (t : ℝ) :
    matterRep S a * clockTransl (H := H) t ∈ crossedProductVN S :=
  mul_mem (matterRep_mem_crossedProductVN S a) (clockTransl_mem_crossedProductVN S t)

/-- **The membership characterization** (C7's density theorem, instantiated): the carrier of the
    crossed-product vN algebra IS the set of operators SOT-approximable from the generated
    ⋆-algebra of the matter + clock operators. -/
theorem crossedProductVN_carrier_eq (S : StandardSubspace H) :
    (crossedProductVN S : Set (Lp H 2 (volume : Measure ℝ) →L[ℂ] Lp H 2 (volume : Measure ℝ)))
      = {T | SOTApprox
          ((StarAlgebra.adjoin ℂ
              (Set.range (matterRep S) ∪ Set.range (clockTransl (H := H)))
            : StarSubalgebra ℂ _) : Set _) T} :=
  generatedBy_carrier_eq _

end QIQTH.VonNeumann
