/-
  THE CLOSURE C2 (THE_CLOSURE_PLAN.md) — the von Neumann algebra GENERATED by a set of operators.

  Purely algebraic (no topology, no density claim): `generatedBy S` is the double centralizer
  `(S ∪ S*)″`, packaged as a Mathlib `VonNeumannAlgebra` — the bicommutant field is
  `Set.centralizer_centralizer_centralizer` (X‴ = X′), and star-closure of a centralizer of a
  star-closed set supplies `star_mem'`. This alone lets the project NAME its limit algebras
  (the crossed-product closure, the refinement-tower limit) before the density theorem lands.

  HOUSE RULE (binding verdict): theorem STATEMENTS use `Set.centralizer` only;
  `StarSubalgebra.centralizer` appears only inside proofs. The Galois lemma `centralizer_adjoin`
  (the centralizer sees only the generated ⋆-algebra) is proved by the PAIR-TRICK adjoin
  induction — the motive carries `Commute x b ∧ Commute x (star b)` so the star case swaps
  conjuncts (a bare `Commute x b` motive dies at the star case: commuting with `b` does NOT give
  commuting with `star b` in general).

  No density statement, no SOT/WOT, no bicommutant THEOREM here — C7's content; this file is the
  naming layer only.
-/
import Mathlib

namespace QIQTH.VonNeumann

variable {H : Type*} [NormedAddCommGroup H] [InnerProductSpace ℂ H] [CompleteSpace H]

/-- The star-union collapses for a star-closed set (the C2 bridging lemma). -/
theorem union_star_self_of_starClosed {M : Type*} [InvolutiveStar M] {s : Set M}
    (hs : ∀ a ∈ s, star a ∈ s) : s ∪ star s = s := by
  refine Set.union_eq_self_of_subset_right fun x hx => ?_
  have := hs (star x) hx
  rwa [star_star] at this

/-- Bridging (house rule): the centralizer of a star-closed set needs no star-union. -/
theorem centralizer_union_star_of_starClosed {s : Set (H →L[ℂ] H)}
    (hs : ∀ a ∈ s, star a ∈ s) :
    Set.centralizer (s ∪ star s) = Set.centralizer s := by
  rw [union_star_self_of_starClosed hs]

/-- **The von Neumann algebra generated by a set of operators** — the double centralizer
    `(S ∪ S*)″`, purely algebraically. The bicommutant property is `X‴ = X′`. -/
def generatedBy (S : Set (H →L[ℂ] H)) : VonNeumannAlgebra H where
  toStarSubalgebra :=
    { Subalgebra.centralizer ℂ (Set.centralizer (S ∪ star S)) with
      star_mem' := fun {a} ha =>
        Set.star_mem_centralizer'
          (fun b hb => Set.star_mem_centralizer hb) ha }
  centralizer_centralizer' :=
    Set.centralizer_centralizer_centralizer (Set.centralizer (S ∪ star S))

theorem generatedBy_coe (S : Set (H →L[ℂ] H)) :
    (generatedBy S : Set (H →L[ℂ] H))
      = Set.centralizer (Set.centralizer (S ∪ star S)) := rfl

theorem mem_generatedBy_iff (S : Set (H →L[ℂ] H)) (T : H →L[ℂ] H) :
    T ∈ generatedBy S ↔ T ∈ Set.centralizer (Set.centralizer (S ∪ star S)) := Iff.rfl

/-- The generators lie in the generated algebra. -/
theorem subset_generatedBy (S : Set (H →L[ℂ] H)) :
    S ⊆ (generatedBy S : Set (H →L[ℂ] H)) := fun _ hx =>
  Set.subset_centralizer_centralizer (Set.mem_union_left _ hx)

/-- The starred generators lie in the generated algebra. -/
theorem star_subset_generatedBy (S : Set (H →L[ℂ] H)) :
    star S ⊆ (generatedBy S : Set (H →L[ℂ] H)) := fun _ hx =>
  Set.subset_centralizer_centralizer (Set.mem_union_right _ hx)

/-- **Minimality**: the generated algebra is contained in every von Neumann algebra containing
    the generators (centralizer antitonicity twice + the bicommutant property of the target). -/
theorem generatedBy_le (S : Set (H →L[ℂ] H)) (M : VonNeumannAlgebra H)
    (h : S ⊆ (M : Set (H →L[ℂ] H))) :
    (generatedBy S : Set (H →L[ℂ] H)) ⊆ (M : Set (H →L[ℂ] H)) := by
  have hT : S ∪ star S ⊆ (M : Set (H →L[ℂ] H)) := by
    refine Set.union_subset h fun x hx => ?_
    have hx' : star x ∈ S := hx
    have hmem : star x ∈ M := h hx'
    have := star_mem hmem
    rwa [star_star] at this
  have h1 : Set.centralizer (M : Set (H →L[ℂ] H)) ⊆ Set.centralizer (S ∪ star S) :=
    Set.centralizer_subset hT
  have h2 : Set.centralizer (Set.centralizer (S ∪ star S))
      ⊆ Set.centralizer (Set.centralizer (M : Set (H →L[ℂ] H))) :=
    Set.centralizer_subset h1
  rw [generatedBy_coe]
  calc (Set.centralizer (Set.centralizer (S ∪ star S)) : Set (H →L[ℂ] H))
      ⊆ Set.centralizer (Set.centralizer (M : Set (H →L[ℂ] H))) := h2
    _ = (M : Set (H →L[ℂ] H)) := M.centralizer_centralizer

/-- For a star-closed generating carrier (e.g. a `StarSubalgebra`) the generated algebra is the
    plain double centralizer. -/
theorem generatedBy_coe_of_starClosed {s : Set (H →L[ℂ] H)} (hs : ∀ a ∈ s, star a ∈ s) :
    (generatedBy s : Set (H →L[ℂ] H)) = Set.centralizer (Set.centralizer s) := by
  rw [generatedBy_coe, union_star_self_of_starClosed hs]

/-- The `StarSubalgebra` instance of the previous lemma. -/
theorem generatedBy_starSubalgebra_coe (A : StarSubalgebra ℂ (H →L[ℂ] H)) :
    (generatedBy (A : Set (H →L[ℂ] H)) : Set (H →L[ℂ] H))
      = Set.centralizer (Set.centralizer (A : Set (H →L[ℂ] H))) :=
  generatedBy_coe_of_starClosed fun _ ha => star_mem ha

/-- **The Galois lemma — the centralizer sees only the generated ⋆-algebra**:
    `(adjoin ℂ S)′ = (S ∪ S*)′`. Proved by the pair-trick adjoin induction (the motive carries
    the commutation with `b` AND with `star b`, so the star case swaps the conjuncts — a bare
    commutation motive dies at the star case). -/
theorem centralizer_adjoin (S : Set (H →L[ℂ] H)) :
    Set.centralizer ((StarAlgebra.adjoin ℂ S : StarSubalgebra ℂ (H →L[ℂ] H))
        : Set (H →L[ℂ] H))
      = Set.centralizer (S ∪ star S) := by
  apply Set.Subset.antisymm
  · refine Set.centralizer_subset ?_
    refine Set.union_subset (StarAlgebra.subset_adjoin ℂ S) fun x hx => ?_
    have hx' : star x ∈ S := hx
    have := star_mem (StarAlgebra.subset_adjoin ℂ S hx')
    rwa [star_star] at this
  · intro x hx b hb
    have key : ∀ (c : H →L[ℂ] H), c ∈ StarAlgebra.adjoin ℂ S →
        c * x = x * c ∧ (star c) * x = x * (star c) := by
      intro c hc
      induction hc using StarAlgebra.adjoin_induction with
      | mem y hy =>
        refine ⟨hx y (Set.mem_union_left _ hy), hx (star y) (Set.mem_union_right _ ?_)⟩
        rw [Set.mem_star, star_star]
        exact hy
      | algebraMap r =>
        refine ⟨Algebra.commutes r x, ?_⟩
        rw [← algebraMap_star_comm]
        exact Algebra.commutes (star r) x
      | add y z _ _ hy hz =>
        refine ⟨by rw [add_mul, mul_add, hy.1, hz.1], ?_⟩
        rw [star_add, add_mul, mul_add, hy.2, hz.2]
      | mul y z _ _ hy hz =>
        refine ⟨by rw [mul_assoc, hz.1, ← mul_assoc, hy.1, mul_assoc], ?_⟩
        rw [star_mul, mul_assoc, hy.2, ← mul_assoc, hz.2, mul_assoc]
      | star y _ hy =>
        refine ⟨hy.2, ?_⟩
        rw [star_star]
        exact hy.1
    exact (key b hb).1

end QIQTH.VonNeumann
