/-
  THE CLOSURE C1 (THE_CLOSURE_PLAN.md) — projections onto invariant subspaces lie in the commutant.

  The elementary engine of the von Neumann double-commutant theorem: for a ⋆-closed unital algebra
  of operators A ⊆ B(H), the orthogonal (star) projection onto any closed A-invariant subspace
  commutes with every element of A — invariance of U under `a` handles one block, invariance of Uᗮ
  (which follows from invariance of U under `star a` — THE ⋆-CLOSURE USE) handles the other, and
  Mathlib's `IsIdempotentElem.commute_iff` (range + kernel invariant ⟺ commuting) closes it.

  ⚠ THE ⋆-CLOSURE IS LOAD-BEARING (counterexample): take A = the upper-triangular 2×2 matrices —
  a unital, norm-closed subalgebra of B(ℂ²) that is NOT ⋆-closed. The line span(e₁) is A-invariant,
  but its orthogonal projection P₁ does NOT commute with the nilpotent E₁₂ ∈ A
  (E₁₂P₁ = 0 ≠ P₁E₁₂ = E₁₂): the projection onto an invariant subspace of a non-⋆ algebra need not
  lie in the commutant — indeed A′ = ℂ·1 and A″ = B(ℂ²) ⊋ A, so the bicommutant theorem is FALSE
  without star. Nothing beyond this block is claimed: no density, no bicommutant statement here.
-/
import Mathlib

namespace QIQTH.VonNeumann

open ContinuousLinearMap Submodule

variable {H : Type*} [NormedAddCommGroup H] [InnerProductSpace ℂ H] [CompleteSpace H]
variable (A : StarSubalgebra ℂ (H →L[ℂ] H))

/-- The orbit `A ξ` of a vector under a (star-)subalgebra of operators, as a submodule. -/
def orbitSubmodule (ξ : H) : Submodule ℂ H where
  carrier := {y | ∃ a ∈ A, a ξ = y}
  add_mem' := by
    rintro _ _ ⟨a, ha, rfl⟩ ⟨b, hb, rfl⟩
    exact ⟨a + b, add_mem ha hb, rfl⟩
  zero_mem' := ⟨0, zero_mem A, rfl⟩
  smul_mem' := by
    rintro c _ ⟨a, ha, rfl⟩
    exact ⟨c • a, SMulMemClass.smul_mem c ha, rfl⟩

theorem mem_orbitSubmodule_iff (ξ y : H) :
    y ∈ orbitSubmodule A ξ ↔ ∃ a ∈ A, a ξ = y := Iff.rfl

/-- Unitality: the vector itself lies in its own orbit (`1 ∈ A`). -/
theorem self_mem_orbitSubmodule (ξ : H) : ξ ∈ orbitSubmodule A ξ :=
  ⟨1, one_mem A, rfl⟩

/-- The orbit is invariant under the algebra (`a · (b ξ) = (a * b) ξ`). -/
theorem orbitSubmodule_invariant {a : H →L[ℂ] H} (ha : a ∈ A) (ξ : H) :
    ∀ y ∈ orbitSubmodule A ξ, a y ∈ orbitSubmodule A ξ := by
  rintro _ ⟨b, hb, rfl⟩
  exact ⟨a * b, mul_mem ha hb, rfl⟩

/-- The closed orbit `cl(A ξ)` — the cyclic subspace generated by `ξ`. -/
def orbitClosure (ξ : H) : Submodule ℂ H :=
  (orbitSubmodule A ξ).topologicalClosure

/-- The orthogonal projection exists (the closure is closed, hence complete) — attached at the
    definition per the binding verdict, so downstream uses never chase the instance. -/
instance (ξ : H) : (orbitClosure A ξ).HasOrthogonalProjection :=
  haveI : CompleteSpace (orbitClosure A ξ) :=
    (orbitSubmodule A ξ).isClosed_topologicalClosure.completeSpace_coe
  Submodule.HasOrthogonalProjection.ofCompleteSpace _

theorem self_mem_orbitClosure (ξ : H) : ξ ∈ orbitClosure A ξ :=
  (orbitSubmodule A ξ).le_topologicalClosure (self_mem_orbitSubmodule A ξ)

/-- The closed orbit is invariant under the algebra (continuity + orbit invariance). -/
theorem orbitClosure_invariant {a : H →L[ℂ] H} (ha : a ∈ A) (ξ : H) :
    ∀ y ∈ orbitClosure A ξ, a y ∈ orbitClosure A ξ := by
  intro y hy
  exact map_mem_closure a.continuous hy fun z hz => orbitSubmodule_invariant A ha ξ z hz

/-- **C1 CAPSTONE — the star projection onto a closed invariant subspace lies in the commutant**:
    if `U` is invariant under every element of the ⋆-closed unital algebra `A`, then
    `P_U ∈ A′`. Invariance of `U` under `star a` (⋆-closure!) gives invariance of `Uᗮ` under `a`;
    range and kernel of `P_U` are then both `a`-invariant, so they commute. -/
theorem starProjection_mem_centralizer {U : Submodule ℂ H} [U.HasOrthogonalProjection]
    (hU : ∀ a ∈ A, ∀ x ∈ U, a x ∈ U) :
    U.starProjection ∈ Set.centralizer (A : Set (H →L[ℂ] H)) := by
  rw [Set.mem_centralizer_iff]
  intro a ha
  have hUa : U ∈ Module.End.invtSubmodule (a : H →ₗ[ℂ] H) :=
    (Module.End.mem_invtSubmodule_iff_forall_mem_of_mem _).mpr fun x hx => hU a ha x hx
  have hUstar : U ∈ Module.End.invtSubmodule
      ((ContinuousLinearMap.adjoint a : H →L[ℂ] H) : H →ₗ[ℂ] H) := by
    refine (Module.End.mem_invtSubmodule_iff_forall_mem_of_mem _).mpr fun x hx => ?_
    have hst : (ContinuousLinearMap.adjoint a) x = (star a) x := by
      rw [star_eq_adjoint]
    show (ContinuousLinearMap.adjoint a) x ∈ U
    rw [hst]
    exact hU (star a) (star_mem ha) x hx
  have hperp : Uᗮ ∈ Module.End.invtSubmodule (a : H →ₗ[ℂ] H) :=
    ContinuousLinearMap.orthogonal_mem_invtSubmodule hUstar
  have hcomm : Commute U.starProjection a :=
    (U.isIdempotentElem_starProjection.commute_iff).mpr
      (by rw [range_starProjection, ker_starProjection]; exact ⟨hUa, hperp⟩)
  exact hcomm.symm.eq

/-- The commutant membership for the cyclic-subspace projection — the form C3 consumes. -/
theorem starProjection_orbitClosure_mem_centralizer (ξ : H) :
    (orbitClosure A ξ).starProjection ∈ Set.centralizer (A : Set (H →L[ℂ] H)) :=
  starProjection_mem_centralizer A fun a ha x hx => orbitClosure_invariant A ha ξ x hx

end QIQTH.VonNeumann
