# ---- GENERATED BY ECMMath.lean (ER.toPy of the PROVEN global-floor ops) — DO NOT hand-edit ----
def _fxCents(rate, fx): return ((rate / fx) * 100)
def _sectorFloor(base, rate, com): return ((base * rate) / com)
def _scaleFloor(scale, c): return (scale * c)
def _envLo(mat): return mat.min(axis=1)   # min over regions (envelope_contains: weighted >= min)
def _envHi(mat): return mat.max(axis=1)   # max over regions (envelope_contains: weighted <= max)
def _weighted(mat, w): return mat @ w     # sum_i w_i*rate_i (envelope_contains: stays in [lo,hi])
