/-
Copyright (c) 2026 PK. All rights reserved.
Released under Apache 2.0 license.

# Falsification gate C — the finite modular flow has discrete spectrum (BW-recurrence bound)

Gate **C** of the QG campaign (`QG_CAMPAIGN_PLAN.md`). A finite modular flow `σ_t = Ad(Δ^{it})` is generated by a
**finite** modular Hamiltonian `K = log Δ` (a finite Hermitian matrix). Its spectrum is therefore a **finite**
subset of `ℝ` — only finitely many "modular energies." The continuum Bisognano–Wichmann modular flow of a Type
III₁ wedge algebra is generated by the **boost**, whose spectrum is **all of `ℝ`** (absolutely continuous, the
flow is mixing). The two cannot coincide: a finite modular Hamiltonian **misses energies** the continuum boost
has, so a finite modular flow can match the continuum BW flow only on a finite-energy window — never globally.

Dynamically this is the **recurrence** distinction: a finite (discrete-spectrum) modular flow is Bohr
almost-periodic and Poincaré-recurrent (it returns near the identity), whereas the continuum BW flow with
absolutely-continuous spectrum `ℝ` is mixing (correlations decay, no recurrence). So QIQT-H's finite
modular/spectral results (`FiniteModularTheory`, the finite RvD shadows) are **finite-spectrum / finite-time /
low-energy** approximations of the continuum boost flow, not exact realizations.

The rigorous, machine-checked core below is the **spectral** statement (the discrete/finite spectrum and the
missed energies); the almost-periodicity/recurrence is its standard dynamical consequence, recorded honestly as
such. Axiom-free (standard `propext`/`Classical.choice`/`Quot.sound`).
-/
import Mathlib.Analysis.Matrix.Spectrum
import Mathlib.LinearAlgebra.Eigenspace.Minpoly

namespace QIQTH.QG

open Matrix

variable {n : Type*} [Fintype n] [DecidableEq n]

/-- **The finite modular Hamiltonian has finite (complex) spectrum.** For a finite modular flow generated by
`K : Matrix n n ℂ` (`= log Δ`), `spectrum ℂ K` is a finite set — at most `|n|` modular eigenvalues. -/
theorem modHam_spectrum_finite (K : Matrix n n ℂ) : (spectrum ℂ K).Finite :=
  K.finite_spectrum

/-- **The finite modular Hamiltonian has finite *real* spectrum** (the modular energies). -/
theorem modHam_real_spectrum_finite (K : Matrix n n ℂ) : (spectrum ℝ K).Finite :=
  K.finite_real_spectrum

/-- **★ Gate C — a finite modular flow misses energies.** Since `spectrum ℝ K` is finite and `ℝ` is infinite,
there is a real "energy" outside the spectrum of any finite modular Hamiltonian. The continuum Bisognano–Wichmann
modular generator (the boost) has spectrum *all* of `ℝ`; hence no finite modular Hamiltonian reproduces it. -/
theorem exists_energy_outside_finite_spectrum (K : Matrix n n ℂ) :
    ∃ lam : ℝ, lam ∉ spectrum ℝ K := by
  obtain ⟨lam, hlam⟩ := (modHam_real_spectrum_finite K).infinite_compl.nonempty
  exact ⟨lam, hlam⟩

/-- **The finite modular spectrum is not the whole real line.** A direct corollary: `spectrum ℝ K ≠ ℝ`, so a
finite modular flow's energy content is a proper (finite) subset of the continuum boost's full spectrum `ℝ` —
the precise, machine-checked form of the BW-recurrence/discrete-spectrum bound. -/
theorem finite_modular_spectrum_ne_real_line (K : Matrix n n ℂ) :
    spectrum ℝ K ≠ Set.univ := by
  obtain ⟨lam, hlam⟩ := exists_energy_outside_finite_spectrum K
  intro h
  rw [h] at hlam
  exact hlam (Set.mem_univ lam)

end QIQTH.QG
