/-
  THE COMMUTATION THEOREM CORRIDOR — toward Tomita's hard half J·M·J = M′ for the tower
  limit (LIMIT ALGEBRA campaign, brick LA1′, LIMIT_ALGEBRA_PLAN.md).

  HELD COMING IN (the tower's FULL modular data): Ω cyclic and separating for
  M := towerLimitVN (S5–S8), the bounded right action with computed adjoint
  (S1–S4, T0_4 `towerRightMulCLM_adjoint`), the modular conjugation J with
  J π_C(a) J = R_{jStage a} (J7 `jconj_towerRep`), and TOMITA II IN INCLUSION FORM
  J·M·J ⊆ M′ (J8 `jconj_limitVN_mem_commutant`). The named wall is the REVERSE inclusion
  M′ ⊆ J·M·J, i.e. the full commutation theorem J·M·J = M′.

  THIS BRICK ADDS (deliverables 1–3 of LA1′):

  1. THE FINITE-STAGE COMMUTATION THEOREM (`stage_commutant_eq_rightMul`,
     `stage_commutant_iff_eq_mulRight`): on a single stage's carrier — the full matrix
     algebra `DiamondAlg L C`, which IS the stage GNS carrier since the Gibbs state is
     faithful — any linear map commuting with every left multiplication is EXACTLY right
     multiplication by its value at 1. The reason the tower-level statement is credible.

  2. `rightLimitVN` = the von Neumann algebra generated by ALL right multiplications —
     a genuine `VonNeumannAlgebra` with: the stage identity both ways
     (`towerRightMulCLM_eq_jconj`, from J7 + `jStage` involutive — jStage is its OWN
     inverse: jStage b = (√ρ⁻¹·b·√ρ)ᴴ, `jStage_eq_conjTranspose_sandwich`); the image
     identity `jconj_image_towerLimitVN` : J·M·J = rightLimitVN AS SETS (SOT transport
     through the anti-unitary J, both directions, star base case closed by T0_4);
     `rightLimitVN_le_commutant` (J8 repackaged through `generatedBy_le` minimality);
     Ω CYCLIC for rightLimitVN (`dense_span_rightLimitVN_orbit_cyclicVec`) and SEPARATING
     for rightLimitVN and for its commutant; and the standard-form duality
     M ⊆ (rightLimitVN)′ (`towerLimitVN_le_rightLimitVN_commutant`).

  3. ORBIT-LEVEL APPROXIMATION OF THE COMMUTANT BY RIGHT MULTIPLICATIONS (the compression
     argument): the stage subspaces V_C := range of the stage germ map are FINITE-
     DIMENSIONAL (the germ map is injective — Gibbs faithfulness,
     `stageGermL_injective`), monotone, and jointly dense; `commutantSymbol T C` is the
     stage-C matrix symbol of the orthogonal projection P_C(TΩ); and for T ∈ M′
       ‖T(germ a) − R_{b_C}(germ a)‖ ≤ ‖π_C(a)‖ · ‖TΩ − P_C(TΩ)‖   (`commutant_orbit_approx`)
     with ‖TΩ − P_C(TΩ)‖ → 0 along the stage filter (`commutant_orbit_tendsto`):
     EVERY COMMUTANT ELEMENT IS, POINTWISE ON THE CYCLIC ORBIT, THE LIMIT OF RIGHT
     MULTIPLICATIONS — with ONE approximant per stage, uniform over the whole orbit.

  MANDATORY FIREWALL (binding): the full equality J·M·J = M′ is NOT claimed and NOT
  proved. Deliverable 3 is pointwise on the cyclic orbit, NOT an SOT/von-Neumann-algebra
  membership statement: upgrading it to M′ ⊆ rightLimitVN needs uniform operator-norm
  control of the approximants R_{b_C} (a Kaplansky-density-type statement), and the
  PRECISE OBSTRUCTION is the weighted-Frobenius vs GNS norm mismatch — the held operator
  bound is ‖R_b‖ ≤ √(Σ_{n,m} ‖b n m‖²·(w_m/w_n)) (`rightFrobBound`, ratio-weighted),
  while what the compression controls is the GNS norm ‖germ b_C‖² =
  Σ_n w_n Σ_m ‖b m n‖² (`gnsInner_self_entrywise`, column-weighted) ≤ ‖T‖²
  (`commutantSymbol_gnsNorm_le`); the ratio weights w_m/w_n are NOT bounded by the
  column weights, so ‖R_{b_C}‖ is uncontrolled by ‖T‖. "J M J = M′ up to the
  norm-control (Kaplansky) gap." No strip-KMS, no type/S-invariant/ITPFI/III₁ claim
  (Araki–Woods 1968 and Connes 1973 stay cited, never invoked); finite-stage Gibbs
  inductive limit only; NOT quantum gravity. No axioms, no `sorry`.
-/
import Mathlib
import QIQTH.TowerGNS.TomitaSecondHalf
import QIQTH.TowerGNS.Tomita
import QIQTH.TowerGNS.JStage

/-! ### The generic nearest-point helper (Hilbert-space geometry, no tower content) -/

namespace QIQTH.TowerGNS

open QIQTH.Keystone QIQTH.Tower QIQTH.Dynamics QIQTH.FiniteModularTheory QIQTH.VonNeumann
open scoped ComplexOrder Matrix DirectSum InnerProductSpace

/-- **The nearest-point property of the orthogonal projection**: the projection onto `U`
    is the closest point of `U` — for any `y ∈ U`, `‖ξ − P_U ξ‖ ≤ ‖ξ − y‖`
    (`starProjection_minimal` + the infimum is under every member). -/
theorem norm_sub_starProjection_le_of_mem {E : Type*} [NormedAddCommGroup E]
    [InnerProductSpace ℂ E] (U : Submodule ℂ E) [U.HasOrthogonalProjection]
    (ξ : E) {y : E} (hy : y ∈ U) :
    ‖ξ - U.starProjection ξ‖ ≤ ‖ξ - y‖ := by
  rw [Submodule.starProjection_minimal]
  exact ciInf_le ⟨0, fun r hr => by obtain ⟨x, rfl⟩ := hr; exact norm_nonneg _⟩
    (⟨y, hy⟩ : U)

variable {M : Type*} [DecidableEq M] (L : LinkDims M) (ω : M → ℝ) (β : ℝ)

/-! ### Deliverable 1 — THE FINITE-STAGE COMMUTATION THEOREM

    On a single stage the GNS carrier of the (faithful) Gibbs state IS the full matrix
    algebra `DiamondAlg L C`, so "operator on the stage GNS space" = "linear map on the
    algebra". The stage commutant of the left regular action is EXACTLY the right regular
    action — the finite commutation theorem, and the reason the tower-level statement
    `J·M·J = M′` is credible. -/

/-- **THE FINITE-STAGE COMMUTATION THEOREM**: a linear map on the stage carrier commuting
    with every LEFT multiplication (`T(a·x) = a·T(x)`) is right multiplication by its value
    at the unit — `T(x) = T(x·1) = x·T(1)` (the hypothesis at `a := x`, `x := 1`). The
    right-multiplication form is automatically ℂ-linear in the symbol (it is
    `LinearMap.mulRight ℂ (T 1)` — see the iff packaging below). -/
theorem stage_commutant_eq_rightMul (C : Finset M)
    (T : DiamondAlg L C →ₗ[ℂ] DiamondAlg L C)
    (hT : ∀ a x : DiamondAlg L C, T (a * x) = a * T x) (x : DiamondAlg L C) :
    T x = x * T 1 := by
  have h := hT x 1
  rwa [mul_one] at h

/-- **The stage-level converse**: right multiplication commutes with every left
    multiplication — associativity, packaged on `LinearMap.mulRight`. -/
theorem stage_rightMul_comm_leftMul (C : Finset M) (b a x : DiamondAlg L C) :
    LinearMap.mulRight ℂ b (a * x) = a * LinearMap.mulRight ℂ b x := by
  rw [LinearMap.mulRight_apply, LinearMap.mulRight_apply, mul_assoc]

/-- **The finite-stage commutant, characterized**: a linear map commutes with the whole
    left regular action IFF it IS the bundled right multiplication by its value at 1 —
    the stage commutant of the left action is exactly the right action. -/
theorem stage_commutant_iff_eq_mulRight (C : Finset M)
    (T : DiamondAlg L C →ₗ[ℂ] DiamondAlg L C) :
    (∀ a x : DiamondAlg L C, T (a * x) = a * T x)
      ↔ T = LinearMap.mulRight ℂ (T 1) := by
  constructor
  · intro hT
    refine LinearMap.ext fun x => ?_
    rw [LinearMap.mulRight_apply]
    exact stage_commutant_eq_rightMul L C T hT x
  · intro h a x
    have hx : ∀ y : DiamondAlg L C, T y = y * T 1 := by
      intro y
      conv_lhs => rw [h]
      rw [LinearMap.mulRight_apply]
    rw [hx (a * x), hx x, mul_assoc]

/-! ### The stage germ map and its faithfulness (the substrate for deliverables 2–3) -/

/-- **The stage germ map**: the corner algebra sent into the tower Hilbert space through
    the pure component at its own stage — `a ↦ ↑(of C a)` — bundled ℂ-linearly. Its range
    is the stage subspace `V_C` of the compression argument. -/
noncomputable def stageGermL (C : Finset M) : DiamondAlg L C →ₗ[ℂ] TowerGNS L ω β where
  toFun a := ((towerOf L ω β C a : TowerPre L ω β) : TowerGNS L ω β)
  map_add' a b := by
    show towerCoe L ω β (DirectSum.of (fun C : Finset M => DiamondAlg L C) C (a + b))
        = towerCoe L ω β (DirectSum.of (fun C : Finset M => DiamondAlg L C) C a)
          + towerCoe L ω β (DirectSum.of (fun C : Finset M => DiamondAlg L C) C b)
    rw [map_add (DirectSum.of (fun C : Finset M => DiamondAlg L C) C) a b]
    exact towerCoe_add_raw L ω β _ _
  map_smul' c a := by
    show towerCoe L ω β (DirectSum.of (fun C : Finset M => DiamondAlg L C) C (c • a))
        = c • towerCoe L ω β (DirectSum.of (fun C : Finset M => DiamondAlg L C) C a)
    have hsm : DirectSum.of (fun C : Finset M => DiamondAlg L C) C (c • a)
        = c • DirectSum.of (fun C : Finset M => DiamondAlg L C) C a := by
      rw [← DirectSum.lof_eq_of ℂ, ← DirectSum.lof_eq_of ℂ, map_smul]
    rw [hsm]
    exact towerCoe_smul_raw L ω β c _

@[simp] theorem stageGermL_apply (C : Finset M) (a : DiamondAlg L C) :
    stageGermL L ω β C a = ((towerOf L ω β C a : TowerPre L ω β) : TowerGNS L ω β) := rfl

/-- The germ map implements the stage GNS form: `⟪germ a, germ b⟫ = ⟪a, b⟫_C = φ_C(aᴴb)`. -/
theorem stageGermL_inner (C : Finset M) (a b : DiamondAlg L C) :
    ⟪stageGermL L ω β C a, stageGermL L ω β C b⟫_ℂ = gnsInner L ω β C a b := by
  rw [stageGermL_apply, stageGermL_apply, inner_coe_of_of,
    pairInner_embed L ω β C C C subset_rfl subset_rfl a b, cornerEmbed_refl,
    cornerEmbed_refl]

/-- **The GNS norm, entrywise** (the COLUMN-weighted Frobenius form):
    `⟪a, a⟫_C = Σ_n w_n · Σ_m ‖a m n‖²` — the weight of the COLUMN index only. Compare
    the right-multiplication operator bound `rightFrobBound a = Σ_{n,m} ‖a n m‖²·(w_m/w_n)`
    (RATIO-weighted): the mismatch between these two quadratic forms IS the Kaplansky wall
    named in the header. -/
theorem gnsInner_self_entrywise (C : Finset M) (a : DiamondAlg L C) :
    gnsInner L ω β C a a
      = ((∑ n, gibbsWeight L C ω β n * ∑ m, Complex.normSq (a m n) : ℝ) : ℂ) := by
  have hentry : ∀ n, (aᴴ * a : DiamondAlg L C) n n
      = ((∑ m, Complex.normSq (a m n) : ℝ) : ℂ) := by
    intro n
    rw [Matrix.mul_apply, Complex.ofReal_sum]
    refine Finset.sum_congr rfl fun m _ => ?_
    rw [Matrix.conjTranspose_apply, Complex.star_def, mul_comm, Complex.mul_conj]
  rw [gnsInner_def, gibbsDensity, QIQTH.Tower.trace_diagonal_mul, Complex.ofReal_sum]
  refine Finset.sum_congr rfl fun n _ => ?_
  rw [hentry n, ← Complex.ofReal_mul]

/-- **Gibbs faithfulness at stage level**: the GNS form is positive DEFINITE — `a ≠ 0` gives
    `0 < re ⟪a, a⟫_C` (all Gibbs weights are strictly positive and a nonzero matrix has a
    nonzero entry). -/
theorem gnsInner_self_re_pos (C : Finset M) {a : DiamondAlg L C} (ha : a ≠ 0) :
    0 < RCLike.re (gnsInner L ω β C a a) := by
  rw [gnsInner_self_entrywise L ω β C a, RCLike.re_to_complex, Complex.ofReal_re]
  obtain ⟨m₀, n₀, hmn⟩ : ∃ m n, a m n ≠ 0 := by
    by_contra h
    refine ha ?_
    ext m n
    have h2 : a m n = 0 := not_not.mp (not_exists.mp (not_exists.mp h m) n)
    simpa using h2
  refine Finset.sum_pos' (fun n _ => mul_nonneg (gibbsWeight_pos L C ω β n).le
    (Finset.sum_nonneg fun m _ => Complex.normSq_nonneg _)) ⟨n₀, Finset.mem_univ n₀, ?_⟩
  refine mul_pos (gibbsWeight_pos L C ω β n₀) ?_
  exact Finset.sum_pos' (fun m _ => Complex.normSq_nonneg _)
    ⟨m₀, Finset.mem_univ m₀, Complex.normSq_pos.mpr hmn⟩

/-- **The stage germ map is INJECTIVE** — the direct-limit gluing never collapses a single
    stage (Gibbs faithfulness): `germ a = 0` forces `⟪a, a⟫_C = 0`, impossible for `a ≠ 0`. -/
theorem stageGermL_injective (C : Finset M) :
    Function.Injective (stageGermL L ω β C) := by
  refine (injective_iff_map_eq_zero _).mpr fun a ha => ?_
  by_contra hne
  have hz : gnsInner L ω β C a a = 0 := by
    rw [← stageGermL_inner L ω β C a a, ha, inner_zero_right]
  have hpos := gnsInner_self_re_pos L ω β C hne
  rw [hz] at hpos
  simp at hpos

/-! ### The stage subspaces `V_C` — finite-dimensional, monotone, jointly dense -/

/-- **The stage subspace** `V_C` — the range of the stage germ map: the (closed,
    finite-dimensional) copy of the corner algebra inside the tower Hilbert space. -/
noncomputable def stageSubspace (C : Finset M) : Submodule ℂ (TowerGNS L ω β) :=
  LinearMap.range (stageGermL L ω β C)

theorem mem_stageSubspace_iff {C : Finset M} {v : TowerGNS L ω β} :
    v ∈ stageSubspace L ω β C ↔ ∃ a : DiamondAlg L C, stageGermL L ω β C a = v :=
  LinearMap.mem_range

instance stageSubspace_finiteDimensional (C : Finset M) :
    FiniteDimensional ℂ (stageSubspace L ω β C) :=
  inferInstanceAs (FiniteDimensional ℂ (LinearMap.range (stageGermL L ω β C)))

instance stageSubspace_completeSpace (C : Finset M) :
    CompleteSpace (stageSubspace L ω β C) :=
  FiniteDimensional.complete ℂ _

/-- **The stage subspaces are monotone**: `C ⊆ C'` gives `V_C ⊆ V_{C'}` — the germ
    identity (R4) presents `germ_C a` as `germ_{C'} (ι a)`. -/
theorem stageSubspace_mono {C C' : Finset M} (h : C ⊆ C') :
    stageSubspace L ω β C ≤ stageSubspace L ω β C' := by
  rintro v ⟨a, rfl⟩
  exact ⟨cornerEmbed L C C' h a, towerGerm L ω β h a⟩

/-- Every coerced pre-vector supported under `K` IS a stage-`K` germ — the germ of its
    stage-`K` collapse (each pure component glues into stage `K` by the germ identity, and
    the collapse is the sum of the embeddings). -/
theorem towerCoe_eq_stageGerm_collapse (K : Finset M)
    (x : ⨁ C : Finset M, DiamondAlg L C) (hx : ∀ C, x C ≠ 0 → C ⊆ K) :
    towerCoe L ω β x = stageGermL L ω β K (collapseRaw L K x) := by
  classical
  have hxsum : x = ∑ C ∈ DFinsupp.support x, DirectSum.of _ C (x C) :=
    (DirectSum.sum_support_of x).symm
  set F : (⨁ C : Finset M, DiamondAlg L C) →+ TowerGNS L ω β :=
    AddMonoidHom.mk' (fun y => towerCoe L ω β y)
      (fun u v => towerCoe_add_raw L ω β u v) with hF
  have hFx : towerCoe L ω β x = F x := rfl
  rw [hFx, hxsum, map_sum F _ (DFinsupp.support x),
    map_sum (collapseRaw L K) _ (DFinsupp.support x),
    map_sum (stageGermL L ω β K) _ (DFinsupp.support x)]
  refine Finset.sum_congr rfl fun C hC => ?_
  have hCK : C ⊆ K := hx C (DFinsupp.mem_support_iff.mp hC)
  rw [collapseRaw_of_le L hCK]
  exact (towerGerm L ω β hCK (x C)).symm

/-- Every coerced pre-vector lies in SOME stage subspace (the one of any corner containing
    its support) — the raw membership feeding the density statement. -/
theorem towerCoe_mem_iUnion_stageSubspace (x : ⨁ C : Finset M, DiamondAlg L C) :
    towerCoe L ω β x
      ∈ ⋃ C : Finset M, (stageSubspace L ω β C : Set (TowerGNS L ω β)) := by
  classical
  rw [Set.mem_iUnion]
  set K : Finset M := (DFinsupp.support x).sup id with hK
  have hx : ∀ C, x C ≠ 0 → C ⊆ K := fun C hC =>
    Finset.le_sup (f := id) (DFinsupp.mem_support_iff.mpr hC)
  exact ⟨K, (mem_stageSubspace_iff L ω β).mpr ⟨collapseRaw L K x,
    (towerCoe_eq_stageGerm_collapse L ω β K x hx).symm⟩⟩

/-- **The stage subspaces are jointly DENSE**: `⋃_C V_C` is dense in the tower Hilbert
    space — every coerced pre-vector lies in the stage subspace of any corner containing
    its support, and the coerced pre-space is dense in the completion. -/
theorem dense_iUnion_stageSubspace :
    Dense (⋃ C : Finset M, (stageSubspace L ω β C : Set (TowerGNS L ω β))) := by
  refine Dense.mono ?_ UniformSpace.Completion.denseRange_coe
  rintro w ⟨x, rfl⟩
  exact towerCoe_mem_iUnion_stageSubspace L ω β x

/-- **The stage projections converge strongly to the identity**: for EVERY vector `ξ`,
    `‖ξ − P_{V_C} ξ‖ → 0` along the directed stage filter — for any ε pick a germ within ε
    (joint density); every deeper stage subspace still contains it (monotonicity), and the
    projection is the NEAREST point. -/
theorem tendsto_norm_sub_starProjection_stageSubspace (ξ : TowerGNS L ω β) :
    Filter.Tendsto
      (fun C : Finset M => ‖ξ - (stageSubspace L ω β C).starProjection ξ‖)
      Filter.atTop (nhds 0) := by
  rw [Metric.tendsto_atTop]
  intro ε hε
  obtain ⟨y, hy, hdist⟩ :=
    (dense_iUnion_stageSubspace L ω β).exists_dist_lt ξ hε
  obtain ⟨C₀, hyC₀⟩ := Set.mem_iUnion.mp hy
  refine ⟨C₀, fun C hC => ?_⟩
  have hy' : y ∈ stageSubspace L ω β C := stageSubspace_mono L ω β hC hyC₀
  rw [Real.dist_0_eq_abs, abs_of_nonneg (norm_nonneg _)]
  refine lt_of_le_of_lt (norm_sub_starProjection_le_of_mem _ ξ hy') ?_
  rw [← dist_eq_norm]
  exact hdist

/-! ### Deliverable 2 — `rightLimitVN`: J·M·J as a genuine von Neumann algebra -/

/-- The set of ALL represented right multiplications, over every stage — the commutant-side
    mirror of the union of the stage algebras. -/
noncomputable def rightStageSet : Set (TowerGNS L ω β →L[ℂ] TowerGNS L ω β) :=
  ⋃ C : Finset M, Set.range (towerRightMulCLM L ω β C)

theorem mem_rightStageSet_iff {T : TowerGNS L ω β →L[ℂ] TowerGNS L ω β} :
    T ∈ rightStageSet L ω β
      ↔ ∃ (C : Finset M) (a : DiamondAlg L C), towerRightMulCLM L ω β C a = T := by
  constructor
  · intro hT
    have h : T ∈ ⋃ C : Finset M, Set.range (towerRightMulCLM L ω β C) := hT
    rw [Set.mem_iUnion] at h
    obtain ⟨C, a, ha⟩ := h
    exact ⟨C, a, ha⟩
  · rintro ⟨C, a, rfl⟩
    have h : towerRightMulCLM L ω β C a
        ∈ ⋃ C : Finset M, Set.range (towerRightMulCLM L ω β C) := by
      rw [Set.mem_iUnion]
      exact ⟨C, a, rfl⟩
    exact h

/-- The right-multiplication set is ⋆-closed — the T0_4 adjoint `(R_a)† = R_{(rightConj² a)ᴴ}`
    is again a right multiplication at the same stage. -/
theorem rightStageSet_star_closed :
    ∀ s ∈ rightStageSet L ω β, star s ∈ rightStageSet L ω β := by
  intro s hs
  rw [mem_rightStageSet_iff] at hs ⊢
  obtain ⟨C, a, rfl⟩ := hs
  refine ⟨C, (rightConj L ω β C (rightConj L ω β C a))ᴴ, ?_⟩
  rw [ContinuousLinearMap.star_eq_adjoint, towerRightMulCLM_adjoint]

/-- **`rightLimitVN` — THE RIGHT-MULTIPLICATION LIMIT VON NEUMANN ALGEBRA**: the von
    Neumann algebra generated by all represented right multiplications. By
    `jconj_image_towerLimitVN` below this IS J·(towerLimitVN)·J, exhibited as a genuine
    `VonNeumannAlgebra` — the candidate commutant of Tomita's hard half. (That it EQUALS
    `M′` is NOT claimed — the Kaplansky wall of the header.) -/
noncomputable def rightLimitVN : VonNeumannAlgebra (TowerGNS L ω β) :=
  QIQTH.VonNeumann.generatedBy (rightStageSet L ω β)

/-- Every represented right multiplication lies in `rightLimitVN`. -/
theorem towerRightMulCLM_mem_rightLimitVN (C : Finset M) (a : DiamondAlg L C) :
    towerRightMulCLM L ω β C a ∈ rightLimitVN L ω β :=
  QIQTH.VonNeumann.subset_generatedBy _
    ((mem_rightStageSet_iff L ω β).mpr ⟨C, a, rfl⟩)

/-! #### The stage identity both ways — `jStage` is its own inverse -/

/-- The explicit inverse formula for the stage conjugation: `jStage b = (√ρ⁻¹·b·√ρ)ᴴ` —
    together with `jStage_involutive` this is why `jStage` is a stage bijection with itself
    as inverse (`a = jStage b` solves `jStage a = b`). -/
theorem jStage_eq_conjTranspose_sandwich (C : Finset M) (b : DiamondAlg L C) :
    jStage L ω β C b = (sqrtInvGibbs L ω β C * b * sqrtGibbs L ω β C)ᴴ := by
  rw [← jStage_conjTranspose, Matrix.conjTranspose_conjTranspose]

/-- **The stage identity, reversed**: every right multiplication is a J-conjugated stage
    operator — `R_b = J π_C(jStage b) J` (J7 at `a := jStage b` + `jStage² = 1`). -/
theorem towerRightMulCLM_eq_jconj (C : Finset M) (b : DiamondAlg L C) :
    towerRightMulCLM L ω β C b
      = jconj L ω β (towerRep L ω β C (jStage L ω β C b)) := by
  rw [jconj_towerRep, jStage_involutive]

/-! #### The `jconj` operator calculus (the algebra laws of T ↦ J·T·J) -/

/-- `jconj 1 = 1` — `J² = 1`. -/
theorem jconj_one : jconj L ω β (1 : TowerGNS L ω β →L[ℂ] TowerGNS L ω β) = 1 := by
  ext ξ
  simp only [jconj_apply, ContinuousLinearMap.one_apply, towerJ_involutive]

/-- `jconj` is additive. -/
theorem jconj_add (T S : TowerGNS L ω β →L[ℂ] TowerGNS L ω β) :
    jconj L ω β (T + S) = jconj L ω β T + jconj L ω β S := by
  ext ξ
  simp only [jconj_apply, ContinuousLinearMap.add_apply, map_add]

/-- **The conjugate-linear twist of `jconj` in the OPERATOR slot**: `J(c•T)J = c̄•(JTJ)` —
    the two anti-linear `J`'s flank a single scalar. -/
theorem jconj_smul (c : ℂ) (T : TowerGNS L ω β →L[ℂ] TowerGNS L ω β) :
    jconj L ω β (c • T) = starRingEnd ℂ c • jconj L ω β T := by
  ext ξ
  simp only [jconj_apply, ContinuousLinearMap.smul_apply, towerJ_smul]

/-- `jconj` is MULTIPLICATIVE (not anti-): `J(TS)J = (JTJ)(JSJ)` since `J² = 1`. -/
theorem jconj_mul (T S : TowerGNS L ω β →L[ℂ] TowerGNS L ω β) :
    jconj L ω β (T * S) = jconj L ω β T * jconj L ω β S := by
  ext ξ
  simp only [jconj_apply, ContinuousLinearMap.mul_apply, towerJ_involutive]

/-- `jconj (algebraMap r) = algebraMap r̄`. -/
theorem jconj_algebraMap (r : ℂ) :
    jconj L ω β (algebraMap ℂ (TowerGNS L ω β →L[ℂ] TowerGNS L ω β) r)
      = algebraMap ℂ (TowerGNS L ω β →L[ℂ] TowerGNS L ω β) (starRingEnd ℂ r) := by
  rw [Algebra.algebraMap_eq_smul_one, Algebra.algebraMap_eq_smul_one, jconj_smul,
    jconj_one]

/-- Each J-conjugated right multiplication is a stage operator: `J R_b J = π_C(jStage b) ∈ M`. -/
theorem jconj_rightStageSet_mem {s : TowerGNS L ω β →L[ℂ] TowerGNS L ω β}
    (hs : s ∈ rightStageSet L ω β) : jconj L ω β s ∈ towerLimitVN L ω β := by
  rw [mem_rightStageSet_iff] at hs
  obtain ⟨C, a, rfl⟩ := hs
  have h1 : jconj L ω β (towerRightMulCLM L ω β C a)
      = towerRep L ω β C (jStage L ω β C a) := by
    conv_lhs => rw [towerRightMulCLM_eq_jconj L ω β C a]
    exact jconj_involutive L ω β _
  rw [h1]
  exact towerRep_mem_towerLimitVN L ω β C (jStage L ω β C a)

/-- **The star-algebra transport**: `jconj` maps the whole ⋆-algebra generated by the right
    multiplications into `M = towerLimitVN` — pair-trick adjoin induction (the motive
    carries `jconj c ∈ M ∧ jconj (star c) ∈ M`; the star base case is T0_4's computed
    adjoint, again a right multiplication). -/
theorem jconj_mem_towerLimitVN_of_mem_adjoin
    {u : TowerGNS L ω β →L[ℂ] TowerGNS L ω β}
    (hu : u ∈ StarAlgebra.adjoin ℂ (rightStageSet L ω β)) :
    jconj L ω β u ∈ towerLimitVN L ω β := by
  have key : ∀ c ∈ StarAlgebra.adjoin ℂ (rightStageSet L ω β),
      jconj L ω β c ∈ towerLimitVN L ω β
        ∧ jconj L ω β (star c) ∈ towerLimitVN L ω β := by
    intro c hc
    induction hc using StarAlgebra.adjoin_induction with
    | mem y hy =>
      exact ⟨jconj_rightStageSet_mem L ω β hy,
        jconj_rightStageSet_mem L ω β (rightStageSet_star_closed L ω β y hy)⟩
    | algebraMap r =>
      constructor
      · rw [jconj_algebraMap]
        exact (towerLimitVN L ω β).toStarSubalgebra.algebraMap_mem _
      · rw [← algebraMap_star_comm, jconj_algebraMap]
        exact (towerLimitVN L ω β).toStarSubalgebra.algebraMap_mem _
    | add y z _ _ hy hz =>
      refine ⟨?_, ?_⟩
      · rw [jconj_add]
        exact add_mem hy.1 hz.1
      · rw [star_add, jconj_add]
        exact add_mem hy.2 hz.2
    | mul y z _ _ hy hz =>
      refine ⟨?_, ?_⟩
      · rw [jconj_mul]
        exact mul_mem hy.1 hz.1
      · rw [star_mul, jconj_mul]
        exact mul_mem hz.2 hy.2
    | star y _ hy =>
      refine ⟨hy.2, ?_⟩
      rw [star_star]
      exact hy.1
  exact (key u hu).1

/-- **Forward transport**: `T ∈ M ⟹ J·T·J ∈ rightLimitVN` — SOT-approximation of `T` from
    the stages, carried through the anti-unitary `J` (J8's transport lemma), lands in the
    right-multiplication generators. -/
theorem jconj_mem_rightLimitVN_of_mem {T : TowerGNS L ω β →L[ℂ] TowerGNS L ω β}
    (hT : T ∈ towerLimitVN L ω β) : jconj L ω β T ∈ rightLimitVN L ω β := by
  rw [mem_towerLimitVN_iff] at hT
  have hj := jconj_sotApprox L ω β hT
  have hsub : jconj L ω β ''
        (⋃ C, (towerStageAlg L ω β C : Set (TowerGNS L ω β →L[ℂ] TowerGNS L ω β)))
      ⊆ rightStageSet L ω β := by
    rintro s ⟨u, hu, rfl⟩
    rw [Set.mem_iUnion] at hu
    obtain ⟨C, hu⟩ := hu
    obtain ⟨a, rfl⟩ := hu
    rw [mem_rightStageSet_iff]
    exact ⟨C, jStage L ω β C a, (jconj_towerRep L ω β C a).symm⟩
  have hR : SOTApprox
      ((StarAlgebra.adjoin ℂ (rightStageSet L ω β)
          : StarSubalgebra ℂ (TowerGNS L ω β →L[ℂ] TowerGNS L ω β))
        : Set (TowerGNS L ω β →L[ℂ] TowerGNS L ω β)) (jconj L ω β T) :=
    (hj.mono hsub).mono (StarAlgebra.subset_adjoin ℂ _)
  have hmem : jconj L ω β T ∈ (QIQTH.VonNeumann.generatedBy (rightStageSet L ω β)
      : Set (TowerGNS L ω β →L[ℂ] TowerGNS L ω β)) := by
    rw [QIQTH.VonNeumann.generatedBy_carrier_eq]
    exact hR
  exact hmem

/-- **Backward transport**: `T ∈ rightLimitVN ⟹ J·T·J ∈ M` — SOT-approximation of `T` from
    the ⋆-algebra of the right generators, carried through `J`, lands in `M` (the
    star-algebra transport), and commuting with `M′` is SOT-closed. -/
theorem jconj_mem_towerLimitVN_of_mem {T : TowerGNS L ω β →L[ℂ] TowerGNS L ω β}
    (hT : T ∈ rightLimitVN L ω β) : jconj L ω β T ∈ towerLimitVN L ω β := by
  have hT' : SOTApprox
      ((StarAlgebra.adjoin ℂ (rightStageSet L ω β)
          : StarSubalgebra ℂ (TowerGNS L ω β →L[ℂ] TowerGNS L ω β))
        : Set (TowerGNS L ω β →L[ℂ] TowerGNS L ω β)) T := by
    have h : T ∈ (QIQTH.VonNeumann.generatedBy (rightStageSet L ω β)
        : Set (TowerGNS L ω β →L[ℂ] TowerGNS L ω β)) := hT
    rwa [QIQTH.VonNeumann.generatedBy_carrier_eq] at h
  have hj := jconj_sotApprox L ω β hT'
  have hstar : ∀ a ∈ (⋃ C, (towerStageAlg L ω β C
      : Set (TowerGNS L ω β →L[ℂ] TowerGNS L ω β))),
      star a ∈ ⋃ C, (towerStageAlg L ω β C
        : Set (TowerGNS L ω β →L[ℂ] TowerGNS L ω β)) := by
    intro a ha
    rw [Set.mem_iUnion] at ha ⊢
    obtain ⟨i, hi⟩ := ha
    exact ⟨i, star_mem hi⟩
  have hcoe : (towerLimitVN L ω β : Set (TowerGNS L ω β →L[ℂ] TowerGNS L ω β))
      = Set.centralizer (Set.centralizer (⋃ C, (towerStageAlg L ω β C
          : Set (TowerGNS L ω β →L[ℂ] TowerGNS L ω β)))) :=
    QIQTH.VonNeumann.generatedBy_coe_of_starClosed hstar
  rw [← SetLike.mem_coe, hcoe]
  refine hj.mem_centralizer ?_
  rintro s ⟨u, hu, rfl⟩
  have hmem : jconj L ω β u ∈ (towerLimitVN L ω β
      : Set (TowerGNS L ω β →L[ℂ] TowerGNS L ω β)) :=
    jconj_mem_towerLimitVN_of_mem_adjoin L ω β hu
  rwa [hcoe] at hmem

/-- **★ THE IMAGE IDENTITY — `J·M·J = rightLimitVN` AS SETS**: the `jconj`-image of the
    tower limit von Neumann algebra IS the right-multiplication limit von Neumann algebra —
    both inclusions by SOT transport through the anti-unitary `J`, using `J² = 1` for the
    reverse. (This exhibits `J·M·J` as a GENUINE von Neumann algebra; NO claim that it
    equals `M′` is made.) -/
theorem jconj_image_towerLimitVN :
    jconj L ω β '' (towerLimitVN L ω β : Set (TowerGNS L ω β →L[ℂ] TowerGNS L ω β))
      = (rightLimitVN L ω β : Set (TowerGNS L ω β →L[ℂ] TowerGNS L ω β)) := by
  apply Set.Subset.antisymm
  · rintro s ⟨T, hT, rfl⟩
    exact jconj_mem_rightLimitVN_of_mem L ω β hT
  · intro T hT
    exact ⟨jconj L ω β T, jconj_mem_towerLimitVN_of_mem L ω β hT,
      jconj_involutive L ω β T⟩

/-- **`rightLimitVN ⊆ M′`** (J8 repackaged through minimality): the right generators lie in
    the commutant, and the generated von Neumann algebra is the smallest one containing
    them. This is Tomita II in the `rightLimitVN` packaging — the reverse inclusion is the
    named wall. -/
theorem rightLimitVN_le_commutant :
    (rightLimitVN L ω β : Set (TowerGNS L ω β →L[ℂ] TowerGNS L ω β))
      ⊆ ((towerLimitVN L ω β).commutant
        : Set (TowerGNS L ω β →L[ℂ] TowerGNS L ω β)) := by
  refine QIQTH.VonNeumann.generatedBy_le _ _ ?_
  intro s hs
  rw [mem_rightStageSet_iff] at hs
  obtain ⟨C, a, rfl⟩ := hs
  exact towerRightMulCLM_mem_commutant L ω β C a

/-- The membership form of `rightLimitVN_le_commutant`. -/
theorem mem_commutant_of_mem_rightLimitVN {T : TowerGNS L ω β →L[ℂ] TowerGNS L ω β}
    (hT : T ∈ rightLimitVN L ω β) : T ∈ (towerLimitVN L ω β).commutant :=
  rightLimitVN_le_commutant L ω β hT

/-- **The standard-form duality**: `M ⊆ (rightLimitVN)′` — centralizer antitonicity applied
    to `rightLimitVN ⊆ M′`, closed by the double-commutant property `M″ = M`. -/
theorem towerLimitVN_le_rightLimitVN_commutant :
    (towerLimitVN L ω β : Set (TowerGNS L ω β →L[ℂ] TowerGNS L ω β))
      ⊆ ((rightLimitVN L ω β).commutant
        : Set (TowerGNS L ω β →L[ℂ] TowerGNS L ω β)) := by
  rw [VonNeumannAlgebra.coe_commutant]
  have h1 : (rightLimitVN L ω β : Set (TowerGNS L ω β →L[ℂ] TowerGNS L ω β))
      ⊆ Set.centralizer (towerLimitVN L ω β
        : Set (TowerGNS L ω β →L[ℂ] TowerGNS L ω β)) := by
    have h := rightLimitVN_le_commutant L ω β
    rwa [VonNeumannAlgebra.coe_commutant] at h
  intro T hT
  apply Set.centralizer_subset h1
  rw [(towerLimitVN L ω β).centralizer_centralizer]
  exact hT

/-- **Ω IS CYCLIC FOR `rightLimitVN`**: the right orbit of Ω contains every pure germ
    (`R_a Ω = ↑(of C a)`), which is R8's dense orbit. Standard form on the commutant side. -/
theorem dense_span_rightLimitVN_orbit_cyclicVec :
    Dense (↑(Submodule.span ℂ {v : TowerGNS L ω β | ∃ T ∈ rightLimitVN L ω β,
        v = T (towerCyclicVec L ω β)}) : Set (TowerGNS L ω β)) := by
  have hsub : {v : TowerGNS L ω β | ∃ (C : Finset M) (a : DiamondAlg L C),
        v = towerRep L ω β C a (towerCyclicVec L ω β)}
      ⊆ {v : TowerGNS L ω β | ∃ T ∈ rightLimitVN L ω β,
        v = T (towerCyclicVec L ω β)} := by
    rintro v ⟨C, a, rfl⟩
    refine ⟨towerRightMulCLM L ω β C a,
      towerRightMulCLM_mem_rightLimitVN L ω β C a, ?_⟩
    rw [towerRep_cyclicVec_of, towerRightMul_cyclicVec]
  exact (dense_span_towerRep_cyclicVec L ω β).mono
    (SetLike.coe_subset_coe.mpr (Submodule.span_mono hsub))

/-- **Ω IS SEPARATING FOR `rightLimitVN`** — free from `rightLimitVN ⊆ M′` and Ω separating
    for `M′` (J8). Together with cyclicity this is the standard-form pair on the
    right-multiplication side. -/
theorem towerCyclicVec_separating_rightLimitVN
    {T : TowerGNS L ω β →L[ℂ] TowerGNS L ω β} (hT : T ∈ rightLimitVN L ω β)
    (h0 : T (towerCyclicVec L ω β) = 0) : T = 0 :=
  towerCyclicVec_separating_commutant L ω β
    (mem_commutant_of_mem_rightLimitVN L ω β hT) h0

/-- **Ω IS SEPARATING FOR `(rightLimitVN)′`** — dual to Ω cyclic for `rightLimitVN`: an
    element of the commutant vanishing on Ω vanishes on the dense orbit `{R_a Ω}` and hence
    everywhere. -/
theorem towerCyclicVec_separating_rightLimitVN_commutant
    {S : TowerGNS L ω β →L[ℂ] TowerGNS L ω β}
    (hS : S ∈ (rightLimitVN L ω β).commutant)
    (h0 : S (towerCyclicVec L ω β) = 0) : S = 0 := by
  refine ContinuousLinearMap.ext_on (dense_span_towerRep_cyclicVec L ω β) ?_
  rintro v ⟨C, a, rfl⟩
  have hRa : towerRep L ω β C a (towerCyclicVec L ω β)
      = towerRightMulCLM L ω β C a (towerCyclicVec L ω β) :=
    (towerRep_cyclicVec_of L ω β C a).trans (towerRightMul_cyclicVec L ω β C a).symm
  have hcomm : towerRightMulCLM L ω β C a * S = S * towerRightMulCLM L ω β C a :=
    VonNeumannAlgebra.mem_commutant_iff.mp hS (towerRightMulCLM L ω β C a)
      (towerRightMulCLM_mem_rightLimitVN L ω β C a)
  rw [hRa, ContinuousLinearMap.zero_apply, ← ContinuousLinearMap.mul_apply, ← hcomm,
    ContinuousLinearMap.mul_apply, h0, map_zero]

/-! ### Deliverable 3 — orbit-level approximation of the commutant by right multiplications

    THE COMPRESSION ARGUMENT. For `T ∈ M′` and a stage `C`, compress `TΩ` onto the stage
    subspace `V_C` and read off its matrix symbol `b_C`; then on the WHOLE stage-`C` orbit,
    with the SINGLE approximant `R_{b_C}`,
      `T(π_C(a)Ω) = π_C(a)(TΩ)` and `R_{b_C}(π_C(a)Ω) = π_C(a)(P_C TΩ)`,
    so the error is `π_C(a)(TΩ − P_C TΩ)` — bounded by `‖π_C(a)‖·‖(1−P_C)TΩ‖ → 0`.

    HONEST SCOPE: this is pointwise on the cyclic orbit, NOT an SOT statement — the
    approximants' OPERATOR norms are uncontrolled (the Kaplansky wall of the header). -/

/-- **The compressed stage symbol** `b_C` of an operator: the unique (by
    `stageGermL_injective`) matrix at stage `C` whose germ is the orthogonal projection of
    `TΩ` onto the stage subspace `V_C`. Defined for EVERY bounded operator; it is the
    right-multiplication symbol of the compression argument when `T ∈ M′`. -/
noncomputable def commutantSymbol (T : TowerGNS L ω β →L[ℂ] TowerGNS L ω β)
    (C : Finset M) : DiamondAlg L C :=
  ((mem_stageSubspace_iff L ω β).mp
    ((stageSubspace L ω β C).starProjection_apply_mem
      (T (towerCyclicVec L ω β)))).choose

/-- The defining property of the symbol: its germ IS the projected vector,
    `germ_C (b_C) = P_{V_C}(TΩ)`. -/
theorem stageGerm_commutantSymbol (T : TowerGNS L ω β →L[ℂ] TowerGNS L ω β)
    (C : Finset M) :
    stageGermL L ω β C (commutantSymbol L ω β T C)
      = (stageSubspace L ω β C).starProjection (T (towerCyclicVec L ω β)) :=
  ((mem_stageSubspace_iff L ω β).mp
    ((stageSubspace L ω β C).starProjection_apply_mem
      (T (towerCyclicVec L ω β)))).choose_spec

/-- **What IS controlled — the GNS norm of the symbol**: `‖germ b_C‖ = ‖P_C(TΩ)‖ ≤ ‖T‖`
    (projection is a contraction, `‖Ω‖ = 1`). The wall is that the right-multiplication
    OPERATOR norm of `b_C` is the RATIO-weighted Frobenius constant (`rightFrobBound`),
    which the column-weighted GNS norm does NOT control. -/
theorem commutantSymbol_gnsNorm_le (T : TowerGNS L ω β →L[ℂ] TowerGNS L ω β)
    (C : Finset M) :
    ‖stageGermL L ω β C (commutantSymbol L ω β T C)‖ ≤ ‖T‖ := by
  rw [stageGerm_commutantSymbol]
  calc ‖(stageSubspace L ω β C).starProjection (T (towerCyclicVec L ω β))‖
      ≤ ‖T (towerCyclicVec L ω β)‖ :=
        (stageSubspace L ω β C).norm_starProjection_apply_le _
    _ ≤ ‖T‖ * ‖towerCyclicVec L ω β‖ := T.le_opNorm _
    _ = ‖T‖ := by rw [norm_cyclicVec, mul_one]

/-- **★ THE ORBIT-LEVEL COMPRESSION BOUND**: for `T` in the commutant of the tower limit,
    the single right multiplication `R_{b_C}` approximates `T` on the WHOLE stage-`C` orbit
    with error `‖π_C(a)‖·‖TΩ − P_C(TΩ)‖`:
    `T(germ a) = π_C(a)(TΩ)` (commutation), `R_{b_C}(germ a) = π_C(a)(P_C TΩ)` (S5
    exchange + the symbol's defining property), and the difference is `π_C(a)` of the
    projection error. ONE approximant, uniform over every `a` at the stage — the
    finite-tuple form of SOT approximation ON THE ORBIT (and only there). -/
theorem commutant_orbit_approx {T : TowerGNS L ω β →L[ℂ] TowerGNS L ω β}
    (hT : T ∈ (towerLimitVN L ω β).commutant) (C : Finset M) (a : DiamondAlg L C) :
    ‖T (stageGermL L ω β C a)
        - towerRightMulCLM L ω β C (commutantSymbol L ω β T C)
            (stageGermL L ω β C a)‖
      ≤ ‖towerRep L ω β C a‖
        * ‖T (towerCyclicVec L ω β)
            - (stageSubspace L ω β C).starProjection (T (towerCyclicVec L ω β))‖ := by
  have hgerm : stageGermL L ω β C a
      = towerRep L ω β C a (towerCyclicVec L ω β) := by
    rw [stageGermL_apply]
    exact (towerRep_cyclicVec_of L ω β C a).symm
  have hcommT : towerRep L ω β C a * T = T * towerRep L ω β C a :=
    VonNeumannAlgebra.mem_commutant_iff.mp hT (towerRep L ω β C a)
      (towerRep_mem_towerLimitVN L ω β C a)
  have hTv : T (stageGermL L ω β C a)
      = towerRep L ω β C a (T (towerCyclicVec L ω β)) := by
    rw [hgerm, ← ContinuousLinearMap.mul_apply, ← hcommT, ContinuousLinearMap.mul_apply]
  have hcommR : towerRep L ω β C a
        * towerRightMulCLM L ω β C (commutantSymbol L ω β T C)
      = towerRightMulCLM L ω β C (commutantSymbol L ω β T C)
        * towerRep L ω β C a := by
    simp only [towerRep_apply]
    exact towerRightMul_comm_towerRep L ω β C C a (commutantSymbol L ω β T C)
  have hsym : ((towerOf L ω β C (commutantSymbol L ω β T C) : TowerPre L ω β)
        : TowerGNS L ω β)
      = (stageSubspace L ω β C).starProjection (T (towerCyclicVec L ω β)) := by
    have hs := stageGerm_commutantSymbol L ω β T C
    rwa [stageGermL_apply] at hs
  have hRv : towerRightMulCLM L ω β C (commutantSymbol L ω β T C)
        (stageGermL L ω β C a)
      = towerRep L ω β C a
          ((stageSubspace L ω β C).starProjection (T (towerCyclicVec L ω β))) := by
    rw [hgerm, ← ContinuousLinearMap.mul_apply, ← hcommR,
      ContinuousLinearMap.mul_apply, towerRightMul_cyclicVec, hsym]
  rw [hTv, hRv, ← map_sub]
  exact (towerRep L ω β C a).le_opNorm _

/-- **★★ THE ORBIT-LEVEL LIMIT — every commutant element is, pointwise on the cyclic
    orbit, the limit of right multiplications**: for `T ∈ M′` and ANY orbit vector
    `germ_{C₁}(a)`, the right multiplications by the compressed symbols converge to `T` at
    that vector along the directed stage filter — eventually (`C ⊇ C₁`) the compression
    bound applies through the germ identity, and the projection errors vanish by the
    strong convergence of the stage projections.

    PRECISELY WHY THIS IS NOT YET THE SOT/vN STATEMENT: SOT membership in `rightLimitVN`
    requires approximation on ARBITRARY finite tuples of vectors, not just orbit vectors;
    extending from the dense orbit to all of `H` passes through the OPERATOR norms
    `‖R_{b_C}‖`, which are the ratio-weighted Frobenius constants `rightFrobBound b_C` —
    NOT controlled by `‖T‖` (only the column-weighted GNS norm of `b_C` is:
    `commutantSymbol_gnsNorm_le`). That uniform-norm upgrade is a Kaplansky-density-type
    statement — the named wall; the full `M′ ⊆ rightLimitVN` (Tomita's hard half) is NOT
    claimed. -/
theorem commutant_orbit_tendsto {T : TowerGNS L ω β →L[ℂ] TowerGNS L ω β}
    (hT : T ∈ (towerLimitVN L ω β).commutant) (C₁ : Finset M) (a : DiamondAlg L C₁) :
    Filter.Tendsto
      (fun C : Finset M => ‖T (stageGermL L ω β C₁ a)
        - towerRightMulCLM L ω β C (commutantSymbol L ω β T C)
            (stageGermL L ω β C₁ a)‖)
      Filter.atTop (nhds 0) := by
  have hg : Filter.Tendsto
      (fun C : Finset M => ‖towerRep L ω β C₁ a‖
        * ‖T (towerCyclicVec L ω β)
            - (stageSubspace L ω β C).starProjection (T (towerCyclicVec L ω β))‖)
      Filter.atTop (nhds 0) := by
    have h := (tendsto_norm_sub_starProjection_stageSubspace L ω β
      (T (towerCyclicVec L ω β))).const_mul ‖towerRep L ω β C₁ a‖
    rwa [mul_zero] at h
  refine squeeze_zero' (Filter.Eventually.of_forall fun C => norm_nonneg _) ?_ hg
  filter_upwards [Filter.eventually_ge_atTop C₁] with C hC
  have hsub : C₁ ⊆ C := hC
  have hgermEq : stageGermL L ω β C₁ a
      = stageGermL L ω β C (cornerEmbed L C₁ C hsub a) := by
    rw [stageGermL_apply, stageGermL_apply]
    exact (towerGerm L ω β hsub a).symm
  have hrepEq : towerRep L ω β C (cornerEmbed L C₁ C hsub a)
      = towerRep L ω β C₁ a :=
    towerRep_cornerEmbed L ω β C₁ C hsub a
  calc ‖T (stageGermL L ω β C₁ a)
        - towerRightMulCLM L ω β C (commutantSymbol L ω β T C)
            (stageGermL L ω β C₁ a)‖
      = ‖T (stageGermL L ω β C (cornerEmbed L C₁ C hsub a))
          - towerRightMulCLM L ω β C (commutantSymbol L ω β T C)
              (stageGermL L ω β C (cornerEmbed L C₁ C hsub a))‖ := by rw [hgermEq]
    _ ≤ ‖towerRep L ω β C (cornerEmbed L C₁ C hsub a)‖
          * ‖T (towerCyclicVec L ω β)
              - (stageSubspace L ω β C).starProjection
                  (T (towerCyclicVec L ω β))‖ :=
        commutant_orbit_approx L ω β hT C (cornerEmbed L C₁ C hsub a)
    _ = ‖towerRep L ω β C₁ a‖
          * ‖T (towerCyclicVec L ω β)
              - (stageSubspace L ω β C).starProjection
                  (T (towerCyclicVec L ω β))‖ := by rw [hrepEq]

/-! ### Deliverable 4 — THE WALL (explored; CHECKPOINT — not closed)

    Upgrading `commutant_orbit_tendsto` to the SOT membership `M′ ⊆ rightLimitVN`
    (equivalently, with deliverable 2, the FULL Tomita equality `J·M·J = M′`) requires the
    approximants `R_{b_C}` to have operator norms bounded uniformly in `C` (then the
    orbit-level estimate extends from the dense orbit to arbitrary tuples and
    `mem_limitVN_iff`-style SOT membership closes). The explored route (i) — control
    `‖R_{b_C}‖` by `‖T‖` through the eigenbasis — FAILS at a precise, named point:

    • the held operator bound is `‖R_b‖ ≤ √(rightFrobBound b)` with
      `rightFrobBound b = Σ_{n,m} ‖b n m‖²·(w_m/w_n)` — the RATIO-weighted Frobenius
      constant (RightMul.lean S1–S3, never claimed sharp or contractive);
    • what the compression controls is `‖germ b_C‖² = re ⟪b_C, b_C⟫_C
      = Σ_n w_n Σ_m ‖b_C m n‖²` (`gnsInner_self_entrywise`) — COLUMN-weighted — with
      `‖germ b_C‖ = ‖P_C TΩ‖ ≤ ‖T‖` (`commutantSymbol_gnsNorm_le`);
    • the ratio weights `w_m/w_n` are unbounded relative to the column weights `w_n` as
      the stage grows (the Gibbs weights spread), so NO estimate
      `rightFrobBound b ≤ K·(GNS norm)²` with stage-uniform `K` is available — the two
      quadratic forms are inequivalent, and the compression gives no entrywise decay to
      compensate.

    The standard escape — smoothing the symbols by bounded functions of Δ (spectral
    truncation of the modular operator, then a Kaplansky-density argument) — is a full
    campaign on the held `ModularOp`/`towerFlow` spectral calculus, NOT this brick.

    CHECKPOINT: deliverables 1–3 shipped; "J M J = M′ up to the norm-control (Kaplansky)
    gap: the commutant is right-multiplication-valued pointwise on the cyclic orbit, with
    the approximants' operator norms uncontrolled by ‖T‖ — the weighted-Frobenius/GNS norm
    mismatch is the precise obstruction." -/

end QIQTH.TowerGNS
