/-
  THE FACTOR — factoriality of the tower limit and the full modular spectrum:
  the operator-level type-III₁ signature (LIMIT ALGEBRA campaign, brick LA2).

  With the full commutation equality J·M·J = M′ in hand (D2a,
  `tomita_commutation_equality`), this brick delivers the two operator-level statements
  that upgrade the T3 ARITHMETIC Araki–Woods fingerprint to statements about the actual
  von Neumann algebra of the tower:

  PART 1 — FACTORIALITY (`center_eq_scalar`, `towerLimitVN_factor`): Z(M) = ℂ·1.
  1. MIRRORED RIGHT-BIMODULARITY: the stage subspace `V_C` absorbs right multiplication
     (`towerRightMul_stageGermL`: R_a(germ x) = germ(x·a)), and the right stage action at a
     fixed stage is ⋆-closed (T0_4's computed adjoint `(R_a)† = R_{(rightConj² a)ᴴ}` is again
     a stage-C right multiplication) — so the stage projection `P_C` commutes with every
     right stage multiplication (`starProjection_comm_towerRightMul`, the C1
     invariant-projection engine mirrored).
  2. THE CENTRAL-SYMBOL CHASE (`central_symbol_commutes`): for `T ∈ M ∩ M′` with compressed
     symbol `b_C := commutantSymbol T C`,
       LEFT  (D2a's chase):  germ(a·b_C) = π_C(a)(P_C(TΩ)) = P_C(T(germ a));
       RIGHT (the mirror):   germ(b_C·a) = R_a(P_C(TΩ)) = P_C(R_a(TΩ)) = P_C(T(R_aΩ))
                             = P_C(T(germ a))   [T ∈ M commutes with R_a — S6],
     so `germ(a·b_C) = germ(b_C·a)` and germ injectivity forces `b_C` CENTRAL in the stage
     matrix algebra.
  3. STAGE CENTERS ARE TRIVIAL (`stage_central_eq_smul_one`): the center of the full matrix
     algebra is ℂ·1 (the two-line matrix-unit argument, entrywise).
  4. THE SCALAR IS CONSTANT IN THE STAGE: `P_C(TΩ) = λ_C•Ω` with
     `λ_C = ⟪Ω, P_C(TΩ)⟫ = ⟪P_CΩ, TΩ⟫ = ⟪Ω, TΩ⟫` — CONSTANT (P_C self-adjoint, P_CΩ = Ω),
     so `P_C(TΩ) = λ•Ω` for EVERY stage; the stage projections converge strongly to 1, so
     `TΩ = λ•Ω` exactly (no limit of scalars is ever taken).
  5. ★ Ω SEPARATES: `(T − λ•1)Ω = 0` with `T − λ•1 ∈ M` gives `T = λ•1` — THE TOWER LIMIT
     IS A FACTOR (trivial center, `HasTrivialCenter` — the honest formulation; Mathlib has
     no `IsFactor` API).

  PART 2 — THE FULL MODULAR SPECTRUM (under the T3 two-frequency irrational-ratio
  hypotheses, stated through the BOUNDED resolvent R = (1+Δ)⁻¹):
  6. THE EIGENVALUE SUPPLY: the pure matrix-unit components are eigenvectors of Δ with
     eigenvalues the Gibbs ratios w_n/w_m (ID2) and of R with eigenvalues (1+w_n/w_m)⁻¹;
     the ratio formula `gibbsWeight_div_eq_exp_sum` computes every achievable log-ratio,
     and — given two frequencies s, t on infinitely many modes with `Irrational (s/t)`,
     link dimensions ≥ 2, and β ≠ 0 — realizes EVERY point of the subgroup generated by
     βs and βt (`exists_gibbs_ratio_realizing`), which is DENSE by Kronecker (T2's
     `dense_closure_pair`). Eigenvalues of the bounded self-adjoint R lie in its spectrum;
     `σ_ℝ(R) ⊆ [0,1]` is held (R2); the spectrum is closed and contains a dense subset of
     (0,1), hence
       ★ `spectrum_towerResolvent_eq_Icc` : σ_ℝ(R) = [0,1] EXACTLY,
     and at the Δ level the closure of the point spectrum is exactly [0,∞)
     (★ `modular_spectrum_full`) — the FULL modular spectrum for the tower state, read
     through the resolvent correspondence δ ↔ (1+δ)⁻¹, with no unbounded-spectrum API used.
  7. ★★ THE CAPSTONE (`operator_level_III1_signature`, hypothesis-free √2 instance
     `operator_level_III1_signature_sqrtTwo`): the conjunction — the tower limit is a
     FACTOR ∧ the modular operator is NOT the identity (Δ ≠ 1, the N3 non-triviality) ∧
     the modular spectrum is FULL (σ(R) = [0,1], i.e. spec Δ = [0,∞) in the resolvent
     sense). THE OPERATOR-LEVEL III₁ SIGNATURE: the strongest honest statement without a
     type API — for a type-III₁ factor this is exactly the expected signature (factor,
     non-tracial, S(M) = [0,∞)), but here it is established for THE TOWER STATE's modular
     operator only.

  MANDATORY FIREWALL (binding): the Connes S-INVARIANT PROPER (the infimum of modular
  spectra over ALL faithful normal states) and the TYPE CLASSIFICATION are ABSENT — no
  type API exists in any proof assistant; Araki–Woods 1968 and Connes 1973 are CITED,
  never invoked. The spectrum statement is for the TOWER STATE's modular operator — one
  distinguished state, not an infimum over states — which is exactly why this is a
  SIGNATURE and not a classification. Finite-stage Gibbs inductive limit only (ITPFI-type
  tower); the two-frequency hypotheses are MODEL INPUTS (the √2 instance discharges them
  concretely). NOT the strong holographic principle, NOT quantum gravity. No axioms, no
  `sorry`.
-/
import Mathlib
import QIQTH.TowerGNS.CommutationEquality
import QIQTH.TowerGNS.Separation
import QIQTH.TowerGNS.ModularEigenvectors
import QIQTH.TowerGNS.ResolventOrder
import QIQTH.NonTracial.ModularNonTrivial
import QIQTH.Tower.KroneckerDensity

namespace QIQTH.TowerGNS

open QIQTH.Keystone QIQTH.Tower QIQTH.Dynamics QIQTH.FiniteModularTheory QIQTH.VonNeumann
open scoped ComplexOrder Matrix DirectSum InnerProductSpace

variable {M : Type*} [DecidableEq M] (L : LinkDims M) (ω : M → ℝ) (β : ℝ)

/-! ### Part 1, Step 1 — MIRRORED RIGHT-BIMODULARITY

    The right-multiplication mirror of D2a's step 1: the stage subspace `V_C` absorbs the
    stage-C RIGHT action (`R_a(germ x) = germ (x·a)`), the right stage action is ⋆-closed
    (T0_4's adjoint is again a stage-C right multiplication), and the C1 engine puts the
    stage projection `P_C` in its commutant. -/

/-- **The germ absorbs the right stage action**: `R_a(germ x) = germ (x·a)` — the
    right-multiplication mirror of `towerRep_stageGermL`. Route: the raw right action of
    `a` on the pure component at stage `C` lands at stage `C ⊔ C` as the product of the
    two embeddings, which is the embedding of `x·a` (functoriality + proof irrelevance),
    and the germ identity glues it back down to stage `C`. -/
theorem towerRightMul_stageGermL (C : Finset M) (a x : DiamondAlg L C) :
    towerRightMulCLM L ω β C a (stageGermL L ω β C x) = stageGermL L ω β C (x * a) := by
  simp only [stageGermL_apply]
  rw [towerRightMulCLM_coe]
  have h1 : towerRightMul L ω β C a (towerOf L ω β C x)
      = towerOf L ω β (C ⊔ C)
          (cornerEmbed L C (C ⊔ C) Finset.subset_union_right x
            * cornerEmbed L C (C ⊔ C) Finset.subset_union_left a) := by
    show rightMulRaw L C a (DirectSum.of (fun C : Finset M => DiamondAlg L C) C x)
        = DirectSum.of (fun C : Finset M => DiamondAlg L C) (C ⊔ C)
            (cornerEmbed L C (C ⊔ C) Finset.subset_union_right x
              * cornerEmbed L C (C ⊔ C) Finset.subset_union_left a)
    rw [rightMulRaw_of]
  have h2 : cornerEmbed L C (C ⊔ C) Finset.subset_union_right x
        * cornerEmbed L C (C ⊔ C) Finset.subset_union_left a
      = cornerEmbed L C (C ⊔ C) Finset.subset_union_left (x * a) := by
    rw [cornerEmbed_mul]
  rw [h1, h2]
  exact towerGerm L ω β Finset.subset_union_left (x * a)

/-- The stage subspace `V_C` is invariant under the stage-C RIGHT multiplications. -/
theorem stageSubspace_invariant_right {C : Finset M} (a : DiamondAlg L C)
    {v : TowerGNS L ω β} (hv : v ∈ stageSubspace L ω β C) :
    towerRightMulCLM L ω β C a v ∈ stageSubspace L ω β C := by
  obtain ⟨x, rfl⟩ := (mem_stageSubspace_iff L ω β).mp hv
  exact (mem_stageSubspace_iff L ω β).mpr
    ⟨x * a, (towerRightMul_stageGermL L ω β C a x).symm⟩

/-- **RIGHT BIMODULARITY — the stage projection commutes with the right stage action**:
    `R_a·P_C = P_C·R_a`. `V_C` is invariant under `R_a` AND under its adjoint
    `(R_a)† = R_{(rightConj² a)ᴴ}` (T0_4 — again a stage-C right multiplication, which is
    all the ⋆-closedness needed), so range and kernel of `P_C` are both `R_a`-invariant —
    the C1 invariant-projection engine, mirrored. -/
theorem starProjection_comm_towerRightMul (C : Finset M) (a : DiamondAlg L C) :
    towerRightMulCLM L ω β C a * (stageSubspace L ω β C).starProjection
      = (stageSubspace L ω β C).starProjection * towerRightMulCLM L ω β C a := by
  have hUa : stageSubspace L ω β C ∈ Module.End.invtSubmodule
      ((towerRightMulCLM L ω β C a : TowerGNS L ω β →L[ℂ] TowerGNS L ω β)
        : TowerGNS L ω β →ₗ[ℂ] TowerGNS L ω β) :=
    (Module.End.mem_invtSubmodule_iff_forall_mem_of_mem _).mpr
      fun _ hx => stageSubspace_invariant_right L ω β a hx
  have hUstar : stageSubspace L ω β C ∈ Module.End.invtSubmodule
      ((ContinuousLinearMap.adjoint (towerRightMulCLM L ω β C a)
          : TowerGNS L ω β →L[ℂ] TowerGNS L ω β)
        : TowerGNS L ω β →ₗ[ℂ] TowerGNS L ω β) := by
    refine (Module.End.mem_invtSubmodule_iff_forall_mem_of_mem _).mpr fun x hx => ?_
    show ContinuousLinearMap.adjoint (towerRightMulCLM L ω β C a) x
      ∈ stageSubspace L ω β C
    rw [towerRightMulCLM_adjoint]
    exact stageSubspace_invariant_right L ω β _ hx
  have hperp : (stageSubspace L ω β C)ᗮ ∈ Module.End.invtSubmodule
      ((towerRightMulCLM L ω β C a : TowerGNS L ω β →L[ℂ] TowerGNS L ω β)
        : TowerGNS L ω β →ₗ[ℂ] TowerGNS L ω β) :=
    ContinuousLinearMap.orthogonal_mem_invtSubmodule hUstar
  have hcomm : Commute (stageSubspace L ω β C).starProjection
      (towerRightMulCLM L ω β C a) :=
    (ContinuousLinearMap.IsIdempotentElem.commute_iff
        ((stageSubspace L ω β C).isIdempotentElem_starProjection)).mpr
      (by rw [Submodule.range_starProjection, Submodule.ker_starProjection]
          exact ⟨hUa, hperp⟩)
  exact hcomm.symm.eq

/-- The pointwise form of right bimodularity: `R_a(P_C ξ) = P_C(R_a ξ)`. -/
theorem starProjection_comm_towerRightMul_apply (C : Finset M) (a : DiamondAlg L C)
    (ξ : TowerGNS L ω β) :
    towerRightMulCLM L ω β C a ((stageSubspace L ω β C).starProjection ξ)
      = (stageSubspace L ω β C).starProjection (towerRightMulCLM L ω β C a ξ) := by
  have happ := congrArg
    (fun F : TowerGNS L ω β →L[ℂ] TowerGNS L ω β => F ξ)
    (starProjection_comm_towerRightMul L ω β C a)
  simpa only [ContinuousLinearMap.mul_apply] using happ

/-! ### Part 1, Step 2 — THE CENTRAL-SYMBOL CHASE

    For `T ∈ M ∩ M′`, the compressed symbol `b_C := commutantSymbol T C` commutes with
    every stage element: the LEFT chase is D2a's step 2 verbatim (`T ∈ M′` + left
    bimodularity), the RIGHT chase is the mirror (`T ∈ M` commutes with the right
    multiplications — S6 — + right bimodularity), and both land on `P_C(T(germ a))`. -/

/-- **THE CENTRAL-SYMBOL CHASE**: for `T ∈ M ∩ M′` the compressed symbol is CENTRAL in the
    stage matrix algebra — `a·b_C = b_C·a` for every `a`. Both `germ(a·b_C)` and
    `germ(b_C·a)` equal `P_C(T(germ a))` (the left and right chases), and the stage germ
    map is injective. -/
theorem central_symbol_commutes {T : TowerGNS L ω β →L[ℂ] TowerGNS L ω β}
    (hT : T ∈ towerLimitVN L ω β) (hT' : T ∈ (towerLimitVN L ω β).commutant)
    (C : Finset M) (a : DiamondAlg L C) :
    a * commutantSymbol L ω β T C = commutantSymbol L ω β T C * a := by
  apply stageGermL_injective L ω β C
  have hcommT : towerRep L ω β C a * T = T * towerRep L ω β C a :=
    VonNeumannAlgebra.mem_commutant_iff.mp hT' (towerRep L ω β C a)
      (towerRep_mem_towerLimitVN L ω β C a)
  have hcommR : towerRightMulCLM L ω β C a * T = T * towerRightMulCLM L ω β C a :=
    towerRightMul_comm_limitVN L ω β C a hT
  have hswapL : towerRep L ω β C a (T (towerCyclicVec L ω β))
      = T (towerRep L ω β C a (towerCyclicVec L ω β)) := by
    rw [← ContinuousLinearMap.mul_apply, hcommT, ContinuousLinearMap.mul_apply]
  have hswapR : towerRightMulCLM L ω β C a (T (towerCyclicVec L ω β))
      = T (towerRightMulCLM L ω β C a (towerCyclicVec L ω β)) := by
    rw [← ContinuousLinearMap.mul_apply, hcommR, ContinuousLinearMap.mul_apply]
  have hleft : stageGermL L ω β C (a * commutantSymbol L ω β T C)
      = (stageSubspace L ω β C).starProjection (T (stageGermL L ω β C a)) := by
    calc stageGermL L ω β C (a * commutantSymbol L ω β T C)
        = towerRep L ω β C a
            (stageGermL L ω β C (commutantSymbol L ω β T C)) :=
          (towerRep_stageGermL L ω β C a _).symm
      _ = towerRep L ω β C a ((stageSubspace L ω β C).starProjection
            (T (towerCyclicVec L ω β))) := by rw [stageGerm_commutantSymbol]
      _ = (stageSubspace L ω β C).starProjection
            (towerRep L ω β C a (T (towerCyclicVec L ω β))) :=
          starProjection_comm_towerRep_apply L ω β C a _
      _ = (stageSubspace L ω β C).starProjection
            (T (towerRep L ω β C a (towerCyclicVec L ω β))) := by rw [hswapL]
      _ = (stageSubspace L ω β C).starProjection (T (stageGermL L ω β C a)) := by
          rw [towerRep_cyclicVec_of, ← stageGermL_apply]
  have hright : stageGermL L ω β C (commutantSymbol L ω β T C * a)
      = (stageSubspace L ω β C).starProjection (T (stageGermL L ω β C a)) := by
    calc stageGermL L ω β C (commutantSymbol L ω β T C * a)
        = towerRightMulCLM L ω β C a
            (stageGermL L ω β C (commutantSymbol L ω β T C)) :=
          (towerRightMul_stageGermL L ω β C a _).symm
      _ = towerRightMulCLM L ω β C a ((stageSubspace L ω β C).starProjection
            (T (towerCyclicVec L ω β))) := by rw [stageGerm_commutantSymbol]
      _ = (stageSubspace L ω β C).starProjection
            (towerRightMulCLM L ω β C a (T (towerCyclicVec L ω β))) :=
          starProjection_comm_towerRightMul_apply L ω β C a _
      _ = (stageSubspace L ω β C).starProjection
            (T (towerRightMulCLM L ω β C a (towerCyclicVec L ω β))) := by rw [hswapR]
      _ = (stageSubspace L ω β C).starProjection (T (stageGermL L ω β C a)) := by
          rw [towerRightMul_cyclicVec, ← stageGermL_apply]
  rw [hleft, hright]

/-! ### Part 1, Step 3 — stage centers are trivial -/

/-- **The center of the stage matrix algebra is ℂ·1**: a matrix commuting with every
    matrix is a scalar — commuting with the matrix units forces the off-diagonal entries
    to vanish and the diagonal to be constant (the standard two-line argument,
    entrywise). -/
theorem stage_central_eq_smul_one (C : Finset M) (b : DiamondAlg L C)
    (hb : ∀ a : DiamondAlg L C, a * b = b * a) :
    ∃ lam : ℂ, b = lam • (1 : DiamondAlg L C) := by
  obtain ⟨i₀⟩ : Nonempty (Micro L C) := inferInstance
  refine ⟨b i₀ i₀, ?_⟩
  ext k l
  rw [Matrix.smul_apply, smul_eq_mul]
  by_cases hkl : k = l
  · subst hkl
    rw [Matrix.one_apply_eq, mul_one]
    have h2 : (Matrix.single i₀ k (1 : ℂ) * b) i₀ k
        = (b * Matrix.single i₀ k (1 : ℂ)) i₀ k :=
      congrArg (fun X : DiamondAlg L C => X i₀ k) (hb (Matrix.single i₀ k 1))
    rw [Matrix.single_mul_apply_same, Matrix.mul_single_apply_same, one_mul, mul_one]
      at h2
    exact h2
  · rw [Matrix.one_apply_ne hkl, mul_zero]
    have h2 : (Matrix.single l l (1 : ℂ) * b) k l
        = (b * Matrix.single l l (1 : ℂ)) k l :=
      congrArg (fun X : DiamondAlg L C => X k l) (hb (Matrix.single l l 1))
    rw [Matrix.mul_single_apply_same, Matrix.single_mul_apply_of_ne _ _ _ _ _ hkl,
      mul_one] at h2
    exact h2.symm

/-! ### Part 1, Step 4 — the scalar is constant in the stage -/

/-- **The germ of the stage unit is the cyclic vector**: `germ_C(1) = Ω` — the germ
    identity glues `↑(of C 1)` down to `↑(of ∅ 1)` (`cornerEmbed 1 = 1`). -/
theorem stageGermL_one (C : Finset M) :
    stageGermL L ω β C (1 : DiamondAlg L C) = towerCyclicVec L ω β := by
  have h := towerGerm L ω β (Finset.empty_subset C) (1 : DiamondAlg L ∅)
  rw [cornerEmbed_one] at h
  rw [stageGermL_apply, towerCyclicVec]
  exact h

/-! ### Part 1, Step 5 — ★ FACTORIALITY -/

/-- **★ THE CENTER IS SCALAR**: every `T ∈ M ∩ M′` is `λ•1` with `λ = ⟪Ω, TΩ⟫`.
    The chase makes the symbol `b_C` central at every stage (step 2), stage centers are
    trivial (step 3), so `P_C(TΩ) = λ_C•Ω`; the λ-CONSTANCY TRICK
    (`λ_C·⟪Ω,Ω⟫ = ⟪Ω, P_C(TΩ)⟫ = ⟪P_CΩ, TΩ⟫ = ⟪Ω, TΩ⟫`) makes the scalar independent of
    the stage, the strong convergence of the stage projections gives `TΩ = λ•Ω` exactly,
    and Ω separates `M` (S7). -/
theorem center_eq_scalar {T : TowerGNS L ω β →L[ℂ] TowerGNS L ω β}
    (hT : T ∈ towerLimitVN L ω β) (hT' : T ∈ (towerLimitVN L ω β).commutant) :
    ∃ lam : ℂ, T = lam • (1 : TowerGNS L ω β →L[ℂ] TowerGNS L ω β) := by
  set lam : ℂ := ⟪towerCyclicVec L ω β, T (towerCyclicVec L ω β)⟫_ℂ with hlam
  refine ⟨lam, ?_⟩
  -- Step A: P_C(TΩ) = λ•Ω for EVERY stage (the λ-constancy trick)
  have hstage : ∀ C : Finset M,
      (stageSubspace L ω β C).starProjection (T (towerCyclicVec L ω β))
        = lam • towerCyclicVec L ω β := by
    intro C
    obtain ⟨μ, hμ⟩ := stage_central_eq_smul_one L C (commutantSymbol L ω β T C)
      (fun a => central_symbol_commutes L ω β hT hT' C a)
    have hgerm : (stageSubspace L ω β C).starProjection (T (towerCyclicVec L ω β))
        = μ • towerCyclicVec L ω β := by
      rw [← stageGerm_commutantSymbol, hμ, map_smul, stageGermL_one]
    have hΩmem : towerCyclicVec L ω β ∈ stageSubspace L ω β C :=
      (mem_stageSubspace_iff L ω β).mpr ⟨1, stageGermL_one L ω β C⟩
    have h1 : ⟪towerCyclicVec L ω β,
        (stageSubspace L ω β C).starProjection (T (towerCyclicVec L ω β))⟫_ℂ = lam := by
      rw [← Submodule.inner_starProjection_left_eq_right,
        Submodule.starProjection_eq_self_iff.mpr hΩmem]
    rw [hgerm, inner_smul_right, inner_cyclicVec_self, mul_one] at h1
    rw [hgerm, h1]
  -- Step B: TΩ = λ•Ω exactly (the projection errors are CONSTANT and tend to 0)
  have hTΩ : T (towerCyclicVec L ω β) = lam • towerCyclicVec L ω β := by
    have htend := tendsto_norm_sub_starProjection_stageSubspace L ω β
      (T (towerCyclicVec L ω β))
    have hconst : (fun C : Finset M => ‖T (towerCyclicVec L ω β)
          - (stageSubspace L ω β C).starProjection (T (towerCyclicVec L ω β))‖)
        = fun _ : Finset M =>
            ‖T (towerCyclicVec L ω β) - lam • towerCyclicVec L ω β‖ :=
      funext fun C => by rw [hstage C]
    rw [hconst] at htend
    have h0 : ‖T (towerCyclicVec L ω β) - lam • towerCyclicVec L ω β‖ = 0 :=
      tendsto_nhds_unique tendsto_const_nhds htend
    rw [← sub_eq_zero]
    exact norm_eq_zero.mp h0
  -- Step C: Ω separates M
  have hmem : T - lam • (1 : TowerGNS L ω β →L[ℂ] TowerGNS L ω β)
      ∈ towerLimitVN L ω β := by
    refine sub_mem hT ?_
    have halg : algebraMap ℂ (TowerGNS L ω β →L[ℂ] TowerGNS L ω β) lam
        ∈ towerLimitVN L ω β :=
      (towerLimitVN L ω β).toStarSubalgebra.algebraMap_mem lam
    rwa [Algebra.algebraMap_eq_smul_one] at halg
  have h0 : (T - lam • (1 : TowerGNS L ω β →L[ℂ] TowerGNS L ω β))
      (towerCyclicVec L ω β) = 0 := by
    rw [ContinuousLinearMap.sub_apply, ContinuousLinearMap.smul_apply,
      ContinuousLinearMap.one_apply, hTΩ, sub_self]
  exact sub_eq_zero.mp (towerCyclicVec_separating L ω β hmem h0)

/-- **The center, characterized**: `T ∈ M ∩ M′ ⟺ T is a scalar` — the scalars are central
    (they commute with everything and `algebraMap ∈ M`), and the center is scalar. -/
theorem mem_center_iff_exists_smul_one {T : TowerGNS L ω β →L[ℂ] TowerGNS L ω β} :
    (T ∈ towerLimitVN L ω β ∧ T ∈ (towerLimitVN L ω β).commutant)
      ↔ ∃ lam : ℂ, T = lam • (1 : TowerGNS L ω β →L[ℂ] TowerGNS L ω β) := by
  constructor
  · rintro ⟨hT, hT'⟩
    exact center_eq_scalar L ω β hT hT'
  · rintro ⟨lam, rfl⟩
    constructor
    · have halg : algebraMap ℂ (TowerGNS L ω β →L[ℂ] TowerGNS L ω β) lam
          ∈ towerLimitVN L ω β :=
        (towerLimitVN L ω β).toStarSubalgebra.algebraMap_mem lam
      rwa [Algebra.algebraMap_eq_smul_one] at halg
    · refine VonNeumannAlgebra.mem_commutant_iff.mpr fun g _ => ?_
      rw [mul_smul_comm, smul_mul_assoc, mul_one, one_mul]

/-- **Trivial center** — the honest `IsFactor`-shaped predicate: every element of
    `A ∩ A′` is a scalar multiple of the identity. (Mathlib's `VonNeumannAlgebra` has no
    factor/type API; this file-local definition states factoriality exactly.) -/
def HasTrivialCenter {H : Type*} [NormedAddCommGroup H] [InnerProductSpace ℂ H]
    [CompleteSpace H] (A : VonNeumannAlgebra H) : Prop :=
  ∀ T ∈ A, T ∈ A.commutant → ∃ lam : ℂ, T = lam • (1 : H →L[ℂ] H)

/-- **★★ THE TOWER LIMIT IS A FACTOR** — `Z(towerLimitVN) = ℂ·1`. -/
theorem towerLimitVN_factor : HasTrivialCenter (towerLimitVN L ω β) :=
  fun _ hT hT' => center_eq_scalar L ω β hT hT'

/-! ### Part 2, Step 6 — the eigenvalue supply and the ratio arithmetic -/

/-- **The Gibbs ratio formula**: `w_n / w_m = exp(Σ_k −βω_k·(n_k − m_k))` — the per-mode
    partition functions cancel identically (exact, never approximated). -/
theorem gibbsWeight_div_eq_exp_sum (C : Finset M) (n m : Micro L C) :
    gibbsWeight L C ω β n / gibbsWeight L C ω β m
      = Real.exp (∑ k : C,
          -(β * ω k.val) * (((n k : ℕ) : ℝ) - ((m k : ℕ) : ℝ))) := by
  simp only [gibbsWeight]
  rw [← Finset.prod_div_distrib, Real.exp_sum]
  refine Finset.prod_congr rfl fun k _ => ?_
  simp only [pMode]
  rw [div_div_div_comm, div_self (ZMode_pos L ω β k.val).ne', div_one, ← Real.exp_sub]
  congr 1
  ring

/-- **The indicator ratio**: raising exactly the modes where `P` holds (and lowering the
    others) realizes the log-ratio `Σ_{j∈C} −βω_j·(±1)` — the concrete eigenvalue
    engineering the density argument consumes. -/
theorem gibbsWeight_ratio_indicator (C : Finset M) (P : M → Prop) [DecidablePred P]
    (hone : ∀ k : M, 1 < L.D k) :
    gibbsWeight L C ω β
        (fun k => if P k.val then (⟨1, hone k.val⟩ : Fin (L.D k.val))
          else ⟨0, L.hD k.val⟩)
      / gibbsWeight L C ω β
        (fun k => if P k.val then (⟨0, L.hD k.val⟩ : Fin (L.D k.val))
          else ⟨1, hone k.val⟩)
      = Real.exp (∑ j ∈ C, -(β * ω j) * (if P j then (1 : ℝ) else -1)) := by
  rw [gibbsWeight_div_eq_exp_sum]
  congr 1
  rw [← Finset.sum_coe_sort C (fun j => -(β * ω j) * (if P j then (1 : ℝ) else -1))]
  refine Finset.sum_congr rfl fun k _ => ?_
  by_cases hP : P k.val
  · simp only [if_pos hP]
    norm_num
  · simp only [if_neg hP]
    norm_num

/-- **THE REALIZATION**: with two frequencies `s`, `t` each carried by infinitely many
    modes and all link dimensions ≥ 2, EVERY point `a·(−βs) + b·(−βt)` of the subgroup
    generated by `−βs` and `−βt` is an achievable Gibbs log-ratio — pick `|a|` fresh
    `s`-modes and `|b|` fresh `t`-modes and raise/lower according to the signs. -/
theorem exists_gibbs_ratio_realizing (hD : ∀ k : M, 2 ≤ L.D k) {s t : ℝ}
    (hs : {k : M | ω k = s}.Infinite) (ht : {k : M | ω k = t}.Infinite) (a b : ℤ) :
    ∃ (C : Finset M) (n m : Micro L C),
      gibbsWeight L C ω β n / gibbsWeight L C ω β m
        = Real.exp ((a : ℝ) * -(β * s) + (b : ℝ) * -(β * t)) := by
  have hone : ∀ k : M, 1 < L.D k := fun k => lt_of_lt_of_le one_lt_two (hD k)
  obtain ⟨A, hA, hAcard⟩ := hs.exists_subset_card_eq a.natAbs
  obtain ⟨B, hB, hBcard⟩ := (ht.diff A.finite_toSet).exists_subset_card_eq b.natAbs
  have hdisj : Disjoint A B := Finset.disjoint_left.mpr fun j hjA hjB =>
    (hB (Finset.mem_coe.mpr hjB)).2 (Finset.mem_coe.mpr hjA)
  refine ⟨A ∪ B, _, _,
    (gibbsWeight_ratio_indicator L ω β (A ∪ B)
      (fun j => (j ∈ A ∧ 0 ≤ a) ∨ (j ∉ A ∧ 0 ≤ b)) hone).trans ?_⟩
  congr 1
  rw [Finset.sum_union hdisj]
  have hAsum : ∑ j ∈ A,
      -(β * ω j) * (if (j ∈ A ∧ 0 ≤ a) ∨ (j ∉ A ∧ 0 ≤ b) then (1 : ℝ) else -1)
      = (a : ℝ) * -(β * s) := by
    have hgA : ∀ j ∈ A,
        -(β * ω j) * (if (j ∈ A ∧ 0 ≤ a) ∨ (j ∉ A ∧ 0 ≤ b) then (1 : ℝ) else -1)
          = -(β * s) * (if 0 ≤ a then (1 : ℝ) else -1) := by
      intro j hj
      have hωj : ω j = s := hA (Finset.mem_coe.mpr hj)
      rw [hωj]
      by_cases ha0 : 0 ≤ a
      · rw [if_pos (Or.inl ⟨hj, ha0⟩), if_pos ha0]
      · have hcond : ¬((j ∈ A ∧ 0 ≤ a) ∨ (j ∉ A ∧ 0 ≤ b)) := by
          rintro (⟨-, h⟩ | ⟨hnot, -⟩)
          · exact ha0 h
          · exact hnot hj
        rw [if_neg hcond, if_neg ha0]
    rw [Finset.sum_congr rfl hgA, Finset.sum_const, nsmul_eq_mul, hAcard]
    by_cases ha0 : 0 ≤ a
    · rw [if_pos ha0]
      have hcast : ((a.natAbs : ℕ) : ℝ) = (a : ℝ) := by
        rw [Nat.cast_natAbs, abs_of_nonneg ha0]
      rw [hcast]; ring
    · rw [if_neg ha0]
      have hcast : ((a.natAbs : ℕ) : ℝ) = -(a : ℝ) := by
        rw [Nat.cast_natAbs, abs_of_neg (not_le.mp ha0), Int.cast_neg]
      rw [hcast]; ring
  have hBsum : ∑ j ∈ B,
      -(β * ω j) * (if (j ∈ A ∧ 0 ≤ a) ∨ (j ∉ A ∧ 0 ≤ b) then (1 : ℝ) else -1)
      = (b : ℝ) * -(β * t) := by
    have hgB : ∀ j ∈ B,
        -(β * ω j) * (if (j ∈ A ∧ 0 ≤ a) ∨ (j ∉ A ∧ 0 ≤ b) then (1 : ℝ) else -1)
          = -(β * t) * (if 0 ≤ b then (1 : ℝ) else -1) := by
      intro j hj
      have hωj : ω j = t := (hB (Finset.mem_coe.mpr hj)).1
      have hjA : j ∉ A := fun h => (Finset.disjoint_left.mp hdisj h) hj
      rw [hωj]
      by_cases hb0 : 0 ≤ b
      · rw [if_pos (Or.inr ⟨hjA, hb0⟩), if_pos hb0]
      · have hcond : ¬((j ∈ A ∧ 0 ≤ a) ∨ (j ∉ A ∧ 0 ≤ b)) := by
          rintro (⟨hin, -⟩ | ⟨-, h⟩)
          · exact hjA hin
          · exact hb0 h
        rw [if_neg hcond, if_neg hb0]
    rw [Finset.sum_congr rfl hgB, Finset.sum_const, nsmul_eq_mul, hBcard]
    by_cases hb0 : 0 ≤ b
    · rw [if_pos hb0]
      have hcast : ((b.natAbs : ℕ) : ℝ) = (b : ℝ) := by
        rw [Nat.cast_natAbs, abs_of_nonneg hb0]
      rw [hcast]; ring
    · rw [if_neg hb0]
      have hcast : ((b.natAbs : ℕ) : ℝ) = -(b : ℝ) := by
        rw [Nat.cast_natAbs, abs_of_neg (not_le.mp hb0), Int.cast_neg]
      rw [hcast]; ring
  rw [hAsum, hBsum]

/-- The set of achievable Gibbs LOG-RATIOS of the tower — the modular exponents the
    eigenvalue supply realizes. -/
def gibbsRatioExponents : Set ℝ :=
  {x : ℝ | ∃ (C : Finset M) (n m : Micro L C),
    gibbsWeight L C ω β n / gibbsWeight L C ω β m = Real.exp x}

/-- **★ THE DENSITY ENGINE**: under the T3-style hypotheses (two frequencies on infinitely
    many modes, irrational ratio, `β ≠ 0`, link dimensions ≥ 2), the achievable Gibbs
    log-ratios are DENSE in ℝ — they contain the subgroup generated by `−βs` and `−βt`
    (the realization), which is dense by Kronecker (T2 `dense_closure_pair`). -/
theorem dense_gibbsRatioExponents (hD : ∀ k : M, 2 ≤ L.D k) (hβ : β ≠ 0) {s t : ℝ}
    (hs : {k : M | ω k = s}.Infinite) (ht : {k : M | ω k = t}.Infinite)
    (hirr : Irrational (s / t)) :
    Dense (gibbsRatioExponents L ω β) := by
  have hst : -(β * s) / -(β * t) = s / t := by
    rw [neg_div_neg_eq, mul_div_mul_left s t hβ]
  have hirr' : Irrational (-(β * s) / -(β * t)) := by
    rw [hst]; exact hirr
  have hdense := dense_closure_pair hirr'
  let G : AddSubgroup ℝ :=
    { carrier := {x : ℝ | ∃ p q : ℤ, x = (p : ℝ) * -(β * s) + (q : ℝ) * -(β * t)}
      zero_mem' := ⟨0, 0, by norm_num⟩
      add_mem' := by
        intro x y hx hy
        obtain ⟨p₁, q₁, rfl⟩ := hx
        obtain ⟨p₂, q₂, rfl⟩ := hy
        exact ⟨p₁ + p₂, q₁ + q₂, by push_cast; ring⟩
      neg_mem' := by
        intro x hx
        obtain ⟨p, q, rfl⟩ := hx
        exact ⟨-p, -q, by push_cast; ring⟩ }
  have hle : AddSubgroup.closure ({-(β * s), -(β * t)} : Set ℝ) ≤ G := by
    rw [AddSubgroup.closure_le]
    intro x hx
    rcases Set.mem_insert_iff.mp hx with rfl | hx
    · exact ⟨1, 0, by push_cast; ring⟩
    · rw [Set.mem_singleton_iff.mp hx]
      exact ⟨0, 1, by push_cast; ring⟩
  refine hdense.mono ?_
  intro x hx
  obtain ⟨p, q, rfl⟩ := hle hx
  obtain ⟨C, n, m, hnm⟩ := exists_gibbs_ratio_realizing L ω β hD hs ht p q
  exact ⟨C, n, m, hnm⟩

/-! ### Part 2 — eigenvalues live in the spectrum of the BOUNDED resolvent -/

/-- **Eigenvalue ⟹ spectrum** for the bounded resolvent: a real eigenvalue with a
    NONZERO eigenvector lies in `σ_ℝ(R)` — a unit `algebraMap r − R` would be injective,
    but the eigenvector is in its kernel. -/
theorem mem_spectrum_towerResolvent_of_eigenvector {r : ℝ} {x : TowerGNS L ω β}
    (hx : x ≠ 0) (heig : towerResolvent L ω β x = ((r : ℝ) : ℂ) • x) :
    r ∈ spectrum ℝ (towerResolvent L ω β) := by
  rw [spectrum.mem_iff]
  intro hunit
  obtain ⟨u, hu⟩ := hunit
  have hsmul : r • x = ((r : ℝ) : ℂ) • x := by
    rw [← algebraMap_smul ℂ r x, Complex.coe_algebraMap]
  have hker : (algebraMap ℝ (TowerGNS L ω β →L[ℂ] TowerGNS L ω β) r
      - towerResolvent L ω β) x = 0 := by
    rw [ContinuousLinearMap.sub_apply, heig, Algebra.algebraMap_eq_smul_one,
      ContinuousLinearMap.smul_apply, ContinuousLinearMap.one_apply, hsmul, sub_self]
  have h1 : ((↑u⁻¹ * ↑u : TowerGNS L ω β →L[ℂ] TowerGNS L ω β)) x = x := by
    rw [u.inv_mul, ContinuousLinearMap.one_apply]
  rw [ContinuousLinearMap.mul_apply, hu, hker, map_zero] at h1
  exact hx h1.symm

/-- **The eigenvalue supply, in the spectrum**: every Gibbs ratio `w_n/w_m` puts the point
    `(1 + w_n/w_m)⁻¹` into `σ_ℝ(R)` — ID2's matrix-unit eigenvector (nonzero by N3)
    transported through Δ → R. -/
theorem resolvent_ratio_mem_spectrum (C : Finset M) (n m : Micro L C) :
    (1 + gibbsWeight L C ω β n / gibbsWeight L C ω β m)⁻¹
      ∈ spectrum ℝ (towerResolvent L ω β) :=
  mem_spectrum_towerResolvent_of_eigenvector L ω β
    (QIQTH.NonTracial.towerOf_single_ne_zero L ω β C n m one_ne_zero)
    (towerResolvent_of_single L ω β C n m 1)

/-! ### Part 2 — ★ THE FULL RESOLVENT SPECTRUM -/

/-- **The density half**: `[0,1] ⊆ σ_ℝ(R)` — the eigenvalues `(1 + e^x)⁻¹` for the dense
    exponent set are dense in `(0,1)` (the map `x ↦ (1+e^x)⁻¹` is continuous with the
    explicit section `y ↦ log(y⁻¹ − 1)`), and the spectrum is closed. -/
theorem Icc_subset_spectrum_towerResolvent (hD : ∀ k : M, 2 ≤ L.D k) (hβ : β ≠ 0)
    {s t : ℝ} (hs : {k : M | ω k = s}.Infinite) (ht : {k : M | ω k = t}.Infinite)
    (hirr : Irrational (s / t)) :
    Set.Icc (0 : ℝ) 1 ⊆ spectrum ℝ (towerResolvent L ω β) := by
  have hEdense := dense_gibbsRatioExponents L ω β hD hβ hs ht hirr
  have hfc : Continuous fun x : ℝ => (1 + Real.exp x)⁻¹ := by
    refine Continuous.inv₀ (continuous_const.add Real.continuous_exp) fun x => ?_
    positivity
  have himg : (fun x : ℝ => (1 + Real.exp x)⁻¹) '' gibbsRatioExponents L ω β
      ⊆ spectrum ℝ (towerResolvent L ω β) := by
    rintro y ⟨x, ⟨C, n, m, hx⟩, rfl⟩
    have h := resolvent_ratio_mem_spectrum L ω β C n m
    rw [hx] at h
    exact h
  have hIoo : Set.Ioo (0 : ℝ) 1
      ⊆ closure ((fun x : ℝ => (1 + Real.exp x)⁻¹) '' gibbsRatioExponents L ω β) := by
    rintro y ⟨hy0, hy1⟩
    have hy' : (0 : ℝ) < y⁻¹ - 1 := by
      rw [sub_pos]
      exact (one_lt_inv₀ hy0).mpr hy1
    have hfx : (fun x : ℝ => (1 + Real.exp x)⁻¹) (Real.log (y⁻¹ - 1)) = y := by
      show (1 + Real.exp (Real.log (y⁻¹ - 1)))⁻¹ = y
      rw [Real.exp_log hy', show (1 : ℝ) + (y⁻¹ - 1) = y⁻¹ by ring, inv_inv]
    exact image_closure_subset_closure_image hfc ⟨_, hEdense _, hfx⟩
  intro z hz
  have h1 : Set.Icc (0 : ℝ) 1
      ⊆ closure ((fun x : ℝ => (1 + Real.exp x)⁻¹) '' gibbsRatioExponents L ω β) := by
    rw [← closure_Ioo (by norm_num : (0 : ℝ) ≠ 1)]
    calc closure (Set.Ioo (0 : ℝ) 1)
        ⊆ closure (closure ((fun x : ℝ => (1 + Real.exp x)⁻¹) ''
            gibbsRatioExponents L ω β)) := closure_mono hIoo
      _ = closure ((fun x : ℝ => (1 + Real.exp x)⁻¹) ''
            gibbsRatioExponents L ω β) := closure_closure
  exact closure_minimal himg (spectrum.isClosed _) (h1 hz)

/-- **★ THE FULL RESOLVENT SPECTRUM — `σ_ℝ((1+Δ)⁻¹) = [0,1]` EXACTLY** (under the
    two-frequency irrational-ratio hypotheses): held `σ ⊆ [0,1]` (R2) + the density half.
    This is the bounded-operator reading of "spec Δ = [0,∞)": under the order-reversing
    homeomorphism `δ ↦ (1+δ)⁻¹`, the interval `[0,1]` is exactly the closure of the image
    of `[0,∞)` (with `0` the image of the point at infinity). -/
theorem spectrum_towerResolvent_eq_Icc (hD : ∀ k : M, 2 ≤ L.D k) (hβ : β ≠ 0)
    {s t : ℝ} (hs : {k : M | ω k = s}.Infinite) (ht : {k : M | ω k = t}.Infinite)
    (hirr : Irrational (s / t)) :
    spectrum ℝ (towerResolvent L ω β) = Set.Icc (0 : ℝ) 1 :=
  Set.Subset.antisymm (fun r hr => towerResolvent_spectrum_mem_Icc L ω β ⟨r, hr⟩)
    (Icc_subset_spectrum_towerResolvent L ω β hD hβ hs ht hirr)

/-! ### Part 2 — the Δ-level reading: the point spectrum of Δ closes up to [0,∞) -/

/-- The POINT SPECTRUM of the (unbounded) modular operator: the real numbers `δ` carrying
    a genuine nonzero eigenvector `Δx = δ•x` in the domain. (No unbounded-spectrum API is
    used anywhere — this is the honest eigenvalue-level object.) -/
def modularPointSpectrum : Set ℝ :=
  {δ : ℝ | ∃ (x : TowerGNS L ω β) (hx : x ∈ towerModularDom L ω β),
    x ≠ 0 ∧ towerModularOp L ω β ⟨x, hx⟩ = ((δ : ℝ) : ℂ) • x}

/-- Every Δ-eigenvalue is nonnegative — positivity `⟪Δx, x⟫ = ‖S̄x‖²` (M5.1) forces
    `δ·‖x‖² = ‖S̄x‖² ≥ 0` with `‖x‖ > 0`. -/
theorem modularPointSpectrum_nonneg :
    ∀ δ ∈ modularPointSpectrum L ω β, 0 ≤ δ := by
  rintro δ ⟨x, hx, hx0, heig⟩
  have hbar := mem_bar_of_mem_towerModularDom L ω β hx
  have hF := barF_of_mem_towerModularDom L ω β hx hbar
  have hcongr : towerModularOp L ω β ⟨x, mem_towerModularDom L ω β hbar hF⟩
      = towerModularOp L ω β ⟨x, hx⟩ :=
    towerModularOp_congr L ω β _ hx rfl
  have hxx : ⟪x, x⟫_ℂ = ((‖x‖ : ℝ) : ℂ) ^ 2 := inner_self_eq_norm_sq_to_K _
  have hinner := towerModularOp_inner_self L ω β hbar hF
  rw [hcongr, heig, inner_smul_left, Complex.conj_ofReal, hxx,
    ← Complex.ofReal_pow, ← Complex.ofReal_pow, ← Complex.ofReal_mul] at hinner
  have hreal : δ * ‖x‖ ^ 2 = ‖towerTomitaBar L ω β ⟨x, hbar⟩‖ ^ 2 := by
    exact_mod_cast hinner
  have hx2 : 0 < ‖x‖ ^ 2 := pow_pos (norm_pos_iff.mpr hx0) 2
  by_contra h
  have hδneg : δ < 0 := not_le.mp h
  nlinarith [sq_nonneg ‖towerTomitaBar L ω β ⟨x, hbar⟩‖]

/-- **★ THE FULL MODULAR SPECTRUM — the Δ-level reading**: under the two-frequency
    irrational-ratio hypotheses, the closure of the POINT SPECTRUM of the tower modular
    operator is EXACTLY `[0,∞)` — the matrix-unit eigenvalues realize a dense subgroup of
    ratios (Kronecker), and every eigenvalue is nonnegative. This is "spec Δ = [0,∞)"
    stated without any unbounded-spectrum API: the honest deliverable at the Δ level
    (`spectrum_towerResolvent_eq_Icc` is the exact bounded-operator form). -/
theorem modular_spectrum_full (hD : ∀ k : M, 2 ≤ L.D k) (hβ : β ≠ 0)
    {s t : ℝ} (hs : {k : M | ω k = s}.Infinite) (ht : {k : M | ω k = t}.Infinite)
    (hirr : Irrational (s / t)) :
    closure (modularPointSpectrum L ω β) = Set.Ici (0 : ℝ) := by
  apply Set.Subset.antisymm
  · calc closure (modularPointSpectrum L ω β)
        ⊆ closure (Set.Ici (0 : ℝ)) :=
          closure_mono fun δ hδ => modularPointSpectrum_nonneg L ω β δ hδ
      _ = Set.Ici (0 : ℝ) := isClosed_Ici.closure_eq
  · have hEdense := dense_gibbsRatioExponents L ω β hD hβ hs ht hirr
    have hsub : Real.exp '' gibbsRatioExponents L ω β
        ⊆ modularPointSpectrum L ω β := by
      rintro y ⟨x, ⟨C, n, m, hx⟩, rfl⟩
      refine ⟨_, of_mem_towerModularDom L ω β C (Matrix.single n m 1),
        QIQTH.NonTracial.towerOf_single_ne_zero L ω β C n m one_ne_zero, ?_⟩
      rw [← hx]
      exact towerModularOp_of_single L ω β C n m 1
    have hIoi : Set.Ioi (0 : ℝ)
        ⊆ closure (Real.exp '' gibbsRatioExponents L ω β) := fun y hy =>
      image_closure_subset_closure_image Real.continuous_exp
        ⟨Real.log y, hEdense _, Real.exp_log hy⟩
    calc Set.Ici (0 : ℝ)
        = closure (Set.Ioi (0 : ℝ)) := (closure_Ioi (0 : ℝ)).symm
      _ ⊆ closure (closure (Real.exp '' gibbsRatioExponents L ω β)) :=
          closure_mono hIoi
      _ = closure (Real.exp '' gibbsRatioExponents L ω β) := closure_closure
      _ ⊆ closure (modularPointSpectrum L ω β) := closure_mono hsub

/-! ### Part 2, Step 7 — ★★ THE CAPSTONE: the operator-level III₁ signature -/

/-- A one-mode stage with a nonzero frequency has NON-CONSTANT Gibbs weights — the input
    to N3's modular non-triviality (`Δ ≠ 1`). -/
theorem gibbsWeight_singleton_ne (hone : ∀ k : M, 1 < L.D k) (hβ : β ≠ 0) {k₀ : M}
    {s : ℝ} (hk₀ : ω k₀ = s) (hs0 : s ≠ 0) :
    gibbsWeight L ({k₀} : Finset M) ω β (fun k => ⟨1, hone k.val⟩)
      ≠ gibbsWeight L ({k₀} : Finset M) ω β (fun k => ⟨0, L.hD k.val⟩) := by
  intro heq
  have hratio : gibbsWeight L ({k₀} : Finset M) ω β (fun k => ⟨1, hone k.val⟩)
      / gibbsWeight L ({k₀} : Finset M) ω β (fun k => ⟨0, L.hD k.val⟩)
      = Real.exp (-(β * s)) := by
    rw [gibbsWeight_div_eq_exp_sum]
    congr 1
    trans (∑ k : ({k₀} : Finset M), -(β * ω k.val))
    · refine Finset.sum_congr rfl fun k _ => ?_
      show -(β * ω k.val) * (((1 : ℕ) : ℝ) - ((0 : ℕ) : ℝ)) = -(β * ω k.val)
      norm_num
    · rw [Finset.sum_coe_sort ({k₀} : Finset M) (fun j => -(β * ω j)),
        Finset.sum_singleton, hk₀]
  rw [heq, div_self (gibbsWeight_pos L ({k₀} : Finset M) ω β _).ne'] at hratio
  have h0 : -(β * s) = 0 := Real.exp_injective (by rw [Real.exp_zero]; exact hratio.symm)
  have hbs : β * s = 0 := by linarith
  rcases mul_eq_zero.mp hbs with h | h
  · exact hβ h
  · exact hs0 h

/-- **★★ THE OPERATOR-LEVEL III₁ SIGNATURE** — under the T3-style model hypotheses (two
    frequencies `s`, `t` on infinitely many modes, `Irrational (s/t)`, link dimensions
    ≥ 2, `β ≠ 0`), the tower limit von Neumann algebra satisfies the conjunction:

    1. it is a FACTOR (trivial center — every central element is a scalar);
    2. the tower state is NOT tracial at the modular level: Δ moves a vector (Δ ≠ 1,
       the N3 non-triviality witness on a one-mode matrix unit);
    3. the MODULAR SPECTRUM IS FULL: `σ_ℝ((1+Δ)⁻¹) = [0,1]` exactly — i.e.
       spec Δ = [0,∞) in the resolvent sense.

    For a type-III₁ factor this is exactly the expected signature (factor, non-tracial,
    modular spectrum [0,∞)). FIREWALL: this is the signature FOR THE TOWER STATE — the
    Connes S-invariant proper (the infimum over ALL faithful normal states) and the type
    classification stay CITED (Araki–Woods 1968; Connes 1973), never invoked; no type API
    exists in any proof assistant. -/
theorem operator_level_III1_signature (hD : ∀ k : M, 2 ≤ L.D k) (hβ : β ≠ 0)
    {s t : ℝ} (hs : {k : M | ω k = s}.Infinite) (ht : {k : M | ω k = t}.Infinite)
    (hirr : Irrational (s / t)) :
    (∀ T ∈ towerLimitVN L ω β, T ∈ (towerLimitVN L ω β).commutant →
        ∃ lam : ℂ, T = lam • (1 : TowerGNS L ω β →L[ℂ] TowerGNS L ω β))
    ∧ (∃ (C : Finset M) (n m : Micro L C),
        towerModularOp L ω β
            ⟨((towerOf L ω β C (Matrix.single n m 1) : TowerPre L ω β)
                : TowerGNS L ω β),
              of_mem_towerModularDom L ω β C (Matrix.single n m 1)⟩
          ≠ ((towerOf L ω β C (Matrix.single n m 1) : TowerPre L ω β)
              : TowerGNS L ω β))
    ∧ spectrum ℝ (towerResolvent L ω β) = Set.Icc (0 : ℝ) 1 := by
  have hone : ∀ k : M, 1 < L.D k := fun k => lt_of_lt_of_le one_lt_two (hD k)
  have hs0 : s ≠ 0 := by
    intro h
    apply hirr
    refine ⟨0, ?_⟩
    rw [h, zero_div, Rat.cast_zero]
  obtain ⟨k₀, hk₀⟩ := hs.nonempty
  refine ⟨fun T hT hT' => center_eq_scalar L ω β hT hT', ?_,
    spectrum_towerResolvent_eq_Icc L ω β hD hβ hs ht hirr⟩
  exact ⟨{k₀}, _, _, QIQTH.NonTracial.towerModularOp_ne_id L ω β ({k₀} : Finset M)
    (fun k => ⟨1, hone k.val⟩) (fun k => ⟨0, L.hD k.val⟩)
    (gibbsWeight_singleton_ne L ω β hone hβ hk₀ hs0)⟩

/-! ### The hypothesis-free √2 instance (the vacuity guard) -/

/-- Qubit link dimensions: every link carries a 2-dimensional fiber. -/
def qubitLinkDims : LinkDims ℕ :=
  ⟨fun _ => 2, fun _ => two_pos⟩

/-- The alternating frequency list `1, √2, 1, √2, …` — irrational ratio, both frequencies
    on infinitely many modes. -/
noncomputable def altSqrtTwoFreq : ℕ → ℝ :=
  fun k => if k % 2 = 0 then 1 else Real.sqrt 2

/-- **★★ THE √2 INSTANCE — the III₁ signature, hypothesis-free**: the alternating-qubit
    tower at `β = 1` with frequencies `{1, √2}` satisfies the full operator-level III₁
    signature — factor ∧ Δ ≠ 1 ∧ full modular spectrum — with every model hypothesis
    discharged (`irrational_sqrt_two`; the parities give both frequency classes
    infinitely often). The vacuity guard for `operator_level_III1_signature`. -/
theorem operator_level_III1_signature_sqrtTwo :
    (∀ T ∈ towerLimitVN qubitLinkDims altSqrtTwoFreq 1,
        T ∈ (towerLimitVN qubitLinkDims altSqrtTwoFreq 1).commutant →
        ∃ lam : ℂ, T = lam • (1 : TowerGNS qubitLinkDims altSqrtTwoFreq 1
          →L[ℂ] TowerGNS qubitLinkDims altSqrtTwoFreq 1))
    ∧ (∃ (C : Finset ℕ) (n m : Micro qubitLinkDims C),
        towerModularOp qubitLinkDims altSqrtTwoFreq 1
            ⟨((towerOf qubitLinkDims altSqrtTwoFreq 1 C (Matrix.single n m 1)
                : TowerPre qubitLinkDims altSqrtTwoFreq 1)
                : TowerGNS qubitLinkDims altSqrtTwoFreq 1),
              of_mem_towerModularDom qubitLinkDims altSqrtTwoFreq 1 C
                (Matrix.single n m 1)⟩
          ≠ ((towerOf qubitLinkDims altSqrtTwoFreq 1 C (Matrix.single n m 1)
              : TowerPre qubitLinkDims altSqrtTwoFreq 1)
              : TowerGNS qubitLinkDims altSqrtTwoFreq 1))
    ∧ spectrum ℝ (towerResolvent qubitLinkDims altSqrtTwoFreq 1)
        = Set.Icc (0 : ℝ) 1 := by
  refine operator_level_III1_signature qubitLinkDims altSqrtTwoFreq 1
    (fun k => le_rfl) one_ne_zero (s := Real.sqrt 2) (t := 1) ?_ ?_ ?_
  · refine Set.infinite_of_injective_forall_mem
      (f := fun n : ℕ => 2 * n + 1) (fun a b h => by dsimp only at h; omega) fun n => ?_
    show altSqrtTwoFreq (2 * n + 1) = Real.sqrt 2
    have h : (2 * n + 1) % 2 = 1 := by omega
    simp [altSqrtTwoFreq, h]
  · refine Set.infinite_of_injective_forall_mem
      (f := fun n : ℕ => 2 * n) (fun a b h => by dsimp only at h; omega) fun n => ?_
    show altSqrtTwoFreq (2 * n) = 1
    have h : (2 * n) % 2 = 0 := by omega
    simp [altSqrtTwoFreq, h]
  · rw [div_one]
    exact irrational_sqrt_two

end QIQTH.TowerGNS
