import QIQTH.Spectral.MultiplicationOp
import QIQTH.Spectral.TranslationFlow
import Mathlib.MeasureTheory.Measure.Lebesgue.Basic
import Mathlib.MeasureTheory.Integral.DominatedConvergence
import Mathlib.Analysis.SpecialFunctions.Complex.Circle

/-!
# The modulation operator `e^{isX}` on `L²(ℝ)`

The **modulation operator** `M_s = e^{isX}`, `(M_s f)(x) = e^{isx} f(x)`, is multiplication by the unimodular
symbol `e^{isx}`. Because `|e^{isx}| = 1`, `M_s` is a **unitary** (`norm_mulOp_of_norm_one`), and the symbols
multiply additively (`e^{isx} e^{is'x} = e^{i(s+s')x}`), giving the one-parameter group law `M_s ∘ M_{s'} =
M_{s+s'}`. This is the **position-side one-parameter unitary group**, generated by the position operator `X`
(`M_s = e^{isX}`) — the Fourier-dual of the translation group `e^{itP}` (`TranslationFlow.lean`). Together they
are the canonical pair behind the Weyl CCR. Axiom-free.

**Honest scope:** the generator (`X = ∫ x dE`, Stone) and the Weyl commutation relation
`e^{itP} e^{isX} = e^{ist} e^{isX} e^{itP}` are the recorded next targets; the GR chain stays gated on the
physical wedge inputs `#1/#3/#4` + the `1/4` UV datum.
-/

namespace QIQTH.Spectral.Multiplication

open MeasureTheory

/-- The modulation symbol `e^{i s x}` (unimodular). -/
noncomputable def modSymbol (s : ℝ) : ℝ → ℂ := fun x => Complex.exp (↑(s * x) * Complex.I)

theorem modSymbol_measurable (s : ℝ) : Measurable (modSymbol s) := by
  unfold modSymbol; fun_prop

theorem norm_modSymbol (s x : ℝ) : ‖modSymbol s x‖ = 1 :=
  Complex.norm_exp_ofReal_mul_I (s * x)

theorem modSymbol_le_one (s x : ℝ) : ‖modSymbol s x‖ ≤ 1 := (norm_modSymbol s x).le

/-- The **modulation operator** `e^{isX} = M_{e^{isx}}` on `L²(ℝ)`: a unitary (`|e^{isx}| = 1`). -/
noncomputable def modulationLp (s : ℝ) :
    Lp ℂ 2 (volume : Measure ℝ) →L[ℂ] Lp ℂ 2 (volume : Measure ℝ) :=
  mulOp (modSymbol_measurable s) zero_le_one (modSymbol_le_one s)

/-- The modulation operator is unitary: `‖e^{isX} f‖ = ‖f‖`. -/
@[simp] theorem norm_modulationLp (s : ℝ) (f : Lp ℂ 2 (volume : Measure ℝ)) :
    ‖modulationLp s f‖ = ‖f‖ :=
  norm_mulOp_of_norm_one (modSymbol_measurable s) zero_le_one (modSymbol_le_one s) (norm_modSymbol s) f

/-- The pointwise action: `(e^{isX} f)(x) = e^{isx} f(x)` a.e. -/
theorem coeFn_modulationLp (s : ℝ) (f : Lp ℂ 2 (volume : Measure ℝ)) :
    modulationLp s f =ᵐ[volume] fun x => modSymbol s x * f x :=
  mulOp_coeFn (modSymbol_measurable s) zero_le_one (modSymbol_le_one s) f

/-- **The one-parameter group law** `e^{isX} ∘ e^{is'X} = e^{i(s+s')X}`: the modulation symbols multiply
    additively, `e^{isx} e^{is'x} = e^{i(s+s')x}`. With unitarity this makes `s ↦ e^{isX}` a one-parameter
    group of unitaries (generated by the position operator `X`). -/
theorem modulationLp_add (s s' : ℝ) :
    modulationLp s ∘L modulationLp s' = modulationLp (s + s') := by
  rw [modulationLp, modulationLp,
    mulOp_mul (modSymbol_measurable s) zero_le_one (modSymbol_le_one s)
      (modSymbol_measurable s') zero_le_one (modSymbol_le_one s')]
  exact mulOp_congr _ _ _ (modSymbol_measurable (s + s')) zero_le_one (modSymbol_le_one (s + s'))
    (funext fun x => by
      simp only [modSymbol]
      rw [← Complex.exp_add]
      congr 1
      push_cast
      ring)

/-- Shift identity for the modulation symbol: `e^{is(x+t)} = e^{ist} · e^{isx}`. -/
theorem modSymbol_add_right (s x t : ℝ) :
    modSymbol s (x + t) = Complex.exp (↑(s * t) * Complex.I) * modSymbol s x := by
  simp only [modSymbol]
  rw [← Complex.exp_add]
  congr 1
  push_cast
  ring

/-- **The Weyl canonical commutation relation** (integrated Heisenberg relation):
    `e^{itP} e^{isX} = e^{ist} · e^{isX} e^{itP}`, here as `τ_t (e^{isX} f) = e^{ist} • (e^{isX} (τ_t f))`. The
    translation group `e^{itP}` and the modulation group `e^{isX}` fail to commute by exactly the phase `e^{ist}`
    — the integrated form of `[X, P] = i`. Proof: both sides act a.e. as `e^{is(x+t)} f(x+t)`, up to the phase
    `e^{ist}` peeled off via `modSymbol_add_right`. -/
theorem weyl_relation (s t : ℝ) (f : Lp ℂ 2 (volume : Measure ℝ)) :
    translationLp t (modulationLp s f)
      = Complex.exp (↑(s * t) * Complex.I) • modulationLp s (translationLp t f) := by
  refine Lp.ext ?_
  have hqm := (measurePreserving_add_right (volume : Measure ℝ) t).quasiMeasurePreserving
  have h2 : (fun x => (modulationLp s f : ℝ → ℂ) (x + t))
      =ᵐ[volume] fun x => modSymbol s (x + t) * (f : ℝ → ℂ) (x + t) :=
    hqm.tendsto_ae.eventually (coeFn_modulationLp s f)
  filter_upwards [coeFn_translationLp t (modulationLp s f), h2,
    Lp.coeFn_smul (Complex.exp (↑(s * t) * Complex.I)) (modulationLp s (translationLp t f)),
    coeFn_modulationLp s (translationLp t f), coeFn_translationLp t f]
    with x h_out h_mid h_smul h_mod h_tf
  rw [h_out, h_mid, h_smul]
  simp only [Pi.smul_apply, smul_eq_mul]
  rw [h_mod, h_tf, modSymbol_add_right]
  ring

/-- The modulation at `s = 0` is the identity: `e^{i0X} = 1` (`e^{i0x} = 1`). -/
@[simp] theorem modulationLp_zero : modulationLp 0 = 1 := by
  have hsymm : modSymbol 0 = fun _ : ℝ => (1 : ℂ) := by funext x; simp [modSymbol]
  rw [modulationLp, mulOp_congr (modSymbol_measurable 0) zero_le_one (modSymbol_le_one 0)
      measurable_const (norm_nonneg (1 : ℂ)) (fun _ => le_rfl) hsymm, mulOp_const, one_smul]

/-- `e^{-isX} ∘ e^{isX} = 1` — `e^{isX}` is invertible with inverse `e^{-isX}` (the group law at `(-s) + s = 0`). -/
@[simp] theorem modulationLp_neg_comp (s : ℝ) : modulationLp (-s) ∘L modulationLp s = 1 := by
  rw [modulationLp_add, neg_add_cancel, modulationLp_zero]

/-- `e^{isX} ∘ e^{-isX} = 1`. -/
@[simp] theorem modulationLp_comp_neg (s : ℝ) : modulationLp s ∘L modulationLp (-s) = 1 := by
  rw [modulationLp_add, add_neg_cancel, modulationLp_zero]

open Topology in
/-- **Strong continuity of the modulation group:** `s ↦ e^{isX} f` is continuous `ℝ → L²(ℝ)` for every state
    `f`. With the group law + unitarity this makes `s ↦ e^{isX}` a strongly-continuous one-parameter unitary
    group (the `C₀`-group whose generator is the position operator `X`), symmetric to the translation group
    `e^{itP}`. Proof: `‖e^{isX}f − e^{is₀X}f‖² = ∫ |e^{isx}−e^{is₀x}|²|f(x)|²` (`mulOp_sub` + `norm_mulOp_sq`),
    which → 0 by dominated convergence (integrand → 0 pointwise as `s → s₀`, dominated by `4|f|²`). -/
theorem continuous_modulationLp (f : Lp ℂ 2 (volume : Measure ℝ)) :
    Continuous (fun s => modulationLp s f) := by
  rw [continuous_iff_continuousAt]
  intro s₀
  rw [ContinuousAt, tendsto_iff_norm_sub_tendsto_zero]
  -- the squared norm of the difference
  have hGsq : ∀ s, ‖modulationLp s f - modulationLp s₀ f‖ ^ 2
      = ∫ x, ‖modSymbol s x - modSymbol s₀ x‖ ^ 2 * ‖f x‖ ^ 2 ∂(volume : Measure ℝ) := by
    intro s
    rw [← ContinuousLinearMap.sub_apply,
      show modulationLp s - modulationLp s₀
          = mulOp ((modSymbol_measurable s).sub (modSymbol_measurable s₀))
              (add_nonneg zero_le_one zero_le_one)
              (fun x => (norm_sub_le _ _).trans (add_le_add (modSymbol_le_one s x) (modSymbol_le_one s₀ x)))
        from mulOp_sub (modSymbol_measurable s) zero_le_one (modSymbol_le_one s)
            (modSymbol_measurable s₀) zero_le_one (modSymbol_le_one s₀),
      norm_mulOp_sq]
  -- dominated convergence: the integral → 0
  have hbound_int : Integrable (fun x => 4 * ‖f x‖ ^ 2) (volume : Measure ℝ) :=
    (((MeasureTheory.memLp_two_iff_integrable_sq_norm (Lp.aestronglyMeasurable f)).mp
      (Lp.memLp f))).const_mul 4
  have hmeas_int : ∀ s, AEStronglyMeasurable
      (fun x => ‖modSymbol s x - modSymbol s₀ x‖ ^ 2 * ‖f x‖ ^ 2) (volume : Measure ℝ) := fun s =>
    (((modSymbol_measurable s).sub (modSymbol_measurable s₀)).norm.pow_const 2).aestronglyMeasurable.mul
      (((MeasureTheory.memLp_two_iff_integrable_sq_norm (Lp.aestronglyMeasurable f)).mp
        (Lp.memLp f)).aestronglyMeasurable)
  have hDCT : Filter.Tendsto
      (fun s => ∫ x, ‖modSymbol s x - modSymbol s₀ x‖ ^ 2 * ‖f x‖ ^ 2 ∂(volume : Measure ℝ))
      (𝓝 s₀) (𝓝 0) := by
    have key := MeasureTheory.tendsto_integral_filter_of_dominated_convergence
      (fun x => 4 * ‖f x‖ ^ 2)
      (Filter.Eventually.of_forall hmeas_int)
      (Filter.Eventually.of_forall fun s => Filter.Eventually.of_forall fun x => by
        rw [Real.norm_of_nonneg (mul_nonneg (sq_nonneg _) (sq_nonneg _))]
        have hle : ‖modSymbol s x - modSymbol s₀ x‖ ≤ 2 :=
          (norm_sub_le _ _).trans (by rw [norm_modSymbol, norm_modSymbol]; norm_num)
        have h4 : ‖modSymbol s x - modSymbol s₀ x‖ ^ 2 ≤ 4 := by
          nlinarith [norm_nonneg (modSymbol s x - modSymbol s₀ x), hle]
        exact mul_le_mul_of_nonneg_right h4 (sq_nonneg ‖f x‖))
      hbound_int
      (Filter.Eventually.of_forall fun x => by
        have h1 : Filter.Tendsto (fun s => modSymbol s x) (𝓝 s₀) (𝓝 (modSymbol s₀ x)) :=
          (by unfold modSymbol; fun_prop : Continuous fun s => modSymbol s x).continuousAt
        have hconst : Filter.Tendsto (fun _ : ℝ => modSymbol s₀ x) (𝓝 s₀) (𝓝 (modSymbol s₀ x)) :=
          tendsto_const_nhds
        have hsub : Filter.Tendsto (fun s => modSymbol s x - modSymbol s₀ x) (𝓝 s₀) (𝓝 0) := by
          simpa using h1.sub hconst
        have := ((hsub.norm).pow 2).mul_const (‖f x‖ ^ 2)
        simpa using this)
    simpa using key
  -- ‖·‖² → 0 ⟹ ‖·‖ → 0
  have hsq_tendsto : Filter.Tendsto (fun s => ‖modulationLp s f - modulationLp s₀ f‖ ^ 2) (𝓝 s₀) (𝓝 0) := by
    simp_rw [hGsq]; exact hDCT
  have heq : (fun s => ‖modulationLp s f - modulationLp s₀ f‖)
      = fun s => Real.sqrt (‖modulationLp s f - modulationLp s₀ f‖ ^ 2) := by
    funext s; rw [Real.sqrt_sq (norm_nonneg _)]
  rw [heq]
  have hsqrt := (Real.continuous_sqrt.tendsto 0).comp hsq_tendsto
  rw [Real.sqrt_zero] at hsqrt
  exact hsqrt

/-- **The modulation operator as a unitary `≃ₗᵢ`** (one-parameter *group* of unitaries): `e^{isX}` is invertible
    with inverse `e^{-isX}` (from `e^{∓isX} ∘ e^{±isX} = 1`). This packages modulation as a genuine unitary on
    `L²(ℝ)` — the form conjugation/modular machinery consumes (e.g. `momentumPVM.conj (modulationUnitary s)`). -/
noncomputable def modulationUnitary (s : ℝ) :
    Lp ℂ 2 (volume : Measure ℝ) ≃ₗᵢ[ℂ] Lp ℂ 2 (volume : Measure ℝ) where
  toFun := modulationLp s
  invFun := modulationLp (-s)
  left_inv := fun f => by
    rw [← ContinuousLinearMap.comp_apply, modulationLp_neg_comp, ContinuousLinearMap.one_apply]
  right_inv := fun f => by
    rw [← ContinuousLinearMap.comp_apply, modulationLp_comp_neg, ContinuousLinearMap.one_apply]
  map_add' := (modulationLp s).map_add
  map_smul' := (modulationLp s).map_smul
  norm_map' := norm_modulationLp s

@[simp] theorem modulationUnitary_apply (s : ℝ) (f : Lp ℂ 2 (volume : Measure ℝ)) :
    modulationUnitary s f = modulationLp s f := rfl

@[simp] theorem modulationUnitary_symm_apply (s : ℝ) (f : Lp ℂ 2 (volume : Measure ℝ)) :
    (modulationUnitary s).symm f = modulationLp (-s) f := rfl

end QIQTH.Spectral.Multiplication
