import QIQTH.Spectral.MultiplicationOp
import QIQTH.Spectral.TranslationFlow
import Mathlib.MeasureTheory.Measure.Lebesgue.Basic
import Mathlib.Analysis.SpecialFunctions.Complex.Circle

/-!
# The modulation operator `e^{isX}` on `L²(ℝ)`

The **modulation operator** `M_s = e^{isX}`, `(M_s f)(x) = e^{isx} f(x)`, is multiplication by the unimodular
symbol `e^{isx}`. Because `|e^{isx}| = 1`, `M_s` is a **unitary** (`norm_mulOp_of_norm_one`), and the symbols
multiply additively (`e^{isx} e^{is'x} = e^{i(s+s')x}`), giving the one-parameter group law `M_s ∘ M_{s'} =
M_{s+s'}`. This is the **position-side one-parameter unitary group**, generated by the position operator `X`
(`M_s = e^{isX}`) — the Fourier-dual of the translation group `e^{itP}` (`TranslationFlow.lean`). Together they
are the canonical pair behind the Weyl CCR. Axiom-free.

**Honest scope:** the generator (`X = ∫ x dE`, Stone) and the Weyl commutation relation
`e^{itP} e^{isX} = e^{ist} e^{isX} e^{itP}` are the recorded next targets; the GR chain stays gated on the
physical wedge inputs `#1/#3/#4` + the `1/4` UV datum.
-/

namespace QIQTH.Spectral.Multiplication

open MeasureTheory

/-- The modulation symbol `e^{i s x}` (unimodular). -/
noncomputable def modSymbol (s : ℝ) : ℝ → ℂ := fun x => Complex.exp (↑(s * x) * Complex.I)

theorem modSymbol_measurable (s : ℝ) : Measurable (modSymbol s) := by
  unfold modSymbol; fun_prop

theorem norm_modSymbol (s x : ℝ) : ‖modSymbol s x‖ = 1 :=
  Complex.norm_exp_ofReal_mul_I (s * x)

theorem modSymbol_le_one (s x : ℝ) : ‖modSymbol s x‖ ≤ 1 := (norm_modSymbol s x).le

/-- The **modulation operator** `e^{isX} = M_{e^{isx}}` on `L²(ℝ)`: a unitary (`|e^{isx}| = 1`). -/
noncomputable def modulationLp (s : ℝ) :
    Lp ℂ 2 (volume : Measure ℝ) →L[ℂ] Lp ℂ 2 (volume : Measure ℝ) :=
  mulOp (modSymbol_measurable s) zero_le_one (modSymbol_le_one s)

/-- The modulation operator is unitary: `‖e^{isX} f‖ = ‖f‖`. -/
@[simp] theorem norm_modulationLp (s : ℝ) (f : Lp ℂ 2 (volume : Measure ℝ)) :
    ‖modulationLp s f‖ = ‖f‖ :=
  norm_mulOp_of_norm_one (modSymbol_measurable s) zero_le_one (modSymbol_le_one s) (norm_modSymbol s) f

/-- The pointwise action: `(e^{isX} f)(x) = e^{isx} f(x)` a.e. -/
theorem coeFn_modulationLp (s : ℝ) (f : Lp ℂ 2 (volume : Measure ℝ)) :
    modulationLp s f =ᵐ[volume] fun x => modSymbol s x * f x :=
  mulOp_coeFn (modSymbol_measurable s) zero_le_one (modSymbol_le_one s) f

/-- **The one-parameter group law** `e^{isX} ∘ e^{is'X} = e^{i(s+s')X}`: the modulation symbols multiply
    additively, `e^{isx} e^{is'x} = e^{i(s+s')x}`. With unitarity this makes `s ↦ e^{isX}` a one-parameter
    group of unitaries (generated by the position operator `X`). -/
theorem modulationLp_add (s s' : ℝ) :
    modulationLp s ∘L modulationLp s' = modulationLp (s + s') := by
  rw [modulationLp, modulationLp,
    mulOp_mul (modSymbol_measurable s) zero_le_one (modSymbol_le_one s)
      (modSymbol_measurable s') zero_le_one (modSymbol_le_one s')]
  exact mulOp_congr _ _ _ (modSymbol_measurable (s + s')) zero_le_one (modSymbol_le_one (s + s'))
    (funext fun x => by
      simp only [modSymbol]
      rw [← Complex.exp_add]
      congr 1
      push_cast
      ring)

/-- Shift identity for the modulation symbol: `e^{is(x+t)} = e^{ist} · e^{isx}`. -/
theorem modSymbol_add_right (s x t : ℝ) :
    modSymbol s (x + t) = Complex.exp (↑(s * t) * Complex.I) * modSymbol s x := by
  simp only [modSymbol]
  rw [← Complex.exp_add]
  congr 1
  push_cast
  ring

/-- **The Weyl canonical commutation relation** (integrated Heisenberg relation):
    `e^{itP} e^{isX} = e^{ist} · e^{isX} e^{itP}`, here as `τ_t (e^{isX} f) = e^{ist} • (e^{isX} (τ_t f))`. The
    translation group `e^{itP}` and the modulation group `e^{isX}` fail to commute by exactly the phase `e^{ist}`
    — the integrated form of `[X, P] = i`. Proof: both sides act a.e. as `e^{is(x+t)} f(x+t)`, up to the phase
    `e^{ist}` peeled off via `modSymbol_add_right`. -/
theorem weyl_relation (s t : ℝ) (f : Lp ℂ 2 (volume : Measure ℝ)) :
    translationLp t (modulationLp s f)
      = Complex.exp (↑(s * t) * Complex.I) • modulationLp s (translationLp t f) := by
  refine Lp.ext ?_
  have hqm := (measurePreserving_add_right (volume : Measure ℝ) t).quasiMeasurePreserving
  have h2 : (fun x => (modulationLp s f : ℝ → ℂ) (x + t))
      =ᵐ[volume] fun x => modSymbol s (x + t) * (f : ℝ → ℂ) (x + t) :=
    hqm.tendsto_ae.eventually (coeFn_modulationLp s f)
  filter_upwards [coeFn_translationLp t (modulationLp s f), h2,
    Lp.coeFn_smul (Complex.exp (↑(s * t) * Complex.I)) (modulationLp s (translationLp t f)),
    coeFn_modulationLp s (translationLp t f), coeFn_translationLp t f]
    with x h_out h_mid h_smul h_mod h_tf
  rw [h_out, h_mid, h_smul]
  simp only [Pi.smul_apply, smul_eq_mul]
  rw [h_mod, h_tf, modSymbol_add_right]
  ring

/-- The modulation at `s = 0` is the identity: `e^{i0X} = 1` (`e^{i0x} = 1`). -/
@[simp] theorem modulationLp_zero : modulationLp 0 = 1 := by
  have hsymm : modSymbol 0 = fun _ : ℝ => (1 : ℂ) := by funext x; simp [modSymbol]
  rw [modulationLp, mulOp_congr (modSymbol_measurable 0) zero_le_one (modSymbol_le_one 0)
      measurable_const (norm_nonneg (1 : ℂ)) (fun _ => le_rfl) hsymm, mulOp_const, one_smul]

/-- `e^{-isX} ∘ e^{isX} = 1` — `e^{isX}` is invertible with inverse `e^{-isX}` (the group law at `(-s) + s = 0`). -/
@[simp] theorem modulationLp_neg_comp (s : ℝ) : modulationLp (-s) ∘L modulationLp s = 1 := by
  rw [modulationLp_add, neg_add_cancel, modulationLp_zero]

/-- `e^{isX} ∘ e^{-isX} = 1`. -/
@[simp] theorem modulationLp_comp_neg (s : ℝ) : modulationLp s ∘L modulationLp (-s) = 1 := by
  rw [modulationLp_add, add_neg_cancel, modulationLp_zero]

end QIQTH.Spectral.Multiplication
