#!/usr/bin/env bash
# Build the QIQT-H blueprint (web + pdf) and verify Lean declarations.
#
# Why this script instead of the `leanblueprint` CLI?
# The `leanblueprint` command locates the lakefile at the *git root*
# (it calls `git rev-parse`), but this Lean project lives in a subdirectory
# (lean/mathlib) of the QIQT-H git repo. So the CLI's pdf/web/checkdecls
# wrappers don't find the project. This script calls the underlying tools
# (plastex, latexmk, lake) directly with the right working directory and PATH.
#
# Prerequisites (already installed in this environment):
#   * plastex + leanblueprint plugins  -> miniconda env "ai" Scripts dir
#   * Graphviz (for the dependency graph) -> portable build, see GV below
#   * MiKTeX (xelatex + latexmk)        -> for the pdf
#   * elan/lake                          -> for checkdecls
#
# Usage:  bash scripts/build_blueprint.sh [target]   (default: all)
#   Concise edition:  web | pdf
#   Expanded edition: web-expanded | pdf-expanded | expanded (both)
#   Verify decls:     check
#   all  = concise web + pdf + check
#   full = concise + expanded + check

set -euo pipefail

# --- locate this Lean project (the dir containing lakefile.lean) ---
MATHLIB_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SRC="$MATHLIB_DIR/blueprint/src"

# --- tool locations (edit here if your install paths differ) ---
GV_BIN="/c/Users/Pawel/graphviz-portable/Graphviz-12.2.1-win64/bin"
CONDA_SCRIPTS="/c/Users/Pawel/miniconda3/envs/ai/Scripts"
MIKTEX_BIN="/c/Program Files/MiKTeX/miktex/bin/x64"

export PATH="$GV_BIN:$CONDA_SCRIPTS:$MIKTEX_BIN:$PATH"

target="${1:-all}"

build_web() {
  echo ">>> Building web version (plastex + dependency graph)..."
  mkdir -p "$MATHLIB_DIR/blueprint/web"
  ( cd "$SRC" && plastex -c plastex.cfg web.tex )
  echo ">>> Web output: $MATHLIB_DIR/blueprint/web/index.html"
  echo ">>> Dep graph:  $MATHLIB_DIR/blueprint/web/dep_graph_document.html"
}

build_pdf() {
  echo ">>> Building pdf version (xelatex via latexmk)..."
  mkdir -p "$MATHLIB_DIR/blueprint/print"
  ( cd "$SRC" && latexmk -output-directory=../print )
  echo ">>> PDF output: $MATHLIB_DIR/blueprint/print/print.pdf"
}

build_web_expanded() {
  echo ">>> Building EXPANDED web version (plastex + dependency graph)..."
  mkdir -p "$MATHLIB_DIR/blueprint/web-expanded"
  ( cd "$SRC" && plastex -c plastex-expanded.cfg web-expanded.tex )
  echo ">>> Expanded web: $MATHLIB_DIR/blueprint/web-expanded/index.html"
}

build_pdf_expanded() {
  echo ">>> Building EXPANDED pdf version (xelatex via latexmk)..."
  mkdir -p "$MATHLIB_DIR/blueprint/print-expanded"
  ( cd "$SRC" && latexmk -output-directory=../print-expanded print-expanded.tex )
  echo ">>> Expanded PDF: $MATHLIB_DIR/blueprint/print-expanded/print-expanded.pdf"
}

check_decls() {
  # blueprint/lean_decls is regenerated by the web build; build web first.
  echo ">>> Checking that every \\lean{...} reference exists in Lean..."
  ( cd "$MATHLIB_DIR" && lake exe checkdecls blueprint/lean_decls )
  echo ">>> All blueprint declarations resolved."
}

case "$target" in
  web)          build_web ;;
  pdf)          build_pdf ;;
  web-expanded) build_web_expanded ;;
  pdf-expanded) build_pdf_expanded ;;
  expanded)     build_web_expanded; build_pdf_expanded ;;
  check)        check_decls ;;
  all)          build_web; build_pdf; check_decls ;;
  full)         build_web; build_pdf; build_web_expanded; build_pdf_expanded; check_decls ;;
  *) echo "Unknown target '$target' (use web|pdf|web-expanded|pdf-expanded|expanded|check|all|full)"; exit 1 ;;
esac

echo ">>> Done."
