#!/usr/bin/env python3
"""Stage 3 (axiom / soundness audit) + claim-card generation for the verify capsule.

Runs the combined Lean probe over each capstone in config.json, then:
  • asserts the COMPLETE transitive axiom set is a subset of the standard three
    (propext, Classical.choice, Quot.sound) and contains no forbidden axiom
    (sorryAx, Lean.ofReduceBool, …)  — fail-closed, non-zero exit on any violation;
  • emits verify/out/axioms.json (the raw kernel facts) and verify/out/claim_card.md
    (formal statement, complete trusted base, and the hypothesis ledger).

Assumes the project is already built (verify.sh Stage 1). Run from the repo root or
anywhere; paths are resolved relative to this file.
"""
import json
import pathlib
import sys

HERE = pathlib.Path(__file__).resolve().parent
REPO = HERE.parent
sys.path.insert(0, str(REPO / "scripts"))
from lean_track import latex_tree, latexify, probe  # noqa: E402

CFG = json.loads((HERE / "config.json").read_text(encoding="utf-8"))
OUT = HERE / "out"
STD = set(CFG["standard_axioms"])
FORBIDDEN = set(CFG.get("forbidden_axioms", []))
NOTES = CFG.get("input_notes", {})


def _note(name):
    """Annotation for a hypothesis binder: exact name, else longest-prefix match."""
    if name in NOTES:
        return NOTES[name]
    best = None
    for k, v in NOTES.items():
        if name.startswith(k) and (best is None or len(k) > len(best[0])):
            best = (k, v)
    return best[1] if best else None


def _hygienic(name):
    return ("._@." in name) or ("_hyg" in name) or name.startswith("inst") or name == "[anonymous]"


def _notation():
    cfg = probe.load_config(REPO / "tracks" / "gr.toml")
    note = (cfg.get("latex", {}) or {}).get("notation", {})
    return {**latexify.DEFAULT_NOTATION, **note}


def _render_concl(concl, notation):
    try:
        parts = latex_tree._conjuncts(concl)
        return [latex_tree.tex_of_tree(p, notation) for p in parts]
    except Exception as e:  # never let rendering crash the audit verdict
        return [r"\text{(statement rendered in the Lean source — render error: %s)}" % e]


def _render_type(tree, notation):
    try:
        return latex_tree.tex_of_tree(tree, notation)
    except Exception:
        return r"\text{(see source)}"


def main():
    OUT.mkdir(exist_ok=True)
    latex_tree._LINKS = {}                         # standalone card: no cross-page links
    notation = _notation()
    caps = [c["name"] for c in CFG["capstones"]]
    by_cfg = {c["name"]: c for c in CFG["capstones"]}

    records = probe._run_probe(HERE / "probe_verify.lean.tmpl", caps, "QIQTH", 1800, "vf")
    by_name = {r["name"]: r for r in records}
    (OUT / "axioms.json").write_text(
        json.dumps([{"name": r["name"], "present": r.get("present"),
                     "axioms": r.get("axioms", [])} for r in records],
                   ensure_ascii=False, indent=2), encoding="utf-8")

    rev = probe.git_rev()
    violations, card = [], []
    card.append(f"# Verification claim card\n")
    card.append(f"<small>QIQT-H · commit `{rev}` · Lean `{(REPO/'lean'/'mathlib'/'lean-toolchain').read_text(encoding='utf-8').strip()}` · "
                f"generated by `verify/audit.py`</small>\n")
    card.append("> **What this card is.** A machine-extracted certificate that, in *the build on "
                "this machine*, the Lean kernel accepted each statement below depending only on the "
                "standard axioms, together with the complete list of hypotheses it still assumes. "
                "It certifies a *conditional mathematical entailment*, not a physical truth.\n")

    for cap in caps:
        c = by_cfg[cap]
        r = by_name.get(cap, {})
        present = r.get("present", False)
        axs = r.get("axioms", [])
        extra = sorted(a for a in axs if a not in STD)
        forbidden_hit = sorted(a for a in axs if a in FORBIDDEN)
        if not present:
            violations.append(f"{cap}: NOT FOUND in the built environment")
        if forbidden_hit:
            violations.append(f"{cap}: depends on forbidden axiom(s) {forbidden_hit}")
        if extra:
            violations.append(f"{cap}: non-standard axiom(s) {extra}")

        short = cap.split(".")[-1]
        card.append(f"\n## `{short}`\n")
        card.append(f"<small>`{cap}`</small>\n")

        if not present:
            card.append("❌ **NOT FOUND** in the built environment — cannot certify.\n")
            continue
        ok = not extra and not forbidden_hit
        if ok:
            card.append("✅ **Kernel-accepted, axiom-free** — the complete transitive trust base is "
                        "exactly the three standard Lean/Mathlib axioms.\n")
        else:
            card.append("❌ **Audit failed** — trust base exceeds the standard axioms "
                        f"(extra: {extra or '—'}; forbidden: {forbidden_hit or '—'}).\n")

        card.append(f"**Claim (informal).** {c['claim']}\n")
        card.append("**Formal statement (machine-rendered from the Lean source).**\n")
        for k, p in enumerate(_render_concl(r.get("concl"), notation), 1):
            tag = rf"\text{{({k})}}\quad " if k > 1 or False else ""
            card.append(f"$$ {tag}{p} $$\n")
        card.append("**Complete transitive trusted base.** " +
                    ", ".join(f"`{a}`" for a in sorted(axs)) + ".\n")

        # ---- hypothesis ledger -------------------------------------------------
        binders = r.get("binders", [])
        data = [b for b in binders if b["kind"] == "data" and not _hygienic(b["name"])]
        inst = [b for b in binders if b["kind"] == "instance"]
        props = [b for b in binders if b["kind"] == "prop" and not _hygienic(b["name"])]
        physical, routine = [], []
        for b in props:
            note = _note(b["name"])
            if note and note.get("role") == "physical-input":
                physical.append((b, note))
            else:
                routine.append((b, note))

        card.append("### Hypothesis ledger — the complete set of remaining assumptions\n")
        card.append("The statement is conditional on **exactly** these binders (free variables are "
                    "implicitly universally quantified). Nothing is hidden: every assumption the "
                    "kernel relied on is a binder here.\n")
        if physical:
            card.append("**Load-bearing physical inputs — the honest residue** "
                        "(these are *assumed*, not derived):\n")
            for b, note in physical:
                card.append(f"- **`{b['name']}`** — {note['desc']}  \n"
                            f"  $ {_render_type(b['type'], notation)} $")
            card.append("")
        else:
            card.append("_No binder is tagged as a load-bearing physical input in this build's "
                        "config — review the routine list below to confirm._\n")
        card.append(f"**Objects (data):** {len(data)}"
                    + (f" — {', '.join('`'+b['name']+'`' for b in data[:12])}"
                       + (" …" if len(data) > 12 else "") if data else "") + "  ")
        card.append(f"**Typeclass instances:** {len(inst)}  ")
        if routine:
            names = ", ".join(f"`{b['name']}`" for b, _ in routine[:20])
            more = " …" if len(routine) > 20 else ""
            card.append(f"**Routine (regularity / setup):** {len(routine)} — {names}{more}\n")
        else:
            card.append("**Routine (regularity / setup):** 0\n")

        card.append("### Scope — what this does and does not establish\n")
        card.append(c.get("scope", "") + "\n")

    # ---- overall verdict ------------------------------------------------------
    card.insert(2, ("\n## Overall verdict\n\n"
                    + ("✅ **PASS** — every capstone is kernel-accepted and axiom-free; "
                       "no forbidden axioms; the hypothesis ledger below is the complete "
                       "assumption surface.\n"
                       if not violations else
                       "❌ **FAIL**\n\n" + "\n".join(f"- {v}" for v in violations) + "\n")))

    (OUT / "claim_card.md").write_text("\n".join(card), encoding="utf-8")

    print(f"[audit] capstones: {len(caps)}  ->  {OUT/'claim_card.md'}")
    if violations:
        print("[audit] VIOLATIONS:")
        for v in violations:
            print("   -", v)
        return 1
    print("[audit] PASS — all capstones kernel-accepted and axiom-free.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
