/-
  BRIDGE C2b — the conditional CHM transport: the Clausius datum at EVERY ball.

  ★ SCOPE (BRIDGE_PLAN.md, GPT-5.5-pro-verified). C1 forced the Clausius datum for ONE wedge (given the carried BW
    identification); the FGHMVR skeleton (G1) needs the first-law datum `δ⟨K_B⟩` at EVERY ball of a probe family.
    The CHM theorem supplies it for a CFT vacuum: each ball's modular flow is the conformal image of the wedge
    flow, generated by the diamond CKV whose kernel geometry was verified in C2a (`CHMKernel.lean` — the weight
    `β(r)=(R²−r²)/2R`, its unit surface-gravity edge slope matching the Rindler wedge, and the conformal Killing
    equation). Here that CHM statement is the CARRIED **`hCHM`** field of `BallModularFamily` — each ball's
    geometric (conformal) flow acts on the probe state as its modular flow. It is a structure hypothesis, NEVER a
    Lean axiom; it is CFT-vacuum input (`CHMCompatible`), not generic QFT, and it is NOT derived here.

  Payload (all axiom-free, std-3): GIVEN `hCHM`, every ball inherits the DERIVED modular Clausius datum by riding
  C1's `WedgeBoostPackage` theorems per ball —
  • `ball_correlator_hasDerivAt` : `d/dt⟪ξ_B, W^B_t ξ_B⟫|₀ = i·(−S_B)` at every ball `B` (`S_B` = the ball's
    modular/entanglement entropy);
  • `ball_flux_unique` : the per-ball Clausius datum is FORCED (derivative uniqueness);
  • `ballHeatFlux` : the ball-indexed first-law data `B ↦ −S_B` with `ballHeatFlux_spec` — **exactly the
    `δK : Ball → ℝ` input the assembly (ASM) feeds into G1** (`allBall_firstLaw_iff_residual_zero`).

  ⚠ Honest labels: `hCHM` carried (CFT-vacuum/conformal input); free-field/RvD standard-subspace setting; the
    Clausius/area law `δS = δA/4G` and the value of `G` remain the separate carried inputs of ASM; the area law
    from counting is ingredient D.
-/
import Mathlib
import QIQTH.WedgeBoostClausius

namespace QIQTH.BallModular

open QIQTH.StandardSubspaceModular QIQTH.SpectralTheorem QIQTH.Spectral QIQTH.WedgeBoost

variable {H : Type*} [NormedAddCommGroup H] [InnerProductSpace ℂ H] [CompleteSpace H]

/-- **The ball modular family (C2b package).** For each ball `B` of a probe family: its one-particle standard
    subspace `S B` (the conformal-image wedge data), a probe state, and its geometric conformal (CHM) flow; the
    CARRIED **`hCHM`** field is the CHM/`CHMCompatible` identification — each ball's geometric flow acts on the
    state as its modular flow (the conformal transport of Bisognano–Wichmann; CFT-vacuum input, never an axiom).
    `hdom`/`hspec` are the per-ball domain/spectral conditions of the derived modular machinery. -/
structure BallModularFamily (Ball : Type*) (H : Type*) [NormedAddCommGroup H]
    [InnerProductSpace ℂ H] [CompleteSpace H] where
  /-- the ball's one-particle standard subspace (conformal image of the wedge) -/
  S : Ball → StandardSubspace H
  /-- the probe state on each ball -/
  state : Ball → H
  /-- the geometric conformal (CHM) flow of each ball -/
  flow : Ball → ℝ → H → H
  /-- CARRIED `CHMCompatible`: each ball's geometric flow acts on the state as its modular flow -/
  hCHM : ∀ B t, flow B t (state B) = modUnitary (S B) t (state B)
  /-- finite modular energy of the probe state, per ball -/
  hdom : ∀ B, state B ∈ (PVM_of_selfAdjoint (rvdRC (S B)) (rvdRC_isSelfAdjoint (S B))).fcDomain
    (fun ω : spectrum ℝ (rvdRC (S B)) => kFn ω.val)
  /-- the separating spectral condition, per ball -/
  hspec : ∀ B, ∀ ω : spectrum ℝ (rvdRC (S B)),
    (ω : spectrum ℝ (rvdRC (S B))).val ∈ Set.Ioo (0 : ℝ) 2

variable {Ball : Type*}

/-- Each ball of the family is a C1 wedge-boost package (the conformal image rides the wedge machinery). -/
def BallModularFamily.toWedgePackage (F : BallModularFamily Ball H) (B : Ball) :
    WedgeBoostPackage (F.S B) (F.state B) where
  boost := F.flow B
  hBW := F.hCHM B

/-- **The Clausius datum at every ball:** `d/dt⟪ξ_B, W^B_t ξ_B⟫|₀ = i·(−S_B)` — each ball's geometric conformal
    flow inherits the DERIVED modular derivative, with `S_B = cgpEntropy` the ball's entanglement entropy. -/
theorem ball_correlator_hasDerivAt (F : BallModularFamily Ball H) (B : Ball) :
    HasDerivAt (fun t : ℝ => inner ℂ (F.state B) (F.flow B t (F.state B)))
      (Complex.I * ((-cgpEntropy (F.S B) (F.state B) : ℝ) : ℂ)) 0 :=
  boost_correlator_hasDerivAt (F.toWedgePackage B) (F.hdom B) (F.hspec B)

/-- **The per-ball Clausius datum is FORCED** (derivative uniqueness): any candidate flux at ball `B` equals
    `−S_B`. -/
theorem ball_flux_unique (F : BallModularFamily Ball H) (B : Ball) (c : ℝ)
    (hc : HasDerivAt (fun t : ℝ => inner ℂ (F.state B) (F.flow B t (F.state B)))
      (Complex.I * (c : ℂ)) 0) :
    c = -cgpEntropy (F.S B) (F.state B) :=
  boost_flux_unique (F.toWedgePackage B) c (F.hdom B) (F.hspec B) hc

/-- **The ball-indexed first-law data** `δ⟨K_B⟩ : Ball → ℝ`, `B ↦ −S_B` — exactly the shape the assembly (ASM)
    feeds into the FGHMVR skeleton `G1` (`allBall_firstLaw_iff_residual_zero`). -/
noncomputable def ballHeatFlux (F : BallModularFamily Ball H) (B : Ball) : ℝ :=
  -cgpEntropy (F.S B) (F.state B)

/-- The ball heat-flux data is realized by the geometric flow: at every ball, the correlator derivative is
    `i·(ballHeatFlux B)` — the first-law datum is not a label but the derived derivative of the ball's own
    conformal flow. -/
theorem ballHeatFlux_spec (F : BallModularFamily Ball H) (B : Ball) :
    HasDerivAt (fun t : ℝ => inner ℂ (F.state B) (F.flow B t (F.state B)))
      (Complex.I * ((ballHeatFlux F B : ℝ) : ℂ)) 0 :=
  ball_correlator_hasDerivAt F B

/-- The real (physical) form at every ball: `d/dt Im⟪ξ_B, W^B_t ξ_B⟫|₀ = −S_B`. -/
theorem ball_correlator_im_hasDerivAt (F : BallModularFamily Ball H) (B : Ball) :
    HasDerivAt (fun t : ℝ => (inner ℂ (F.state B) (F.flow B t (F.state B)) : ℂ).im)
      (-cgpEntropy (F.S B) (F.state B)) 0 :=
  boost_correlator_im_hasDerivAt (F.toWedgePackage B) (F.hdom B) (F.hspec B)

end QIQTH.BallModular
