/-
# QIQT-H: deriving the per-collision distinguishability `γ < 1` from a toy Hamiltonian

`SBSBridge.lean` proves the amplification chain (`overlap_amplifies`,
`block_overlap_tendsto_zero`) *conditional* on a per-collision overlap `γ < 1`.  There
`γ` was a hypothesis.  The GPT-5.5-pro review isolated this as the one open physical
input: "derive a stable, factorized, branch-dependent scattering model with uniform
per-collision distinguishability `γ < 1` from a concrete Hamiltonian."

This module discharges it for the standard collisional/QND monitoring model (Zurek):

    H_int = g · σ_z^S ⊗ A,   A a self-adjoint involution on the environment (A = σ_x^E).

Conditioned on the pointer eigenvalue `s = ±1`, the environment qubit evolves under the
Schrödinger propagator of `H_s = s·A`,

    U_s(θ) = exp(-i θ s A) = cos θ · 𝟙 - i·s·sin θ · A      (θ := g·τ, since A² = 𝟙),

which we prove is a genuine one-parameter unitary group (`collisionU_group`,
`collisionU_zero`) generated by the self-adjoint `H_s` (`hamiltonian_isSymmetric`).  The
two branch-conditioned records `|E_±⟩ = U_±(θ)|ε₀⟩` then overlap by

    ⟨E_+ | E_- ⟩ = cos²θ - sin²θ = cos 2θ        (`branch_overlap`),

so the per-collision distinguishability is `γ = |cos 2θ| < 1` for generic coupling
(`gamma_lt_one`), DERIVED — not assumed.  Over `L` independent collisions the joint
overlap factorizes to `γ^L → 0` (`collisional_block_overlap`,
`collisional_overlap_tendsto_zero`), feeding the existing `overlap_amplifies` chain.

See `GAMMA_FROM_HAMILTONIAN.md` for the physics writeup and the honest residual
(this is a toy two-level monitor; a field-theoretic derivation of uniform `γ` is open).
Axiom-free (standard three only). -/
import Mathlib.Analysis.InnerProductSpace.Basic
import Mathlib.Analysis.SpecialFunctions.Trigonometric.Basic
import QIQTH.SBSBridge
import Mathlib.Tactic

namespace QIQTH.CollisionalGamma

open scoped BigOperators
open Complex

variable {E : Type*} [NormedAddCommGroup E] [InnerProductSpace ℂ E]

/-- The environment part of the toy interaction `H_int = g σ_z^S ⊗ A`: a **self-adjoint
    involution** `A` (concretely `σ_x`).  Self-adjointness makes `H_s = s·A` an observable;
    the involution `A² = 𝟙` makes the propagator a clean `cos/sin` rotation. -/
structure ToyInteraction (E : Type*) [NormedAddCommGroup E] [InnerProductSpace ℂ E] where
  /-- the interaction direction (e.g. `σ_x`) -/
  A : E →ₗ[ℂ] E
  /-- `A` is symmetric: `⟪A x, y⟫ = ⟪x, A y⟫` (self-adjoint observable) -/
  symm : ∀ x y, inner ℂ (A x) y = inner ℂ x (A y)
  /-- `A` is an involution: `A² = 𝟙` (so `A` is also unitary) -/
  invol : ∀ x, A (A x) = x

variable (T : ToyInteraction E)

/-- **Schrödinger propagator of `H_s = s·A`**: `U_s(θ) = cos θ · 𝟙 - i·s·sin θ · A`.
    This is `exp(-i θ s A)` (valid since `A² = 𝟙`), the unitary evolution generated by the
    branch-conditioned Hamiltonian over collision time `θ = g·τ`. -/
noncomputable def collisionU (s θ : ℝ) (x : E) : E :=
  (Real.cos θ : ℂ) • x - (Complex.I * ((s * Real.sin θ : ℝ) : ℂ)) • T.A x

/-- `|E_+⟩ = U_{+1}(θ)|ε₀⟩`: the environment record conditioned on pointer outcome `s = +1`. -/
noncomputable def branchPlus (θ : ℝ) (x : E) : E := collisionU T 1 θ x

/-- `|E_-⟩ = U_{-1}(θ)|ε₀⟩`: the environment record conditioned on pointer outcome `s = -1`. -/
noncomputable def branchMinus (θ : ℝ) (x : E) : E := collisionU T (-1) θ x

/-- **`U_s(0) = 𝟙`** — no evolution in zero time (one-parameter-group identity element). -/
theorem collisionU_zero (s : ℝ) (x : E) : collisionU T s 0 x = x := by
  simp [collisionU]

/-- **One-parameter group law** `U_s(θ₁)·U_s(θ₂) = U_s(θ₁+θ₂)`.  This is the defining
    property of the Hamiltonian flow `exp(-iθ s A)` (the exponential homomorphism), proved
    from `A² = 𝟙` (`T.invol`), `s² = 1`, and the angle-addition formulas.  Together with
    `collisionU_zero` it certifies `U_s` as the propagator of a genuine Hamiltonian. -/
theorem collisionU_group (s : ℝ) (hs2 : (s : ℂ) ^ 2 = 1) (θ₁ θ₂ : ℝ) (x : E) :
    collisionU T s θ₁ (collisionU T s θ₂ x) = collisionU T s (θ₁ + θ₂) x := by
  simp only [collisionU, map_sub, map_smul, T.invol, smul_sub, smul_smul]
  match_scalars
  · rw [Complex.cos_add]
    linear_combination
      (Complex.sin (θ₁ : ℂ) * Complex.sin (θ₂ : ℂ) * (s : ℂ) ^ 2) * Complex.I_sq
        + (-(Complex.sin (θ₁ : ℂ) * Complex.sin (θ₂ : ℂ))) * hs2
  · rw [Complex.sin_add]; ring

/-- **`H_s = s·A` is self-adjoint** (`⟪H_s x, y⟫ = ⟪x, H_s y⟫`), so the branch Hamiltonian
    is a genuine observable and `U_s = exp(-iθ H_s)` is unitary by Stone's theorem. -/
theorem hamiltonian_isSymmetric (s : ℝ) (x y : E) :
    inner ℂ ((s : ℂ) • T.A x) y = inner ℂ x ((s : ℂ) • T.A y) := by
  rw [inner_smul_left, inner_smul_right, T.symm]
  simp [Complex.conj_ofReal]

/- ── orthonormal triple `{ε₀, A ε₀}` from the structure ─────────────────────── -/

/-- From symmetry + involution: `⟪A x, A x⟫ = ⟪x, x⟫` (`A` is an isometry). -/
theorem inner_A_A (x : E) : inner ℂ (T.A x) (T.A x) = inner ℂ x x := by
  rw [T.symm, T.invol]

/-- The cross term is symmetric: `⟪A x, x⟫ = ⟪x, A x⟫`. -/
theorem inner_A_left_eq (x : E) : inner ℂ (T.A x) x = inner ℂ x (T.A x) :=
  T.symm x x

/-- **Per-collision overlap of the two branch records:** `⟨E_+ | E_- ⟩ = cos²θ - sin²θ`.
    The only inputs are that `{ε₀, A ε₀}` is orthonormal — `⟪ε₀,ε₀⟫ = 1` and
    `⟪ε₀, A ε₀⟫ = 0` (the rest follows from `A` being a self-adjoint involution).  This is
    the quantity the amplification chain bounds. -/
theorem branch_overlap (θ : ℝ) (x : E)
    (hx : inner ℂ x x = (1 : ℂ)) (hortho : inner ℂ x (T.A x) = (0 : ℂ)) :
    inner ℂ (branchPlus T θ x) (branchMinus T θ x)
      = ((Real.cos θ ^ 2 - Real.sin θ ^ 2 : ℝ) : ℂ) := by
  have hAA : inner ℂ (T.A x) (T.A x) = (1 : ℂ) := by rw [inner_A_A, hx]
  have hAe : inner ℂ (T.A x) x = (0 : ℂ) := by rw [inner_A_left_eq, hortho]
  have hbp : branchPlus T θ x
      = (Real.cos θ : ℂ) • x - (Complex.I * ((Real.sin θ : ℝ) : ℂ)) • T.A x := by
    simp only [branchPlus, collisionU, one_mul]
  have hbm : branchMinus T θ x
      = (Real.cos θ : ℂ) • x + (Complex.I * ((Real.sin θ : ℝ) : ℂ)) • T.A x := by
    simp only [branchMinus, collisionU, neg_one_mul, Complex.ofReal_neg, mul_neg, neg_smul,
      sub_neg_eq_add]
  rw [hbp, hbm]
  simp only [inner_sub_left, inner_add_right, inner_smul_left, inner_smul_right, hx, hortho,
    hAA, hAe, mul_one, mul_zero, sub_zero]
  simp only [Complex.conj_ofReal, map_mul, Complex.conj_I]
  rw [Complex.ofReal_sub, Complex.ofReal_pow, Complex.ofReal_pow]
  linear_combination (((Real.sin θ : ℝ) : ℂ) ^ 2) * Complex.I_sq

/- ── γ = |cos 2θ| < 1 for generic coupling ──────────────────────────────────── -/

/-- The overlap equals `cos 2θ` (double-angle). -/
theorem branch_overlap_cos_two_mul (θ : ℝ) (x : E)
    (hx : inner ℂ x x = (1 : ℂ)) (hortho : inner ℂ x (T.A x) = (0 : ℂ)) :
    inner ℂ (branchPlus T θ x) (branchMinus T θ x) = ((Real.cos (2 * θ) : ℝ) : ℂ) := by
  rw [branch_overlap T θ x hx hortho]
  congr 1
  have h1 := Real.cos_two_mul θ
  have h2 := Real.sin_sq_add_cos_sq θ
  nlinarith [h1, h2]

/-- **`γ < 1` is DERIVED.**  For a generic coupling `0 < θ < π/4` (the weak-monitoring
    regime), the per-collision distinguishability `γ = |cos²θ - sin²θ| = |cos 2θ|` is
    strictly `< 1` — a single collision only partially distinguishes the outcomes.  (At
    `θ = π/4` it is `0`: a one-shot perfect record.)  No assumption: `γ < 1` follows from
    the Hamiltonian via `branch_overlap`. -/
theorem gamma_lt_one {θ : ℝ} (hθ0 : 0 < θ) (hθ : θ < Real.pi / 4) :
    |Real.cos θ ^ 2 - Real.sin θ ^ 2| < 1 := by
  have hpi := Real.pi_pos
  have hsin_pos : 0 < Real.sin θ := Real.sin_pos_of_pos_of_lt_pi hθ0 (by linarith)
  have hcos_pos : 0 < Real.cos θ := Real.cos_pos_of_mem_Ioo ⟨by linarith, by linarith⟩
  have hkey : Real.cos θ ^ 2 - Real.sin θ ^ 2 = 1 - 2 * Real.sin θ ^ 2 := by
    nlinarith [Real.sin_sq_add_cos_sq θ]
  have hsin_lt : Real.sin θ < Real.cos θ := by
    have hmono : Real.sin θ < Real.sin (Real.pi / 4) :=
      Real.strictMonoOn_sin ⟨by linarith, by linarith⟩ ⟨by linarith, by linarith⟩ hθ
    have hanti : Real.cos (Real.pi / 4) < Real.cos θ :=
      Real.strictAntiOn_cos ⟨by linarith, by linarith⟩ ⟨by linarith, by linarith⟩ hθ
    rw [Real.sin_pi_div_four] at hmono
    rw [Real.cos_pi_div_four] at hanti
    linarith
  rw [hkey, abs_lt]
  refine ⟨?_, ?_⟩
  · nlinarith [hsin_pos, hcos_pos, hsin_lt]
  · nlinarith [hsin_pos]

/- ── factorized amplification: γ supplied to the SBSBridge chain ─────────────── -/

open QIQTH.SBSBridge

/-- **Factorized amplification (Hamiltonian-supplied `γ`).**  Over a block `B` of
    independent collisions — each with the same per-collision overlap `c = cos 2θ` (fresh
    environment qubit, identical coupling) — the joint branch overlap is the product
    `∏ c = (cos 2θ)^|B|`, bounded by `γ^|B|` with `γ = |cos 2θ|`.  This is `overlap_amplifies`
    with `γ` now COMPUTED from the toy Hamiltonian rather than assumed. -/
theorem collisional_block_overlap {Frag : Type*} (B : Finset Frag) (θ : ℝ) :
    ‖∏ _a ∈ B, ((Real.cos (2 * θ) : ℝ) : ℂ)‖ ≤ |Real.cos (2 * θ)| ^ B.card :=
  overlap_amplifies B (fun _ => ((Real.cos (2 * θ) : ℝ) : ℂ))
    (fun _ _ => le_of_eq (Complex.norm_real _))

/-- **Exponential record formation.**  With `γ = |cos 2θ| < 1` (from `gamma_lt_one`, i.e.
    generic coupling `0 < θ < π/4`), the block overlap `γ^L → 0` as the number of collisions
    `L → ∞`: weak per-collision monitoring is amplified into near-perfect (orthogonal)
    redundant records.  This is `block_overlap_tendsto_zero` with `γ` Hamiltonian-derived. -/
theorem collisional_overlap_tendsto_zero {θ : ℝ} (hθ0 : 0 < θ) (hθ : θ < Real.pi / 4) :
    Filter.Tendsto (fun L : ℕ => |Real.cos (2 * θ)| ^ L) Filter.atTop (nhds 0) := by
  have hlt : |Real.cos (2 * θ)| < 1 := by
    have h := gamma_lt_one hθ0 hθ
    have he : Real.cos θ ^ 2 - Real.sin θ ^ 2 = Real.cos (2 * θ) := by
      have := Real.cos_two_mul θ
      nlinarith [Real.sin_sq_add_cos_sq θ]
    rwa [he] at h
  exact block_overlap_tendsto_zero (abs_nonneg _) hlt

/- ── non-vacuity: a concrete σ_x witness on ℂ² realizing γ = |cos 2θ| ───────────

   The abstract results above hold for ANY self-adjoint involution `A` with a
   non-degenerate coupling (`⟪ε₀, A ε₀⟫ = 0`).  We exhibit the canonical instance
   `A = σ_x` on `EuclideanSpace ℂ (Fin 2)`, `ε₀ = e₀`, refuting vacuity: there really is
   a Hamiltonian producing `γ = |cos 2θ|`. -/

/-- `σ_x` on `ℂ²` as a linear map (coordinate swap `e₀ ↔ e₁`). -/
noncomputable def sigmaX : EuclideanSpace ℂ (Fin 2) →ₗ[ℂ] EuclideanSpace ℂ (Fin 2) where
  toFun x := !₂[x 1, x 0]
  map_add' x y := by ext i; fin_cases i <;> simp
  map_smul' c x := by ext i; fin_cases i <;> simp

@[simp] theorem sigmaX_apply (x : EuclideanSpace ℂ (Fin 2)) (i : Fin 2) :
    sigmaX x i = x (Equiv.swap 0 1 i) := by
  fin_cases i <;> simp [sigmaX]

/-- The `σ_x` toy interaction on `ℂ²`: a self-adjoint involution. -/
noncomputable def sigmaXInteraction : ToyInteraction (EuclideanSpace ℂ (Fin 2)) where
  A := sigmaX
  symm x y := by
    simp only [PiLp.inner_apply, RCLike.inner_apply, Fin.sum_univ_two, sigmaX_apply,
      Equiv.swap_apply_left, Equiv.swap_apply_right]
    ring
  invol x := by
    ext i; fin_cases i <;> simp [sigmaX]

/-- **Non-vacuity:** the `σ_x` model on `ℂ²` realizes the per-collision overlap
    `⟨E_+ | E_- ⟩ = cos 2θ`, so a concrete Hamiltonian genuinely produces `γ = |cos 2θ| < 1`
    (the abstract theorems are not vacuous). -/
theorem sigmaX_branch_overlap (θ : ℝ) :
    inner ℂ (branchPlus sigmaXInteraction θ (EuclideanSpace.single 0 1))
            (branchMinus sigmaXInteraction θ (EuclideanSpace.single 0 1))
      = ((Real.cos (2 * θ) : ℝ) : ℂ) := by
  refine branch_overlap_cos_two_mul sigmaXInteraction θ _ ?_ ?_
  · simp
  · show inner ℂ _ (sigmaX (EuclideanSpace.single 0 1)) = 0
    simp [PiLp.inner_apply, sigmaX_apply, Equiv.swap_apply_left]

end QIQTH.CollisionalGamma
