/-
Copyright (c) 2026 Pawel Kaplanski. All rights reserved.
Released under Apache 2.0 license.
-/
import QIQTH.ExpJet5D5CurveAbstract
import Mathlib

/-!
# JET-5 TOWER — genuine order-4 curve multilinearity `expJet4CurveG_{add,smul}` (J5-4 support)

Curve-level 4-slot multilinearity of the genuine quadruple feeder `expJet4CurveG`
(mirror of `expJet3CurveG_{add,smul}_*` one Fréchet order up), via `expJet4Curve_congr` +
`expJet4Curve_{add,smul}_*` and the pair/triple feeder multilinearity.  Feeds the five
quadruple-`Q····` slots of the `expJet5ValG` bridge.

## Honest firewall (binding)
J5-4 support only.  NOT `exp_p ∈ C⁵`, NOT `κ = 1/6`, NOT `a₁ = R/6`.  Axiom-free.
-/

namespace QIQTH.ExpMap

open QIQTH.Curvature QIQTH.Geodesic
open Finset Topology

set_option maxSynthPendingDepth 4
set_option maxHeartbeats 1600000

variable {n : ℕ}


theorem expJet4CurveG_add_h (g gi : Point n → Fin n → Fin n → ℝ)
    (hC : ∀ a b c, ContDiff ℝ (⊤ : WithTop ℕ∞) (fun y => christoffel g gi a b c y)) (p v : Point n)
    (Φ : ℝ → ((Point n × Point n) →L[ℝ] (Point n × Point n)))
    (hv : ‖v‖ ≤ expRho g gi hC p) (hΦcont : ContinuousOn Φ (Set.Icc (0 : ℝ) 1))
    (h₁ h₂ k l m : Point n) : ∀ t ∈ (Set.Icc (0 : ℝ) 1),
    expJet4CurveG g gi hC p v Φ hv hΦcont (h₁ + h₂) k l m t
      = expJet4CurveG g gi hC p v Φ hv hΦcont h₁ k l m t
        + expJet4CurveG g gi hC p v Φ hv hΦcont h₂ k l m t := by
  intro t ht
  have hbridge := expJet4Curve_congr g gi hC p v Φ
      (expJet2Curve g gi hC p v Φ hv hΦcont (h₁ + h₂) k)
      (expJet2Curve g gi hC p v Φ hv hΦcont (h₁ + h₂) l)
      (expJet2Curve g gi hC p v Φ hv hΦcont (h₁ + h₂) m)
      (expJet2Curve g gi hC p v Φ hv hΦcont k l)
      (expJet2Curve g gi hC p v Φ hv hΦcont k m)
      (expJet2Curve g gi hC p v Φ hv hΦcont l m)
      (expJet3CurveG g gi hC p v Φ hv hΦcont (h₁ + h₂) k l)
      (expJet3CurveG g gi hC p v Φ hv hΦcont (h₁ + h₂) k m)
      (expJet3CurveG g gi hC p v Φ hv hΦcont (h₁ + h₂) l m)
      (expJet3CurveG g gi hC p v Φ hv hΦcont k l m)
      ((fun s => expJet2Curve g gi hC p v Φ hv hΦcont h₁ k s + expJet2Curve g gi hC p v Φ hv hΦcont h₂ k s))
      ((fun s => expJet2Curve g gi hC p v Φ hv hΦcont h₁ l s + expJet2Curve g gi hC p v Φ hv hΦcont h₂ l s))
      ((fun s => expJet2Curve g gi hC p v Φ hv hΦcont h₁ m s + expJet2Curve g gi hC p v Φ hv hΦcont h₂ m s))
      (expJet2Curve g gi hC p v Φ hv hΦcont k l)
      (expJet2Curve g gi hC p v Φ hv hΦcont k m)
      (expJet2Curve g gi hC p v Φ hv hΦcont l m)
      ((fun s => expJet3CurveG g gi hC p v Φ hv hΦcont h₁ k l s + expJet3CurveG g gi hC p v Φ hv hΦcont h₂ k l s))
      ((fun s => expJet3CurveG g gi hC p v Φ hv hΦcont h₁ k m s + expJet3CurveG g gi hC p v Φ hv hΦcont h₂ k m s))
      ((fun s => expJet3CurveG g gi hC p v Φ hv hΦcont h₁ l m s + expJet3CurveG g gi hC p v Φ hv hΦcont h₂ l m s))
      (expJet3CurveG g gi hC p v Φ hv hΦcont k l m)
      hv hΦcont
      (expJet2Curve_continuousOn g gi hC p v Φ hv hΦcont (h₁ + h₂) k)
      (expJet2Curve_continuousOn g gi hC p v Φ hv hΦcont (h₁ + h₂) l)
      (expJet2Curve_continuousOn g gi hC p v Φ hv hΦcont (h₁ + h₂) m)
      (expJet2Curve_continuousOn g gi hC p v Φ hv hΦcont k l)
      (expJet2Curve_continuousOn g gi hC p v Φ hv hΦcont k m)
      (expJet2Curve_continuousOn g gi hC p v Φ hv hΦcont l m)
      (expJet3CurveG_continuousOn g gi hC p v Φ hv hΦcont (h₁ + h₂) k l)
      (expJet3CurveG_continuousOn g gi hC p v Φ hv hΦcont (h₁ + h₂) k m)
      (expJet3CurveG_continuousOn g gi hC p v Φ hv hΦcont (h₁ + h₂) l m)
      (expJet3CurveG_continuousOn g gi hC p v Φ hv hΦcont k l m)
      (((expJet2Curve_continuousOn g gi hC p v Φ hv hΦcont h₁ k).add (expJet2Curve_continuousOn g gi hC p v Φ hv hΦcont h₂ k)))
      (((expJet2Curve_continuousOn g gi hC p v Φ hv hΦcont h₁ l).add (expJet2Curve_continuousOn g gi hC p v Φ hv hΦcont h₂ l)))
      (((expJet2Curve_continuousOn g gi hC p v Φ hv hΦcont h₁ m).add (expJet2Curve_continuousOn g gi hC p v Φ hv hΦcont h₂ m)))
      (expJet2Curve_continuousOn g gi hC p v Φ hv hΦcont k l)
      (expJet2Curve_continuousOn g gi hC p v Φ hv hΦcont k m)
      (expJet2Curve_continuousOn g gi hC p v Φ hv hΦcont l m)
      (((expJet3CurveG_continuousOn g gi hC p v Φ hv hΦcont h₁ k l).add (expJet3CurveG_continuousOn g gi hC p v Φ hv hΦcont h₂ k l)))
      (((expJet3CurveG_continuousOn g gi hC p v Φ hv hΦcont h₁ k m).add (expJet3CurveG_continuousOn g gi hC p v Φ hv hΦcont h₂ k m)))
      (((expJet3CurveG_continuousOn g gi hC p v Φ hv hΦcont h₁ l m).add (expJet3CurveG_continuousOn g gi hC p v Φ hv hΦcont h₂ l m)))
      (expJet3CurveG_continuousOn g gi hC p v Φ hv hΦcont k l m)
      (h₁ + h₂) k l m
      ((expJet2Curve_add_left g gi hC p v Φ hv hΦcont h₁ h₂ k))
      ((expJet2Curve_add_left g gi hC p v Φ hv hΦcont h₁ h₂ l))
      ((expJet2Curve_add_left g gi hC p v Φ hv hΦcont h₁ h₂ m))
      ((fun _ _ => rfl))
      ((fun _ _ => rfl))
      ((fun _ _ => rfl))
      ((expJet3CurveG_add_h g gi hC p v Φ hv hΦcont h₁ h₂ k l))
      ((expJet3CurveG_add_h g gi hC p v Φ hv hΦcont h₁ h₂ k m))
      ((expJet3CurveG_add_h g gi hC p v Φ hv hΦcont h₁ h₂ l m))
      ((fun _ _ => rfl))
      t ht
  simp only [expJet4CurveG]
  rw [hbridge]
  exact expJet4Curve_add_h g gi hC p v Φ
    (expJet2Curve g gi hC p v Φ hv hΦcont h₁ k)
    (expJet2Curve g gi hC p v Φ hv hΦcont h₂ k)
    (expJet2Curve g gi hC p v Φ hv hΦcont h₁ l)
    (expJet2Curve g gi hC p v Φ hv hΦcont h₂ l)
    (expJet2Curve g gi hC p v Φ hv hΦcont h₁ m)
    (expJet2Curve g gi hC p v Φ hv hΦcont h₂ m)
    (expJet2Curve g gi hC p v Φ hv hΦcont k l)
    (expJet2Curve g gi hC p v Φ hv hΦcont k m)
    (expJet2Curve g gi hC p v Φ hv hΦcont l m)
    (expJet3CurveG g gi hC p v Φ hv hΦcont h₁ k l)
    (expJet3CurveG g gi hC p v Φ hv hΦcont h₂ k l)
    (expJet3CurveG g gi hC p v Φ hv hΦcont h₁ k m)
    (expJet3CurveG g gi hC p v Φ hv hΦcont h₂ k m)
    (expJet3CurveG g gi hC p v Φ hv hΦcont h₁ l m)
    (expJet3CurveG g gi hC p v Φ hv hΦcont h₂ l m)
    (expJet3CurveG g gi hC p v Φ hv hΦcont k l m)
    hv hΦcont
    (expJet2Curve_continuousOn g gi hC p v Φ hv hΦcont h₁ k)
    (expJet2Curve_continuousOn g gi hC p v Φ hv hΦcont h₂ k)
    (expJet2Curve_continuousOn g gi hC p v Φ hv hΦcont h₁ l)
    (expJet2Curve_continuousOn g gi hC p v Φ hv hΦcont h₂ l)
    (expJet2Curve_continuousOn g gi hC p v Φ hv hΦcont h₁ m)
    (expJet2Curve_continuousOn g gi hC p v Φ hv hΦcont h₂ m)
    (expJet2Curve_continuousOn g gi hC p v Φ hv hΦcont k l)
    (expJet2Curve_continuousOn g gi hC p v Φ hv hΦcont k m)
    (expJet2Curve_continuousOn g gi hC p v Φ hv hΦcont l m)
    (expJet3CurveG_continuousOn g gi hC p v Φ hv hΦcont h₁ k l)
    (expJet3CurveG_continuousOn g gi hC p v Φ hv hΦcont h₂ k l)
    (expJet3CurveG_continuousOn g gi hC p v Φ hv hΦcont h₁ k m)
    (expJet3CurveG_continuousOn g gi hC p v Φ hv hΦcont h₂ k m)
    (expJet3CurveG_continuousOn g gi hC p v Φ hv hΦcont h₁ l m)
    (expJet3CurveG_continuousOn g gi hC p v Φ hv hΦcont h₂ l m)
    (expJet3CurveG_continuousOn g gi hC p v Φ hv hΦcont k l m)
    h₁ h₂ k l m t ht

theorem expJet4CurveG_smul_h (g gi : Point n → Fin n → Fin n → ℝ)
    (hC : ∀ a b c, ContDiff ℝ (⊤ : WithTop ℕ∞) (fun y => christoffel g gi a b c y)) (p v : Point n)
    (Φ : ℝ → ((Point n × Point n) →L[ℝ] (Point n × Point n)))
    (hv : ‖v‖ ≤ expRho g gi hC p) (hΦcont : ContinuousOn Φ (Set.Icc (0 : ℝ) 1))
    (c : ℝ) (h k l m : Point n) : ∀ t ∈ (Set.Icc (0 : ℝ) 1),
    expJet4CurveG g gi hC p v Φ hv hΦcont (c • h) k l m t
      = c • expJet4CurveG g gi hC p v Φ hv hΦcont h k l m t := by
  intro t ht
  have hbridge := expJet4Curve_congr g gi hC p v Φ
      (expJet2Curve g gi hC p v Φ hv hΦcont (c • h) k)
      (expJet2Curve g gi hC p v Φ hv hΦcont (c • h) l)
      (expJet2Curve g gi hC p v Φ hv hΦcont (c • h) m)
      (expJet2Curve g gi hC p v Φ hv hΦcont k l)
      (expJet2Curve g gi hC p v Φ hv hΦcont k m)
      (expJet2Curve g gi hC p v Φ hv hΦcont l m)
      (expJet3CurveG g gi hC p v Φ hv hΦcont (c • h) k l)
      (expJet3CurveG g gi hC p v Φ hv hΦcont (c • h) k m)
      (expJet3CurveG g gi hC p v Φ hv hΦcont (c • h) l m)
      (expJet3CurveG g gi hC p v Φ hv hΦcont k l m)
      ((fun s => c • expJet2Curve g gi hC p v Φ hv hΦcont h k s))
      ((fun s => c • expJet2Curve g gi hC p v Φ hv hΦcont h l s))
      ((fun s => c • expJet2Curve g gi hC p v Φ hv hΦcont h m s))
      (expJet2Curve g gi hC p v Φ hv hΦcont k l)
      (expJet2Curve g gi hC p v Φ hv hΦcont k m)
      (expJet2Curve g gi hC p v Φ hv hΦcont l m)
      ((fun s => c • expJet3CurveG g gi hC p v Φ hv hΦcont h k l s))
      ((fun s => c • expJet3CurveG g gi hC p v Φ hv hΦcont h k m s))
      ((fun s => c • expJet3CurveG g gi hC p v Φ hv hΦcont h l m s))
      (expJet3CurveG g gi hC p v Φ hv hΦcont k l m)
      hv hΦcont
      (expJet2Curve_continuousOn g gi hC p v Φ hv hΦcont (c • h) k)
      (expJet2Curve_continuousOn g gi hC p v Φ hv hΦcont (c • h) l)
      (expJet2Curve_continuousOn g gi hC p v Φ hv hΦcont (c • h) m)
      (expJet2Curve_continuousOn g gi hC p v Φ hv hΦcont k l)
      (expJet2Curve_continuousOn g gi hC p v Φ hv hΦcont k m)
      (expJet2Curve_continuousOn g gi hC p v Φ hv hΦcont l m)
      (expJet3CurveG_continuousOn g gi hC p v Φ hv hΦcont (c • h) k l)
      (expJet3CurveG_continuousOn g gi hC p v Φ hv hΦcont (c • h) k m)
      (expJet3CurveG_continuousOn g gi hC p v Φ hv hΦcont (c • h) l m)
      (expJet3CurveG_continuousOn g gi hC p v Φ hv hΦcont k l m)
      (((expJet2Curve_continuousOn g gi hC p v Φ hv hΦcont h k).const_smul c))
      (((expJet2Curve_continuousOn g gi hC p v Φ hv hΦcont h l).const_smul c))
      (((expJet2Curve_continuousOn g gi hC p v Φ hv hΦcont h m).const_smul c))
      (expJet2Curve_continuousOn g gi hC p v Φ hv hΦcont k l)
      (expJet2Curve_continuousOn g gi hC p v Φ hv hΦcont k m)
      (expJet2Curve_continuousOn g gi hC p v Φ hv hΦcont l m)
      (((expJet3CurveG_continuousOn g gi hC p v Φ hv hΦcont h k l).const_smul c))
      (((expJet3CurveG_continuousOn g gi hC p v Φ hv hΦcont h k m).const_smul c))
      (((expJet3CurveG_continuousOn g gi hC p v Φ hv hΦcont h l m).const_smul c))
      (expJet3CurveG_continuousOn g gi hC p v Φ hv hΦcont k l m)
      (c • h) k l m
      ((expJet2Curve_smul_left g gi hC p v Φ hv hΦcont c h k))
      ((expJet2Curve_smul_left g gi hC p v Φ hv hΦcont c h l))
      ((expJet2Curve_smul_left g gi hC p v Φ hv hΦcont c h m))
      ((fun _ _ => rfl))
      ((fun _ _ => rfl))
      ((fun _ _ => rfl))
      ((expJet3CurveG_smul_h g gi hC p v Φ hv hΦcont c h k l))
      ((expJet3CurveG_smul_h g gi hC p v Φ hv hΦcont c h k m))
      ((expJet3CurveG_smul_h g gi hC p v Φ hv hΦcont c h l m))
      ((fun _ _ => rfl))
      t ht
  simp only [expJet4CurveG]
  rw [hbridge]
  exact expJet4Curve_smul_h g gi hC p v Φ
    (expJet2Curve g gi hC p v Φ hv hΦcont h k)
    (expJet2Curve g gi hC p v Φ hv hΦcont h l)
    (expJet2Curve g gi hC p v Φ hv hΦcont h m)
    (expJet2Curve g gi hC p v Φ hv hΦcont k l)
    (expJet2Curve g gi hC p v Φ hv hΦcont k m)
    (expJet2Curve g gi hC p v Φ hv hΦcont l m)
    (expJet3CurveG g gi hC p v Φ hv hΦcont h k l)
    (expJet3CurveG g gi hC p v Φ hv hΦcont h k m)
    (expJet3CurveG g gi hC p v Φ hv hΦcont h l m)
    (expJet3CurveG g gi hC p v Φ hv hΦcont k l m)
    hv hΦcont
    (expJet2Curve_continuousOn g gi hC p v Φ hv hΦcont h k)
    (expJet2Curve_continuousOn g gi hC p v Φ hv hΦcont h l)
    (expJet2Curve_continuousOn g gi hC p v Φ hv hΦcont h m)
    (expJet2Curve_continuousOn g gi hC p v Φ hv hΦcont k l)
    (expJet2Curve_continuousOn g gi hC p v Φ hv hΦcont k m)
    (expJet2Curve_continuousOn g gi hC p v Φ hv hΦcont l m)
    (expJet3CurveG_continuousOn g gi hC p v Φ hv hΦcont h k l)
    (expJet3CurveG_continuousOn g gi hC p v Φ hv hΦcont h k m)
    (expJet3CurveG_continuousOn g gi hC p v Φ hv hΦcont h l m)
    (expJet3CurveG_continuousOn g gi hC p v Φ hv hΦcont k l m)
    c h k l m t ht

theorem expJet4CurveG_add_k (g gi : Point n → Fin n → Fin n → ℝ)
    (hC : ∀ a b c, ContDiff ℝ (⊤ : WithTop ℕ∞) (fun y => christoffel g gi a b c y)) (p v : Point n)
    (Φ : ℝ → ((Point n × Point n) →L[ℝ] (Point n × Point n)))
    (hv : ‖v‖ ≤ expRho g gi hC p) (hΦcont : ContinuousOn Φ (Set.Icc (0 : ℝ) 1))
    (h k₁ k₂ l m : Point n) : ∀ t ∈ (Set.Icc (0 : ℝ) 1),
    expJet4CurveG g gi hC p v Φ hv hΦcont h (k₁ + k₂) l m t
      = expJet4CurveG g gi hC p v Φ hv hΦcont h k₁ l m t
        + expJet4CurveG g gi hC p v Φ hv hΦcont h k₂ l m t := by
  intro t ht
  have hbridge := expJet4Curve_congr g gi hC p v Φ
      (expJet2Curve g gi hC p v Φ hv hΦcont h (k₁ + k₂))
      (expJet2Curve g gi hC p v Φ hv hΦcont h l)
      (expJet2Curve g gi hC p v Φ hv hΦcont h m)
      (expJet2Curve g gi hC p v Φ hv hΦcont (k₁ + k₂) l)
      (expJet2Curve g gi hC p v Φ hv hΦcont (k₁ + k₂) m)
      (expJet2Curve g gi hC p v Φ hv hΦcont l m)
      (expJet3CurveG g gi hC p v Φ hv hΦcont h (k₁ + k₂) l)
      (expJet3CurveG g gi hC p v Φ hv hΦcont h (k₁ + k₂) m)
      (expJet3CurveG g gi hC p v Φ hv hΦcont h l m)
      (expJet3CurveG g gi hC p v Φ hv hΦcont (k₁ + k₂) l m)
      ((fun s => expJet2Curve g gi hC p v Φ hv hΦcont h k₁ s + expJet2Curve g gi hC p v Φ hv hΦcont h k₂ s))
      (expJet2Curve g gi hC p v Φ hv hΦcont h l)
      (expJet2Curve g gi hC p v Φ hv hΦcont h m)
      ((fun s => expJet2Curve g gi hC p v Φ hv hΦcont k₁ l s + expJet2Curve g gi hC p v Φ hv hΦcont k₂ l s))
      ((fun s => expJet2Curve g gi hC p v Φ hv hΦcont k₁ m s + expJet2Curve g gi hC p v Φ hv hΦcont k₂ m s))
      (expJet2Curve g gi hC p v Φ hv hΦcont l m)
      ((fun s => expJet3CurveG g gi hC p v Φ hv hΦcont h k₁ l s + expJet3CurveG g gi hC p v Φ hv hΦcont h k₂ l s))
      ((fun s => expJet3CurveG g gi hC p v Φ hv hΦcont h k₁ m s + expJet3CurveG g gi hC p v Φ hv hΦcont h k₂ m s))
      (expJet3CurveG g gi hC p v Φ hv hΦcont h l m)
      ((fun s => expJet3CurveG g gi hC p v Φ hv hΦcont k₁ l m s + expJet3CurveG g gi hC p v Φ hv hΦcont k₂ l m s))
      hv hΦcont
      (expJet2Curve_continuousOn g gi hC p v Φ hv hΦcont h (k₁ + k₂))
      (expJet2Curve_continuousOn g gi hC p v Φ hv hΦcont h l)
      (expJet2Curve_continuousOn g gi hC p v Φ hv hΦcont h m)
      (expJet2Curve_continuousOn g gi hC p v Φ hv hΦcont (k₁ + k₂) l)
      (expJet2Curve_continuousOn g gi hC p v Φ hv hΦcont (k₁ + k₂) m)
      (expJet2Curve_continuousOn g gi hC p v Φ hv hΦcont l m)
      (expJet3CurveG_continuousOn g gi hC p v Φ hv hΦcont h (k₁ + k₂) l)
      (expJet3CurveG_continuousOn g gi hC p v Φ hv hΦcont h (k₁ + k₂) m)
      (expJet3CurveG_continuousOn g gi hC p v Φ hv hΦcont h l m)
      (expJet3CurveG_continuousOn g gi hC p v Φ hv hΦcont (k₁ + k₂) l m)
      (((expJet2Curve_continuousOn g gi hC p v Φ hv hΦcont h k₁).add (expJet2Curve_continuousOn g gi hC p v Φ hv hΦcont h k₂)))
      (expJet2Curve_continuousOn g gi hC p v Φ hv hΦcont h l)
      (expJet2Curve_continuousOn g gi hC p v Φ hv hΦcont h m)
      (((expJet2Curve_continuousOn g gi hC p v Φ hv hΦcont k₁ l).add (expJet2Curve_continuousOn g gi hC p v Φ hv hΦcont k₂ l)))
      (((expJet2Curve_continuousOn g gi hC p v Φ hv hΦcont k₁ m).add (expJet2Curve_continuousOn g gi hC p v Φ hv hΦcont k₂ m)))
      (expJet2Curve_continuousOn g gi hC p v Φ hv hΦcont l m)
      (((expJet3CurveG_continuousOn g gi hC p v Φ hv hΦcont h k₁ l).add (expJet3CurveG_continuousOn g gi hC p v Φ hv hΦcont h k₂ l)))
      (((expJet3CurveG_continuousOn g gi hC p v Φ hv hΦcont h k₁ m).add (expJet3CurveG_continuousOn g gi hC p v Φ hv hΦcont h k₂ m)))
      (expJet3CurveG_continuousOn g gi hC p v Φ hv hΦcont h l m)
      (((expJet3CurveG_continuousOn g gi hC p v Φ hv hΦcont k₁ l m).add (expJet3CurveG_continuousOn g gi hC p v Φ hv hΦcont k₂ l m)))
      h (k₁ + k₂) l m
      ((expJet2Curve_add_right g gi hC p v Φ hv hΦcont h k₁ k₂))
      ((fun _ _ => rfl))
      ((fun _ _ => rfl))
      ((expJet2Curve_add_left g gi hC p v Φ hv hΦcont k₁ k₂ l))
      ((expJet2Curve_add_left g gi hC p v Φ hv hΦcont k₁ k₂ m))
      ((fun _ _ => rfl))
      ((expJet3CurveG_add_k g gi hC p v Φ hv hΦcont h k₁ k₂ l))
      ((expJet3CurveG_add_k g gi hC p v Φ hv hΦcont h k₁ k₂ m))
      ((fun _ _ => rfl))
      ((expJet3CurveG_add_h g gi hC p v Φ hv hΦcont k₁ k₂ l m))
      t ht
  simp only [expJet4CurveG]
  rw [hbridge]
  exact expJet4Curve_add_k g gi hC p v Φ
    (expJet2Curve g gi hC p v Φ hv hΦcont h k₁)
    (expJet2Curve g gi hC p v Φ hv hΦcont h k₂)
    (expJet2Curve g gi hC p v Φ hv hΦcont h l)
    (expJet2Curve g gi hC p v Φ hv hΦcont h m)
    (expJet2Curve g gi hC p v Φ hv hΦcont k₁ l)
    (expJet2Curve g gi hC p v Φ hv hΦcont k₂ l)
    (expJet2Curve g gi hC p v Φ hv hΦcont k₁ m)
    (expJet2Curve g gi hC p v Φ hv hΦcont k₂ m)
    (expJet2Curve g gi hC p v Φ hv hΦcont l m)
    (expJet3CurveG g gi hC p v Φ hv hΦcont h k₁ l)
    (expJet3CurveG g gi hC p v Φ hv hΦcont h k₂ l)
    (expJet3CurveG g gi hC p v Φ hv hΦcont h k₁ m)
    (expJet3CurveG g gi hC p v Φ hv hΦcont h k₂ m)
    (expJet3CurveG g gi hC p v Φ hv hΦcont h l m)
    (expJet3CurveG g gi hC p v Φ hv hΦcont k₁ l m)
    (expJet3CurveG g gi hC p v Φ hv hΦcont k₂ l m)
    hv hΦcont
    (expJet2Curve_continuousOn g gi hC p v Φ hv hΦcont h k₁)
    (expJet2Curve_continuousOn g gi hC p v Φ hv hΦcont h k₂)
    (expJet2Curve_continuousOn g gi hC p v Φ hv hΦcont h l)
    (expJet2Curve_continuousOn g gi hC p v Φ hv hΦcont h m)
    (expJet2Curve_continuousOn g gi hC p v Φ hv hΦcont k₁ l)
    (expJet2Curve_continuousOn g gi hC p v Φ hv hΦcont k₂ l)
    (expJet2Curve_continuousOn g gi hC p v Φ hv hΦcont k₁ m)
    (expJet2Curve_continuousOn g gi hC p v Φ hv hΦcont k₂ m)
    (expJet2Curve_continuousOn g gi hC p v Φ hv hΦcont l m)
    (expJet3CurveG_continuousOn g gi hC p v Φ hv hΦcont h k₁ l)
    (expJet3CurveG_continuousOn g gi hC p v Φ hv hΦcont h k₂ l)
    (expJet3CurveG_continuousOn g gi hC p v Φ hv hΦcont h k₁ m)
    (expJet3CurveG_continuousOn g gi hC p v Φ hv hΦcont h k₂ m)
    (expJet3CurveG_continuousOn g gi hC p v Φ hv hΦcont h l m)
    (expJet3CurveG_continuousOn g gi hC p v Φ hv hΦcont k₁ l m)
    (expJet3CurveG_continuousOn g gi hC p v Φ hv hΦcont k₂ l m)
    h k₁ k₂ l m t ht

theorem expJet4CurveG_smul_k (g gi : Point n → Fin n → Fin n → ℝ)
    (hC : ∀ a b c, ContDiff ℝ (⊤ : WithTop ℕ∞) (fun y => christoffel g gi a b c y)) (p v : Point n)
    (Φ : ℝ → ((Point n × Point n) →L[ℝ] (Point n × Point n)))
    (hv : ‖v‖ ≤ expRho g gi hC p) (hΦcont : ContinuousOn Φ (Set.Icc (0 : ℝ) 1))
    (c : ℝ) (h k l m : Point n) : ∀ t ∈ (Set.Icc (0 : ℝ) 1),
    expJet4CurveG g gi hC p v Φ hv hΦcont h (c • k) l m t
      = c • expJet4CurveG g gi hC p v Φ hv hΦcont h k l m t := by
  intro t ht
  have hbridge := expJet4Curve_congr g gi hC p v Φ
      (expJet2Curve g gi hC p v Φ hv hΦcont h (c • k))
      (expJet2Curve g gi hC p v Φ hv hΦcont h l)
      (expJet2Curve g gi hC p v Φ hv hΦcont h m)
      (expJet2Curve g gi hC p v Φ hv hΦcont (c • k) l)
      (expJet2Curve g gi hC p v Φ hv hΦcont (c • k) m)
      (expJet2Curve g gi hC p v Φ hv hΦcont l m)
      (expJet3CurveG g gi hC p v Φ hv hΦcont h (c • k) l)
      (expJet3CurveG g gi hC p v Φ hv hΦcont h (c • k) m)
      (expJet3CurveG g gi hC p v Φ hv hΦcont h l m)
      (expJet3CurveG g gi hC p v Φ hv hΦcont (c • k) l m)
      ((fun s => c • expJet2Curve g gi hC p v Φ hv hΦcont h k s))
      (expJet2Curve g gi hC p v Φ hv hΦcont h l)
      (expJet2Curve g gi hC p v Φ hv hΦcont h m)
      ((fun s => c • expJet2Curve g gi hC p v Φ hv hΦcont k l s))
      ((fun s => c • expJet2Curve g gi hC p v Φ hv hΦcont k m s))
      (expJet2Curve g gi hC p v Φ hv hΦcont l m)
      ((fun s => c • expJet3CurveG g gi hC p v Φ hv hΦcont h k l s))
      ((fun s => c • expJet3CurveG g gi hC p v Φ hv hΦcont h k m s))
      (expJet3CurveG g gi hC p v Φ hv hΦcont h l m)
      ((fun s => c • expJet3CurveG g gi hC p v Φ hv hΦcont k l m s))
      hv hΦcont
      (expJet2Curve_continuousOn g gi hC p v Φ hv hΦcont h (c • k))
      (expJet2Curve_continuousOn g gi hC p v Φ hv hΦcont h l)
      (expJet2Curve_continuousOn g gi hC p v Φ hv hΦcont h m)
      (expJet2Curve_continuousOn g gi hC p v Φ hv hΦcont (c • k) l)
      (expJet2Curve_continuousOn g gi hC p v Φ hv hΦcont (c • k) m)
      (expJet2Curve_continuousOn g gi hC p v Φ hv hΦcont l m)
      (expJet3CurveG_continuousOn g gi hC p v Φ hv hΦcont h (c • k) l)
      (expJet3CurveG_continuousOn g gi hC p v Φ hv hΦcont h (c • k) m)
      (expJet3CurveG_continuousOn g gi hC p v Φ hv hΦcont h l m)
      (expJet3CurveG_continuousOn g gi hC p v Φ hv hΦcont (c • k) l m)
      (((expJet2Curve_continuousOn g gi hC p v Φ hv hΦcont h k).const_smul c))
      (expJet2Curve_continuousOn g gi hC p v Φ hv hΦcont h l)
      (expJet2Curve_continuousOn g gi hC p v Φ hv hΦcont h m)
      (((expJet2Curve_continuousOn g gi hC p v Φ hv hΦcont k l).const_smul c))
      (((expJet2Curve_continuousOn g gi hC p v Φ hv hΦcont k m).const_smul c))
      (expJet2Curve_continuousOn g gi hC p v Φ hv hΦcont l m)
      (((expJet3CurveG_continuousOn g gi hC p v Φ hv hΦcont h k l).const_smul c))
      (((expJet3CurveG_continuousOn g gi hC p v Φ hv hΦcont h k m).const_smul c))
      (expJet3CurveG_continuousOn g gi hC p v Φ hv hΦcont h l m)
      (((expJet3CurveG_continuousOn g gi hC p v Φ hv hΦcont k l m).const_smul c))
      h (c • k) l m
      ((expJet2Curve_smul_right g gi hC p v Φ hv hΦcont c h k))
      ((fun _ _ => rfl))
      ((fun _ _ => rfl))
      ((expJet2Curve_smul_left g gi hC p v Φ hv hΦcont c k l))
      ((expJet2Curve_smul_left g gi hC p v Φ hv hΦcont c k m))
      ((fun _ _ => rfl))
      ((expJet3CurveG_smul_k g gi hC p v Φ hv hΦcont c h k l))
      ((expJet3CurveG_smul_k g gi hC p v Φ hv hΦcont c h k m))
      ((fun _ _ => rfl))
      ((expJet3CurveG_smul_h g gi hC p v Φ hv hΦcont c k l m))
      t ht
  simp only [expJet4CurveG]
  rw [hbridge]
  exact expJet4Curve_smul_k g gi hC p v Φ
    (expJet2Curve g gi hC p v Φ hv hΦcont h k)
    (expJet2Curve g gi hC p v Φ hv hΦcont h l)
    (expJet2Curve g gi hC p v Φ hv hΦcont h m)
    (expJet2Curve g gi hC p v Φ hv hΦcont k l)
    (expJet2Curve g gi hC p v Φ hv hΦcont k m)
    (expJet2Curve g gi hC p v Φ hv hΦcont l m)
    (expJet3CurveG g gi hC p v Φ hv hΦcont h k l)
    (expJet3CurveG g gi hC p v Φ hv hΦcont h k m)
    (expJet3CurveG g gi hC p v Φ hv hΦcont h l m)
    (expJet3CurveG g gi hC p v Φ hv hΦcont k l m)
    hv hΦcont
    (expJet2Curve_continuousOn g gi hC p v Φ hv hΦcont h k)
    (expJet2Curve_continuousOn g gi hC p v Φ hv hΦcont h l)
    (expJet2Curve_continuousOn g gi hC p v Φ hv hΦcont h m)
    (expJet2Curve_continuousOn g gi hC p v Φ hv hΦcont k l)
    (expJet2Curve_continuousOn g gi hC p v Φ hv hΦcont k m)
    (expJet2Curve_continuousOn g gi hC p v Φ hv hΦcont l m)
    (expJet3CurveG_continuousOn g gi hC p v Φ hv hΦcont h k l)
    (expJet3CurveG_continuousOn g gi hC p v Φ hv hΦcont h k m)
    (expJet3CurveG_continuousOn g gi hC p v Φ hv hΦcont h l m)
    (expJet3CurveG_continuousOn g gi hC p v Φ hv hΦcont k l m)
    c h k l m t ht

theorem expJet4CurveG_add_l (g gi : Point n → Fin n → Fin n → ℝ)
    (hC : ∀ a b c, ContDiff ℝ (⊤ : WithTop ℕ∞) (fun y => christoffel g gi a b c y)) (p v : Point n)
    (Φ : ℝ → ((Point n × Point n) →L[ℝ] (Point n × Point n)))
    (hv : ‖v‖ ≤ expRho g gi hC p) (hΦcont : ContinuousOn Φ (Set.Icc (0 : ℝ) 1))
    (h k l₁ l₂ m : Point n) : ∀ t ∈ (Set.Icc (0 : ℝ) 1),
    expJet4CurveG g gi hC p v Φ hv hΦcont h k (l₁ + l₂) m t
      = expJet4CurveG g gi hC p v Φ hv hΦcont h k l₁ m t
        + expJet4CurveG g gi hC p v Φ hv hΦcont h k l₂ m t := by
  intro t ht
  have hbridge := expJet4Curve_congr g gi hC p v Φ
      (expJet2Curve g gi hC p v Φ hv hΦcont h k)
      (expJet2Curve g gi hC p v Φ hv hΦcont h (l₁ + l₂))
      (expJet2Curve g gi hC p v Φ hv hΦcont h m)
      (expJet2Curve g gi hC p v Φ hv hΦcont k (l₁ + l₂))
      (expJet2Curve g gi hC p v Φ hv hΦcont k m)
      (expJet2Curve g gi hC p v Φ hv hΦcont (l₁ + l₂) m)
      (expJet3CurveG g gi hC p v Φ hv hΦcont h k (l₁ + l₂))
      (expJet3CurveG g gi hC p v Φ hv hΦcont h k m)
      (expJet3CurveG g gi hC p v Φ hv hΦcont h (l₁ + l₂) m)
      (expJet3CurveG g gi hC p v Φ hv hΦcont k (l₁ + l₂) m)
      (expJet2Curve g gi hC p v Φ hv hΦcont h k)
      ((fun s => expJet2Curve g gi hC p v Φ hv hΦcont h l₁ s + expJet2Curve g gi hC p v Φ hv hΦcont h l₂ s))
      (expJet2Curve g gi hC p v Φ hv hΦcont h m)
      ((fun s => expJet2Curve g gi hC p v Φ hv hΦcont k l₁ s + expJet2Curve g gi hC p v Φ hv hΦcont k l₂ s))
      (expJet2Curve g gi hC p v Φ hv hΦcont k m)
      ((fun s => expJet2Curve g gi hC p v Φ hv hΦcont l₁ m s + expJet2Curve g gi hC p v Φ hv hΦcont l₂ m s))
      ((fun s => expJet3CurveG g gi hC p v Φ hv hΦcont h k l₁ s + expJet3CurveG g gi hC p v Φ hv hΦcont h k l₂ s))
      (expJet3CurveG g gi hC p v Φ hv hΦcont h k m)
      ((fun s => expJet3CurveG g gi hC p v Φ hv hΦcont h l₁ m s + expJet3CurveG g gi hC p v Φ hv hΦcont h l₂ m s))
      ((fun s => expJet3CurveG g gi hC p v Φ hv hΦcont k l₁ m s + expJet3CurveG g gi hC p v Φ hv hΦcont k l₂ m s))
      hv hΦcont
      (expJet2Curve_continuousOn g gi hC p v Φ hv hΦcont h k)
      (expJet2Curve_continuousOn g gi hC p v Φ hv hΦcont h (l₁ + l₂))
      (expJet2Curve_continuousOn g gi hC p v Φ hv hΦcont h m)
      (expJet2Curve_continuousOn g gi hC p v Φ hv hΦcont k (l₁ + l₂))
      (expJet2Curve_continuousOn g gi hC p v Φ hv hΦcont k m)
      (expJet2Curve_continuousOn g gi hC p v Φ hv hΦcont (l₁ + l₂) m)
      (expJet3CurveG_continuousOn g gi hC p v Φ hv hΦcont h k (l₁ + l₂))
      (expJet3CurveG_continuousOn g gi hC p v Φ hv hΦcont h k m)
      (expJet3CurveG_continuousOn g gi hC p v Φ hv hΦcont h (l₁ + l₂) m)
      (expJet3CurveG_continuousOn g gi hC p v Φ hv hΦcont k (l₁ + l₂) m)
      (expJet2Curve_continuousOn g gi hC p v Φ hv hΦcont h k)
      (((expJet2Curve_continuousOn g gi hC p v Φ hv hΦcont h l₁).add (expJet2Curve_continuousOn g gi hC p v Φ hv hΦcont h l₂)))
      (expJet2Curve_continuousOn g gi hC p v Φ hv hΦcont h m)
      (((expJet2Curve_continuousOn g gi hC p v Φ hv hΦcont k l₁).add (expJet2Curve_continuousOn g gi hC p v Φ hv hΦcont k l₂)))
      (expJet2Curve_continuousOn g gi hC p v Φ hv hΦcont k m)
      (((expJet2Curve_continuousOn g gi hC p v Φ hv hΦcont l₁ m).add (expJet2Curve_continuousOn g gi hC p v Φ hv hΦcont l₂ m)))
      (((expJet3CurveG_continuousOn g gi hC p v Φ hv hΦcont h k l₁).add (expJet3CurveG_continuousOn g gi hC p v Φ hv hΦcont h k l₂)))
      (expJet3CurveG_continuousOn g gi hC p v Φ hv hΦcont h k m)
      (((expJet3CurveG_continuousOn g gi hC p v Φ hv hΦcont h l₁ m).add (expJet3CurveG_continuousOn g gi hC p v Φ hv hΦcont h l₂ m)))
      (((expJet3CurveG_continuousOn g gi hC p v Φ hv hΦcont k l₁ m).add (expJet3CurveG_continuousOn g gi hC p v Φ hv hΦcont k l₂ m)))
      h k (l₁ + l₂) m
      ((fun _ _ => rfl))
      ((expJet2Curve_add_right g gi hC p v Φ hv hΦcont h l₁ l₂))
      ((fun _ _ => rfl))
      ((expJet2Curve_add_right g gi hC p v Φ hv hΦcont k l₁ l₂))
      ((fun _ _ => rfl))
      ((expJet2Curve_add_left g gi hC p v Φ hv hΦcont l₁ l₂ m))
      ((expJet3CurveG_add_l g gi hC p v Φ hv hΦcont h k l₁ l₂))
      ((fun _ _ => rfl))
      ((expJet3CurveG_add_k g gi hC p v Φ hv hΦcont h l₁ l₂ m))
      ((expJet3CurveG_add_k g gi hC p v Φ hv hΦcont k l₁ l₂ m))
      t ht
  simp only [expJet4CurveG]
  rw [hbridge]
  exact expJet4Curve_add_l g gi hC p v Φ
    (expJet2Curve g gi hC p v Φ hv hΦcont h k)
    (expJet2Curve g gi hC p v Φ hv hΦcont h l₁)
    (expJet2Curve g gi hC p v Φ hv hΦcont h l₂)
    (expJet2Curve g gi hC p v Φ hv hΦcont h m)
    (expJet2Curve g gi hC p v Φ hv hΦcont k l₁)
    (expJet2Curve g gi hC p v Φ hv hΦcont k l₂)
    (expJet2Curve g gi hC p v Φ hv hΦcont k m)
    (expJet2Curve g gi hC p v Φ hv hΦcont l₁ m)
    (expJet2Curve g gi hC p v Φ hv hΦcont l₂ m)
    (expJet3CurveG g gi hC p v Φ hv hΦcont h k l₁)
    (expJet3CurveG g gi hC p v Φ hv hΦcont h k l₂)
    (expJet3CurveG g gi hC p v Φ hv hΦcont h k m)
    (expJet3CurveG g gi hC p v Φ hv hΦcont h l₁ m)
    (expJet3CurveG g gi hC p v Φ hv hΦcont h l₂ m)
    (expJet3CurveG g gi hC p v Φ hv hΦcont k l₁ m)
    (expJet3CurveG g gi hC p v Φ hv hΦcont k l₂ m)
    hv hΦcont
    (expJet2Curve_continuousOn g gi hC p v Φ hv hΦcont h k)
    (expJet2Curve_continuousOn g gi hC p v Φ hv hΦcont h l₁)
    (expJet2Curve_continuousOn g gi hC p v Φ hv hΦcont h l₂)
    (expJet2Curve_continuousOn g gi hC p v Φ hv hΦcont h m)
    (expJet2Curve_continuousOn g gi hC p v Φ hv hΦcont k l₁)
    (expJet2Curve_continuousOn g gi hC p v Φ hv hΦcont k l₂)
    (expJet2Curve_continuousOn g gi hC p v Φ hv hΦcont k m)
    (expJet2Curve_continuousOn g gi hC p v Φ hv hΦcont l₁ m)
    (expJet2Curve_continuousOn g gi hC p v Φ hv hΦcont l₂ m)
    (expJet3CurveG_continuousOn g gi hC p v Φ hv hΦcont h k l₁)
    (expJet3CurveG_continuousOn g gi hC p v Φ hv hΦcont h k l₂)
    (expJet3CurveG_continuousOn g gi hC p v Φ hv hΦcont h k m)
    (expJet3CurveG_continuousOn g gi hC p v Φ hv hΦcont h l₁ m)
    (expJet3CurveG_continuousOn g gi hC p v Φ hv hΦcont h l₂ m)
    (expJet3CurveG_continuousOn g gi hC p v Φ hv hΦcont k l₁ m)
    (expJet3CurveG_continuousOn g gi hC p v Φ hv hΦcont k l₂ m)
    h k l₁ l₂ m t ht

theorem expJet4CurveG_smul_l (g gi : Point n → Fin n → Fin n → ℝ)
    (hC : ∀ a b c, ContDiff ℝ (⊤ : WithTop ℕ∞) (fun y => christoffel g gi a b c y)) (p v : Point n)
    (Φ : ℝ → ((Point n × Point n) →L[ℝ] (Point n × Point n)))
    (hv : ‖v‖ ≤ expRho g gi hC p) (hΦcont : ContinuousOn Φ (Set.Icc (0 : ℝ) 1))
    (c : ℝ) (h k l m : Point n) : ∀ t ∈ (Set.Icc (0 : ℝ) 1),
    expJet4CurveG g gi hC p v Φ hv hΦcont h k (c • l) m t
      = c • expJet4CurveG g gi hC p v Φ hv hΦcont h k l m t := by
  intro t ht
  have hbridge := expJet4Curve_congr g gi hC p v Φ
      (expJet2Curve g gi hC p v Φ hv hΦcont h k)
      (expJet2Curve g gi hC p v Φ hv hΦcont h (c • l))
      (expJet2Curve g gi hC p v Φ hv hΦcont h m)
      (expJet2Curve g gi hC p v Φ hv hΦcont k (c • l))
      (expJet2Curve g gi hC p v Φ hv hΦcont k m)
      (expJet2Curve g gi hC p v Φ hv hΦcont (c • l) m)
      (expJet3CurveG g gi hC p v Φ hv hΦcont h k (c • l))
      (expJet3CurveG g gi hC p v Φ hv hΦcont h k m)
      (expJet3CurveG g gi hC p v Φ hv hΦcont h (c • l) m)
      (expJet3CurveG g gi hC p v Φ hv hΦcont k (c • l) m)
      (expJet2Curve g gi hC p v Φ hv hΦcont h k)
      ((fun s => c • expJet2Curve g gi hC p v Φ hv hΦcont h l s))
      (expJet2Curve g gi hC p v Φ hv hΦcont h m)
      ((fun s => c • expJet2Curve g gi hC p v Φ hv hΦcont k l s))
      (expJet2Curve g gi hC p v Φ hv hΦcont k m)
      ((fun s => c • expJet2Curve g gi hC p v Φ hv hΦcont l m s))
      ((fun s => c • expJet3CurveG g gi hC p v Φ hv hΦcont h k l s))
      (expJet3CurveG g gi hC p v Φ hv hΦcont h k m)
      ((fun s => c • expJet3CurveG g gi hC p v Φ hv hΦcont h l m s))
      ((fun s => c • expJet3CurveG g gi hC p v Φ hv hΦcont k l m s))
      hv hΦcont
      (expJet2Curve_continuousOn g gi hC p v Φ hv hΦcont h k)
      (expJet2Curve_continuousOn g gi hC p v Φ hv hΦcont h (c • l))
      (expJet2Curve_continuousOn g gi hC p v Φ hv hΦcont h m)
      (expJet2Curve_continuousOn g gi hC p v Φ hv hΦcont k (c • l))
      (expJet2Curve_continuousOn g gi hC p v Φ hv hΦcont k m)
      (expJet2Curve_continuousOn g gi hC p v Φ hv hΦcont (c • l) m)
      (expJet3CurveG_continuousOn g gi hC p v Φ hv hΦcont h k (c • l))
      (expJet3CurveG_continuousOn g gi hC p v Φ hv hΦcont h k m)
      (expJet3CurveG_continuousOn g gi hC p v Φ hv hΦcont h (c • l) m)
      (expJet3CurveG_continuousOn g gi hC p v Φ hv hΦcont k (c • l) m)
      (expJet2Curve_continuousOn g gi hC p v Φ hv hΦcont h k)
      (((expJet2Curve_continuousOn g gi hC p v Φ hv hΦcont h l).const_smul c))
      (expJet2Curve_continuousOn g gi hC p v Φ hv hΦcont h m)
      (((expJet2Curve_continuousOn g gi hC p v Φ hv hΦcont k l).const_smul c))
      (expJet2Curve_continuousOn g gi hC p v Φ hv hΦcont k m)
      (((expJet2Curve_continuousOn g gi hC p v Φ hv hΦcont l m).const_smul c))
      (((expJet3CurveG_continuousOn g gi hC p v Φ hv hΦcont h k l).const_smul c))
      (expJet3CurveG_continuousOn g gi hC p v Φ hv hΦcont h k m)
      (((expJet3CurveG_continuousOn g gi hC p v Φ hv hΦcont h l m).const_smul c))
      (((expJet3CurveG_continuousOn g gi hC p v Φ hv hΦcont k l m).const_smul c))
      h k (c • l) m
      ((fun _ _ => rfl))
      ((expJet2Curve_smul_right g gi hC p v Φ hv hΦcont c h l))
      ((fun _ _ => rfl))
      ((expJet2Curve_smul_right g gi hC p v Φ hv hΦcont c k l))
      ((fun _ _ => rfl))
      ((expJet2Curve_smul_left g gi hC p v Φ hv hΦcont c l m))
      ((expJet3CurveG_smul_l g gi hC p v Φ hv hΦcont c h k l))
      ((fun _ _ => rfl))
      ((expJet3CurveG_smul_k g gi hC p v Φ hv hΦcont c h l m))
      ((expJet3CurveG_smul_k g gi hC p v Φ hv hΦcont c k l m))
      t ht
  simp only [expJet4CurveG]
  rw [hbridge]
  exact expJet4Curve_smul_l g gi hC p v Φ
    (expJet2Curve g gi hC p v Φ hv hΦcont h k)
    (expJet2Curve g gi hC p v Φ hv hΦcont h l)
    (expJet2Curve g gi hC p v Φ hv hΦcont h m)
    (expJet2Curve g gi hC p v Φ hv hΦcont k l)
    (expJet2Curve g gi hC p v Φ hv hΦcont k m)
    (expJet2Curve g gi hC p v Φ hv hΦcont l m)
    (expJet3CurveG g gi hC p v Φ hv hΦcont h k l)
    (expJet3CurveG g gi hC p v Φ hv hΦcont h k m)
    (expJet3CurveG g gi hC p v Φ hv hΦcont h l m)
    (expJet3CurveG g gi hC p v Φ hv hΦcont k l m)
    hv hΦcont
    (expJet2Curve_continuousOn g gi hC p v Φ hv hΦcont h k)
    (expJet2Curve_continuousOn g gi hC p v Φ hv hΦcont h l)
    (expJet2Curve_continuousOn g gi hC p v Φ hv hΦcont h m)
    (expJet2Curve_continuousOn g gi hC p v Φ hv hΦcont k l)
    (expJet2Curve_continuousOn g gi hC p v Φ hv hΦcont k m)
    (expJet2Curve_continuousOn g gi hC p v Φ hv hΦcont l m)
    (expJet3CurveG_continuousOn g gi hC p v Φ hv hΦcont h k l)
    (expJet3CurveG_continuousOn g gi hC p v Φ hv hΦcont h k m)
    (expJet3CurveG_continuousOn g gi hC p v Φ hv hΦcont h l m)
    (expJet3CurveG_continuousOn g gi hC p v Φ hv hΦcont k l m)
    c h k l m t ht

theorem expJet4CurveG_add_m (g gi : Point n → Fin n → Fin n → ℝ)
    (hC : ∀ a b c, ContDiff ℝ (⊤ : WithTop ℕ∞) (fun y => christoffel g gi a b c y)) (p v : Point n)
    (Φ : ℝ → ((Point n × Point n) →L[ℝ] (Point n × Point n)))
    (hv : ‖v‖ ≤ expRho g gi hC p) (hΦcont : ContinuousOn Φ (Set.Icc (0 : ℝ) 1))
    (h k l m₁ m₂ : Point n) : ∀ t ∈ (Set.Icc (0 : ℝ) 1),
    expJet4CurveG g gi hC p v Φ hv hΦcont h k l (m₁ + m₂) t
      = expJet4CurveG g gi hC p v Φ hv hΦcont h k l m₁ t
        + expJet4CurveG g gi hC p v Φ hv hΦcont h k l m₂ t := by
  intro t ht
  have hbridge := expJet4Curve_congr g gi hC p v Φ
      (expJet2Curve g gi hC p v Φ hv hΦcont h k)
      (expJet2Curve g gi hC p v Φ hv hΦcont h l)
      (expJet2Curve g gi hC p v Φ hv hΦcont h (m₁ + m₂))
      (expJet2Curve g gi hC p v Φ hv hΦcont k l)
      (expJet2Curve g gi hC p v Φ hv hΦcont k (m₁ + m₂))
      (expJet2Curve g gi hC p v Φ hv hΦcont l (m₁ + m₂))
      (expJet3CurveG g gi hC p v Φ hv hΦcont h k l)
      (expJet3CurveG g gi hC p v Φ hv hΦcont h k (m₁ + m₂))
      (expJet3CurveG g gi hC p v Φ hv hΦcont h l (m₁ + m₂))
      (expJet3CurveG g gi hC p v Φ hv hΦcont k l (m₁ + m₂))
      (expJet2Curve g gi hC p v Φ hv hΦcont h k)
      (expJet2Curve g gi hC p v Φ hv hΦcont h l)
      ((fun s => expJet2Curve g gi hC p v Φ hv hΦcont h m₁ s + expJet2Curve g gi hC p v Φ hv hΦcont h m₂ s))
      (expJet2Curve g gi hC p v Φ hv hΦcont k l)
      ((fun s => expJet2Curve g gi hC p v Φ hv hΦcont k m₁ s + expJet2Curve g gi hC p v Φ hv hΦcont k m₂ s))
      ((fun s => expJet2Curve g gi hC p v Φ hv hΦcont l m₁ s + expJet2Curve g gi hC p v Φ hv hΦcont l m₂ s))
      (expJet3CurveG g gi hC p v Φ hv hΦcont h k l)
      ((fun s => expJet3CurveG g gi hC p v Φ hv hΦcont h k m₁ s + expJet3CurveG g gi hC p v Φ hv hΦcont h k m₂ s))
      ((fun s => expJet3CurveG g gi hC p v Φ hv hΦcont h l m₁ s + expJet3CurveG g gi hC p v Φ hv hΦcont h l m₂ s))
      ((fun s => expJet3CurveG g gi hC p v Φ hv hΦcont k l m₁ s + expJet3CurveG g gi hC p v Φ hv hΦcont k l m₂ s))
      hv hΦcont
      (expJet2Curve_continuousOn g gi hC p v Φ hv hΦcont h k)
      (expJet2Curve_continuousOn g gi hC p v Φ hv hΦcont h l)
      (expJet2Curve_continuousOn g gi hC p v Φ hv hΦcont h (m₁ + m₂))
      (expJet2Curve_continuousOn g gi hC p v Φ hv hΦcont k l)
      (expJet2Curve_continuousOn g gi hC p v Φ hv hΦcont k (m₁ + m₂))
      (expJet2Curve_continuousOn g gi hC p v Φ hv hΦcont l (m₁ + m₂))
      (expJet3CurveG_continuousOn g gi hC p v Φ hv hΦcont h k l)
      (expJet3CurveG_continuousOn g gi hC p v Φ hv hΦcont h k (m₁ + m₂))
      (expJet3CurveG_continuousOn g gi hC p v Φ hv hΦcont h l (m₁ + m₂))
      (expJet3CurveG_continuousOn g gi hC p v Φ hv hΦcont k l (m₁ + m₂))
      (expJet2Curve_continuousOn g gi hC p v Φ hv hΦcont h k)
      (expJet2Curve_continuousOn g gi hC p v Φ hv hΦcont h l)
      (((expJet2Curve_continuousOn g gi hC p v Φ hv hΦcont h m₁).add (expJet2Curve_continuousOn g gi hC p v Φ hv hΦcont h m₂)))
      (expJet2Curve_continuousOn g gi hC p v Φ hv hΦcont k l)
      (((expJet2Curve_continuousOn g gi hC p v Φ hv hΦcont k m₁).add (expJet2Curve_continuousOn g gi hC p v Φ hv hΦcont k m₂)))
      (((expJet2Curve_continuousOn g gi hC p v Φ hv hΦcont l m₁).add (expJet2Curve_continuousOn g gi hC p v Φ hv hΦcont l m₂)))
      (expJet3CurveG_continuousOn g gi hC p v Φ hv hΦcont h k l)
      (((expJet3CurveG_continuousOn g gi hC p v Φ hv hΦcont h k m₁).add (expJet3CurveG_continuousOn g gi hC p v Φ hv hΦcont h k m₂)))
      (((expJet3CurveG_continuousOn g gi hC p v Φ hv hΦcont h l m₁).add (expJet3CurveG_continuousOn g gi hC p v Φ hv hΦcont h l m₂)))
      (((expJet3CurveG_continuousOn g gi hC p v Φ hv hΦcont k l m₁).add (expJet3CurveG_continuousOn g gi hC p v Φ hv hΦcont k l m₂)))
      h k l (m₁ + m₂)
      ((fun _ _ => rfl))
      ((fun _ _ => rfl))
      ((expJet2Curve_add_right g gi hC p v Φ hv hΦcont h m₁ m₂))
      ((fun _ _ => rfl))
      ((expJet2Curve_add_right g gi hC p v Φ hv hΦcont k m₁ m₂))
      ((expJet2Curve_add_right g gi hC p v Φ hv hΦcont l m₁ m₂))
      ((fun _ _ => rfl))
      ((expJet3CurveG_add_l g gi hC p v Φ hv hΦcont h k m₁ m₂))
      ((expJet3CurveG_add_l g gi hC p v Φ hv hΦcont h l m₁ m₂))
      ((expJet3CurveG_add_l g gi hC p v Φ hv hΦcont k l m₁ m₂))
      t ht
  simp only [expJet4CurveG]
  rw [hbridge]
  exact expJet4Curve_add_m g gi hC p v Φ
    (expJet2Curve g gi hC p v Φ hv hΦcont h k)
    (expJet2Curve g gi hC p v Φ hv hΦcont h l)
    (expJet2Curve g gi hC p v Φ hv hΦcont h m₁)
    (expJet2Curve g gi hC p v Φ hv hΦcont h m₂)
    (expJet2Curve g gi hC p v Φ hv hΦcont k l)
    (expJet2Curve g gi hC p v Φ hv hΦcont k m₁)
    (expJet2Curve g gi hC p v Φ hv hΦcont k m₂)
    (expJet2Curve g gi hC p v Φ hv hΦcont l m₁)
    (expJet2Curve g gi hC p v Φ hv hΦcont l m₂)
    (expJet3CurveG g gi hC p v Φ hv hΦcont h k l)
    (expJet3CurveG g gi hC p v Φ hv hΦcont h k m₁)
    (expJet3CurveG g gi hC p v Φ hv hΦcont h k m₂)
    (expJet3CurveG g gi hC p v Φ hv hΦcont h l m₁)
    (expJet3CurveG g gi hC p v Φ hv hΦcont h l m₂)
    (expJet3CurveG g gi hC p v Φ hv hΦcont k l m₁)
    (expJet3CurveG g gi hC p v Φ hv hΦcont k l m₂)
    hv hΦcont
    (expJet2Curve_continuousOn g gi hC p v Φ hv hΦcont h k)
    (expJet2Curve_continuousOn g gi hC p v Φ hv hΦcont h l)
    (expJet2Curve_continuousOn g gi hC p v Φ hv hΦcont h m₁)
    (expJet2Curve_continuousOn g gi hC p v Φ hv hΦcont h m₂)
    (expJet2Curve_continuousOn g gi hC p v Φ hv hΦcont k l)
    (expJet2Curve_continuousOn g gi hC p v Φ hv hΦcont k m₁)
    (expJet2Curve_continuousOn g gi hC p v Φ hv hΦcont k m₂)
    (expJet2Curve_continuousOn g gi hC p v Φ hv hΦcont l m₁)
    (expJet2Curve_continuousOn g gi hC p v Φ hv hΦcont l m₂)
    (expJet3CurveG_continuousOn g gi hC p v Φ hv hΦcont h k l)
    (expJet3CurveG_continuousOn g gi hC p v Φ hv hΦcont h k m₁)
    (expJet3CurveG_continuousOn g gi hC p v Φ hv hΦcont h k m₂)
    (expJet3CurveG_continuousOn g gi hC p v Φ hv hΦcont h l m₁)
    (expJet3CurveG_continuousOn g gi hC p v Φ hv hΦcont h l m₂)
    (expJet3CurveG_continuousOn g gi hC p v Φ hv hΦcont k l m₁)
    (expJet3CurveG_continuousOn g gi hC p v Φ hv hΦcont k l m₂)
    h k l m₁ m₂ t ht

theorem expJet4CurveG_smul_m (g gi : Point n → Fin n → Fin n → ℝ)
    (hC : ∀ a b c, ContDiff ℝ (⊤ : WithTop ℕ∞) (fun y => christoffel g gi a b c y)) (p v : Point n)
    (Φ : ℝ → ((Point n × Point n) →L[ℝ] (Point n × Point n)))
    (hv : ‖v‖ ≤ expRho g gi hC p) (hΦcont : ContinuousOn Φ (Set.Icc (0 : ℝ) 1))
    (c : ℝ) (h k l m : Point n) : ∀ t ∈ (Set.Icc (0 : ℝ) 1),
    expJet4CurveG g gi hC p v Φ hv hΦcont h k l (c • m) t
      = c • expJet4CurveG g gi hC p v Φ hv hΦcont h k l m t := by
  intro t ht
  have hbridge := expJet4Curve_congr g gi hC p v Φ
      (expJet2Curve g gi hC p v Φ hv hΦcont h k)
      (expJet2Curve g gi hC p v Φ hv hΦcont h l)
      (expJet2Curve g gi hC p v Φ hv hΦcont h (c • m))
      (expJet2Curve g gi hC p v Φ hv hΦcont k l)
      (expJet2Curve g gi hC p v Φ hv hΦcont k (c • m))
      (expJet2Curve g gi hC p v Φ hv hΦcont l (c • m))
      (expJet3CurveG g gi hC p v Φ hv hΦcont h k l)
      (expJet3CurveG g gi hC p v Φ hv hΦcont h k (c • m))
      (expJet3CurveG g gi hC p v Φ hv hΦcont h l (c • m))
      (expJet3CurveG g gi hC p v Φ hv hΦcont k l (c • m))
      (expJet2Curve g gi hC p v Φ hv hΦcont h k)
      (expJet2Curve g gi hC p v Φ hv hΦcont h l)
      ((fun s => c • expJet2Curve g gi hC p v Φ hv hΦcont h m s))
      (expJet2Curve g gi hC p v Φ hv hΦcont k l)
      ((fun s => c • expJet2Curve g gi hC p v Φ hv hΦcont k m s))
      ((fun s => c • expJet2Curve g gi hC p v Φ hv hΦcont l m s))
      (expJet3CurveG g gi hC p v Φ hv hΦcont h k l)
      ((fun s => c • expJet3CurveG g gi hC p v Φ hv hΦcont h k m s))
      ((fun s => c • expJet3CurveG g gi hC p v Φ hv hΦcont h l m s))
      ((fun s => c • expJet3CurveG g gi hC p v Φ hv hΦcont k l m s))
      hv hΦcont
      (expJet2Curve_continuousOn g gi hC p v Φ hv hΦcont h k)
      (expJet2Curve_continuousOn g gi hC p v Φ hv hΦcont h l)
      (expJet2Curve_continuousOn g gi hC p v Φ hv hΦcont h (c • m))
      (expJet2Curve_continuousOn g gi hC p v Φ hv hΦcont k l)
      (expJet2Curve_continuousOn g gi hC p v Φ hv hΦcont k (c • m))
      (expJet2Curve_continuousOn g gi hC p v Φ hv hΦcont l (c • m))
      (expJet3CurveG_continuousOn g gi hC p v Φ hv hΦcont h k l)
      (expJet3CurveG_continuousOn g gi hC p v Φ hv hΦcont h k (c • m))
      (expJet3CurveG_continuousOn g gi hC p v Φ hv hΦcont h l (c • m))
      (expJet3CurveG_continuousOn g gi hC p v Φ hv hΦcont k l (c • m))
      (expJet2Curve_continuousOn g gi hC p v Φ hv hΦcont h k)
      (expJet2Curve_continuousOn g gi hC p v Φ hv hΦcont h l)
      (((expJet2Curve_continuousOn g gi hC p v Φ hv hΦcont h m).const_smul c))
      (expJet2Curve_continuousOn g gi hC p v Φ hv hΦcont k l)
      (((expJet2Curve_continuousOn g gi hC p v Φ hv hΦcont k m).const_smul c))
      (((expJet2Curve_continuousOn g gi hC p v Φ hv hΦcont l m).const_smul c))
      (expJet3CurveG_continuousOn g gi hC p v Φ hv hΦcont h k l)
      (((expJet3CurveG_continuousOn g gi hC p v Φ hv hΦcont h k m).const_smul c))
      (((expJet3CurveG_continuousOn g gi hC p v Φ hv hΦcont h l m).const_smul c))
      (((expJet3CurveG_continuousOn g gi hC p v Φ hv hΦcont k l m).const_smul c))
      h k l (c • m)
      ((fun _ _ => rfl))
      ((fun _ _ => rfl))
      ((expJet2Curve_smul_right g gi hC p v Φ hv hΦcont c h m))
      ((fun _ _ => rfl))
      ((expJet2Curve_smul_right g gi hC p v Φ hv hΦcont c k m))
      ((expJet2Curve_smul_right g gi hC p v Φ hv hΦcont c l m))
      ((fun _ _ => rfl))
      ((expJet3CurveG_smul_l g gi hC p v Φ hv hΦcont c h k m))
      ((expJet3CurveG_smul_l g gi hC p v Φ hv hΦcont c h l m))
      ((expJet3CurveG_smul_l g gi hC p v Φ hv hΦcont c k l m))
      t ht
  simp only [expJet4CurveG]
  rw [hbridge]
  exact expJet4Curve_smul_m g gi hC p v Φ
    (expJet2Curve g gi hC p v Φ hv hΦcont h k)
    (expJet2Curve g gi hC p v Φ hv hΦcont h l)
    (expJet2Curve g gi hC p v Φ hv hΦcont h m)
    (expJet2Curve g gi hC p v Φ hv hΦcont k l)
    (expJet2Curve g gi hC p v Φ hv hΦcont k m)
    (expJet2Curve g gi hC p v Φ hv hΦcont l m)
    (expJet3CurveG g gi hC p v Φ hv hΦcont h k l)
    (expJet3CurveG g gi hC p v Φ hv hΦcont h k m)
    (expJet3CurveG g gi hC p v Φ hv hΦcont h l m)
    (expJet3CurveG g gi hC p v Φ hv hΦcont k l m)
    hv hΦcont
    (expJet2Curve_continuousOn g gi hC p v Φ hv hΦcont h k)
    (expJet2Curve_continuousOn g gi hC p v Φ hv hΦcont h l)
    (expJet2Curve_continuousOn g gi hC p v Φ hv hΦcont h m)
    (expJet2Curve_continuousOn g gi hC p v Φ hv hΦcont k l)
    (expJet2Curve_continuousOn g gi hC p v Φ hv hΦcont k m)
    (expJet2Curve_continuousOn g gi hC p v Φ hv hΦcont l m)
    (expJet3CurveG_continuousOn g gi hC p v Φ hv hΦcont h k l)
    (expJet3CurveG_continuousOn g gi hC p v Φ hv hΦcont h k m)
    (expJet3CurveG_continuousOn g gi hC p v Φ hv hΦcont h l m)
    (expJet3CurveG_continuousOn g gi hC p v Φ hv hΦcont k l m)
    c h k l m t ht

end QIQTH.ExpMap
