/-
  InterchangeLocalRebase — J4-206: the tsum/heatConv INTERCHANGE re-proved under the `(0,T]`-LOCAL
  bound family (Sol final plan Phase 3, docs/qg_roadmap/JET4_TOWER_PLAN.md, "SOL CONSULT #3").

  ══════════════════════════════════════════════════════════════════════════════════════════════
  ⚠  HONEST FIREWALL.  THIS IS NOT `a₁ = R/6`, and proves NOTHING about `R/6`.  It is a re-plumbing
  of the ALREADY-BANKED tsum/heatConv interchange `hInter` so its bound hypothesis matches the
  provider actually available downstream.

  ══════════════════════════════════════════════════════════════════════════════════════════════
  THE PROBLEM (J4-203 slot mismatch).  The banked `LeviInterchange.heatConv_leviSeries_interchange`
  demands a GLOBAL-in-`τ` fixed-`C` one-step bound `∀ τ, 0 < τ → |E τ p q| ≤ C·baseKernelW 2 0 τ p q`.
  But every downstream provider (the `gatedWitnessN1_package_open` residual, J4-197/203/204) only
  hands over the `(0,T]`-LOCAL family `∀ τ, 0 < τ → τ ≤ T → |E τ p q| ≤ C·baseKernelW 2 0 τ p q`
  (with `C = C₀·(1+T)` the fixed window constant).

  SOL'S VERDICT.  "The fixed global constant is an API artifact, not a mathematical requirement —
  every temporal argument generated by the convolution is `s` or `T−s` with `0 < s < T`, both in
  `(0,T]`.  Re-prove under the local hypothesis; recover the global theorem as a corollary."

  ══════════════════════════════════════════════════════════════════════════════════════════════
  WHERE THE GLOBAL BOUND ENTERED THE BANKED PROOF (and how the localization works).

    (1) `hInt : IterConvIntegrableW E 2 0 C` (the ALL-outer-time integrability family).  This is the
        ONE genuinely all-time object — but it is NOT re-derived here from a global bound: it is
        CONSUMED from the `LeviSeriesLocalData E C T` package (J4-205), which itself builds it from the
        LOCAL bound + the `hglobal` every-ceiling family via the `timeCap` producer
        (`iterConvIntegrableW_of_locally_bound_baseMeas`).  So the "global" object is already the
        package's job — the interchange proof only ever CONSUMES it at the outer time `t ≤ T`.

    (2) The iterated domination `dom : |iterE E (k+1) τ| ≤ C^(k+1)·iterKernelW 2 0 (k+1) τ` and the
        raw one-step bound on `E` — both used ONLY at temporal arguments `s` and `t−s` for
        `0 < s < t ≤ T`, hence `s ≤ T` and `t − s ≤ T`.  Localized to `data.hmajor` (the `(0,T]`
        Volterra majorant) and its `k = 0` case (the raw `E` bound via `iterE_one`/`iterKernelW_one`).

  The interchange CORE (the double `integral_tsum_of_summable_integral_norm`, the model closed forms,
  the summabilities) is UNCHANGED — only the bound-plumbing localizes.  No genuine load-bearing global
  use of the bound survives inside the interchange proof; the all-time `IterConvIntegrableW` is
  supplied by the package (built from the local data).

  ══════════════════════════════════════════════════════════════════════════════════════════════
  WHAT LANDS HERE.
    • `heatConv_leviSeries_interchange_local` — the interchange from a `LeviSeriesLocalData E C T`
      package, at any `t` with `0 < t ≤ T`.
    • `heatConv_leviSeries_interchange_global'` — the banked GLOBAL statement re-derived from the
      local theorem (Sol's "one proof, two interfaces").
    • `hInter_from_local_data` — the exact `hInter` slot provider: from the `(0,T]` local bound +
      `hEzero` + `hEmeas` (the honest carry) + the `hglobal` every-ceiling family, produce the
      interchange conclusion (build the package, apply the local theorem).

  NO `sorry`.  NO new axioms.  NOT `a₁ = R/6`.  The one honest carry is `hEmeas` (base joint strong
  measurability of the residual) — everything else is a genuine derived fact of the actual residual.
-/
import Mathlib
import QIQTH.TrueHeatKernel
import QIQTH.LeviSeries
import QIQTH.HeatDuhamel
import QIQTH.ParametrixHEboundWiring
import QIQTH.IterEMeasurable
import QIQTH.ModelIntegrableW
import QIQTH.LeviSeriesLocalData

open MeasureTheory
open QIQTH.Curvature QIQTH.FlatHeatEquation QIQTH.GaussianConvolution
open QIQTH.HeatDuhamel QIQTH.LeviSeries QIQTH.TrueHeatKernel QIQTH.GaussianWidthTolerant
open QIQTH.HeatResidualBound QIQTH.LeviSeriesLocalData

namespace QIQTH.InterchangeLocalRebase

variable {n : ℕ}

set_option maxHeartbeats 3200000

/-! ###############################################################################
    ### 1. THE LOCAL INTERCHANGE THEOREM (mirrors the banked proof; bound localized).
    ############################################################################### -/

/-- **★ THE tsum/heatConv INTERCHANGE, RE-PROVED FROM THE `(0,T]`-LOCAL DATA.**  For the shared
    `(0,T]`-window package `LeviSeriesLocalData E C T` (J4-205), at ANY convolution time `t` with
    `0 < t ≤ T`, the space-time convolution `heatConv E (·)` commutes with the infinite (Levi/Neumann)
    sum:
        `heatConv E (leviSeries E) t x y
           = ∑' k, heatConv E (fun τ p q => (-1)^(k+1)·iterE E (k+1) τ p q) t x y`.
    Mirror of `LeviInterchange.heatConv_leviSeries_interchange`, EXCEPT the one-step / iterated bounds
    are taken from the package's `(0,T]` fields (`hmajor`, its `k = 0` case for the raw `E` bound) and
    the all-outer-time `IterConvIntegrableW` is CONSUMED (`data.hInt`) rather than rebuilt from a
    global bound.  Every temporal argument (`s`, `t−s`, `0 < s < t ≤ T`) lies in `(0,T]`, so the local
    bounds suffice — Sol's Phase-3 point.  NOT `a₁ = R/6`. -/
theorem heatConv_leviSeries_interchange_local
    (E : ℝ → Point n → Point n → ℝ) (C T : ℝ)
    (data : LeviSeriesLocalData E C T)
    (t : ℝ) (ht : 0 < t) (htT : t ≤ T) (x y : Point n) :
    heatConv E (leviSeries E) t x y
      = ∑' k : ℕ, heatConv E (fun τ p q => (-1 : ℝ) ^ (k + 1) * iterE E (k + 1) τ p q) t x y := by
  -- ── The package fields (consumed, not rebuilt). ─────────────────────────────────────────────
  have hC : 0 ≤ C := data.hC
  have hEmeas : StronglyMeasurable (fun q : ℝ × Point n × Point n => E q.1 q.2.1 q.2.2) :=
    data.hEmeas
  have hInt : IterConvIntegrableW E (2 : ℝ) (0 : ℝ) C := data.hInt
  -- The `(0,T]` iterated Volterra majorant (localized `dom`).
  have dom : ∀ (k : ℕ) (τ : ℝ), 0 < τ → τ ≤ T → ∀ (p q : Point n),
      |iterE E (k + 1) τ p q| ≤ C ^ (k + 1) * iterKernelW (2 : ℝ) (0 : ℝ) (k + 1) τ p q :=
    fun k τ hτ hτT p q => data.hmajor k τ p q hτ hτT
  -- The raw one-step `E` bound on `(0,T]` = the `k = 0` case of `hmajor`.
  have hEbnd : ∀ τ p q, 0 < τ → τ ≤ T → |E τ p q| ≤ C * baseKernelW (2 : ℝ) (0 : ℝ) τ p q := by
    intro τ p q hτ hτT
    have h := data.hmajor 0 τ p q hτ hτT
    simpa only [zero_add, iterE_one, pow_one, iterKernelW_one] using h
  have hE_zmeas : ∀ (τ : ℝ) (p : Point n),
      AEStronglyMeasurable (fun z : Point n => E τ p z) volume := by
    intro τ p
    exact (hEmeas.comp_measurable
      (measurable_const.prodMk (measurable_const.prodMk measurable_id))).aestronglyMeasurable
  -- The unit-modulus sign factor.
  have hsgn : ∀ m : ℕ, |(-1 : ℝ) ^ m| = 1 := fun m => by
    rw [abs_pow, abs_neg, abs_one, one_pow]
  -- ── The pointwise norm bound `‖E·(sign·iterE)‖ ≤ model`  (interior times). ───────────────────
  have hnormbd : ∀ (k : ℕ) (s : ℝ), 0 < s → s < t → ∀ z : Point n,
      ‖E (t - s) x z * ((-1 : ℝ) ^ (k + 1) * iterE E (k + 1) s z y)‖
        ≤ C * baseKernelW (2 : ℝ) (0 : ℝ) (t - s) x z
            * (C ^ (k + 1) * iterKernelW (2 : ℝ) (0 : ℝ) (k + 1) s z y) := by
    intro k s hs0 hst z
    have hts : 0 < t - s := by linarith
    have htsT : t - s ≤ T := by linarith
    have hsT : s ≤ T := by linarith
    rw [Real.norm_eq_abs, abs_mul, abs_mul, hsgn (k + 1), one_mul]
    have hEb := hEbnd (t - s) x z hts htsT
    have hIb := dom k s hs0 hsT z y
    calc |E (t - s) x z| * |iterE E (k + 1) s z y|
        ≤ (C * baseKernelW (2 : ℝ) (0 : ℝ) (t - s) x z)
            * (C ^ (k + 1) * iterKernelW (2 : ℝ) (0 : ℝ) (k + 1) s z y) :=
          mul_le_mul hEb hIb (abs_nonneg _) (le_trans (abs_nonneg _) hEb)
      _ = C * baseKernelW (2 : ℝ) (0 : ℝ) (t - s) x z
            * (C ^ (k + 1) * iterKernelW (2 : ℝ) (0 : ℝ) (k + 1) s z y) := by ring
  -- ── Per-`(k,s)` `z`-integrability of the actual signed integrand (interior times). ───────────
  have fkszInt : ∀ (k : ℕ) (s : ℝ), 0 < s → s < t →
      Integrable (fun z => E (t - s) x z * ((-1 : ℝ) ^ (k + 1) * iterE E (k + 1) s z y)) volume := by
    intro k s hs0 hst
    obtain ⟨_, _, _, hIg, _⟩ := hInt (k + 1) (by omega) t ht x y
    have hmeas : AEStronglyMeasurable
        (fun z => E (t - s) x z * ((-1 : ℝ) ^ (k + 1) * iterE E (k + 1) s z y)) volume :=
      (hE_zmeas (t - s) x).mul
        ((iterE_zmeas E hEmeas (k + 1) (by omega) s y).const_mul _)
    exact Integrable.mono' (hIg s) hmeas (ae_of_all _ (fun z => hnormbd k s hs0 hst z))
  -- ── The model `z`-integral closed form (interior times). ─────────────────────────────────────
  have hDzeq : ∀ (k : ℕ) (s : ℝ), 0 < s → s < t →
      (∫ z, C * baseKernelW (2 : ℝ) (0 : ℝ) (t - s) x z
              * (C ^ (k + 1) * iterKernelW (2 : ℝ) (0 : ℝ) (k + 1) s z y))
        = (C * gaussDdim (2 * t) (x - y)) * (C ^ (k + 1) * modelCoeff 0 s (k + 1)) := by
    intro k s hs0 hst
    have hts : 0 < t - s := by linarith
    have hform : (fun z => C * baseKernelW (2 : ℝ) (0 : ℝ) (t - s) x z
              * (C ^ (k + 1) * iterKernelW (2 : ℝ) (0 : ℝ) (k + 1) s z y))
        = fun z => (C * C ^ (k + 1)
              * (Real.Gamma (0 + 1) ^ (k + 1) / Real.Gamma (((k + 1 : ℕ) : ℝ) * (0 + 1)))
              * s ^ (((k + 1 : ℕ) : ℝ) * (0 + 1) - 1))
            * (gaussDdim (2 * (t - s)) (x - z) * gaussDdim (2 * s) (z - y)) := by
      funext z
      rw [baseKernelW_zero_apply,
          iterKernelW_eq (2 : ℝ) (0 : ℝ) (by norm_num) (by norm_num) s hs0 z y (by omega : 1 ≤ k + 1)]
      ring
    rw [hform, integral_const_mul,
        gaussDdim_conv (2 * (t - s)) (2 * s) (by linarith) (by linarith) x y,
        show 2 * (t - s) + 2 * s = 2 * t from by ring]
    unfold modelCoeff
    ring
  -- ── INNER interchange (fixed interior `s`): pull `∑'` out of `∫z`. ────────────────────────────
  have inner : ∀ s, 0 < s → s < t →
      (∫ z, E (t - s) x z * (∑' k : ℕ, (-1 : ℝ) ^ (k + 1) * iterE E (k + 1) s z y))
        = ∑' k : ℕ, ∫ z, E (t - s) x z * ((-1 : ℝ) ^ (k + 1) * iterE E (k + 1) s z y) := by
    intro s hs0 hst
    -- (a) move the constant `E(t−s)x z` inside the `∑'`.
    rw [integral_congr_ae (Filter.Eventually.of_forall (fun z =>
      (tsum_mul_left (f := fun k : ℕ => (-1 : ℝ) ^ (k + 1) * iterE E (k + 1) s z y)
        (a := E (t - s) x z)).symm))]
    -- (b) per-`k` integrability of the (signed) integrand.
    have hFint : ∀ k, Integrable
        (fun z => E (t - s) x z * ((-1 : ℝ) ^ (k + 1) * iterE E (k + 1) s z y)) volume :=
      fun k => fkszInt k s hs0 hst
    -- (c) summability of `∫z ‖·‖` via the model bound.
    have hFsum : Summable
        (fun k => ∫ z, ‖E (t - s) x z * ((-1 : ℝ) ^ (k + 1) * iterE E (k + 1) s z y)‖) := by
      have hDzsum : Summable
          (fun k => (C * gaussDdim (2 * t) (x - y)) * (C ^ (k + 1) * modelCoeff 0 s (k + 1))) :=
        (scaledModelCoeff_summable 0 s C le_rfl hs0 hC).mul_left _
      refine Summable.of_nonneg_of_le
        (fun k => integral_nonneg (fun z => norm_nonneg _)) (fun k => ?_) hDzsum
      obtain ⟨_, _, _, hIg, _⟩ := hInt (k + 1) (by omega) t ht x y
      calc ∫ z, ‖E (t - s) x z * ((-1 : ℝ) ^ (k + 1) * iterE E (k + 1) s z y)‖
          ≤ ∫ z, C * baseKernelW (2 : ℝ) (0 : ℝ) (t - s) x z
                * (C ^ (k + 1) * iterKernelW (2 : ℝ) (0 : ℝ) (k + 1) s z y) :=
            integral_mono (hFint k).norm (hIg s) (fun z => hnormbd k s hs0 hst z)
        _ = (C * gaussDdim (2 * t) (x - y)) * (C ^ (k + 1) * modelCoeff 0 s (k + 1)) :=
            hDzeq k s hs0 hst
    exact (integral_tsum_of_summable_integral_norm hFint hFsum).symm
  -- ── The signed `s`-integrand as a scalar multiple of the unsigned convolution. ───────────────
  have gk_eq : ∀ k,
      (fun s => ∫ z, E (t - s) x z * ((-1 : ℝ) ^ (k + 1) * iterE E (k + 1) s z y))
        = (fun s => (-1 : ℝ) ^ (k + 1) * ∫ z, E (t - s) x z * iterE E (k + 1) s z y) := by
    intro k; funext s
    rw [integral_congr_ae (Filter.Eventually.of_forall (fun z =>
        show E (t - s) x z * ((-1 : ℝ) ^ (k + 1) * iterE E (k + 1) s z y)
              = (-1 : ℝ) ^ (k + 1) * (E (t - s) x z * iterE E (k + 1) s z y) from by ring)),
        integral_const_mul]
  -- ── OUTER `hF_int`: `Integrable (g k) (volume.restrict (Ioc 0 t))`. ──────────────────────────
  have gkInt : ∀ k, Integrable
      (fun s => ∫ z, E (t - s) x z * ((-1 : ℝ) ^ (k + 1) * iterE E (k + 1) s z y))
      (volume.restrict (Set.Ioc 0 t)) := by
    intro k
    rw [gk_eq k]
    obtain ⟨hI1, _, _, _, _⟩ := hInt (k + 1) (by omega) t ht x y
    have hnormOn : Integrable
        (fun s => ‖∫ z, E (t - s) x z * iterE E (k + 1) s z y‖) (volume.restrict (Set.Ioc 0 t)) :=
      (intervalIntegrable_iff_integrableOn_Ioc_of_le ht.le).mp hI1
    have hsig : AEStronglyMeasurable
        (fun s => ∫ z, E (t - s) x z * iterE E (k + 1) s z y) (volume.restrict (Set.Ioc 0 t)) := by
      have hjoint := conv_meas E hEmeas (k + 1) (by omega) t ht x y
      simpa only [Function.uncurry_apply_pair] using hjoint.integral_prod_right'
    exact (Integrable.mono' hnormOn hsig (ae_of_all _ (fun s => le_refl _))).const_mul _
  -- ── OUTER `hF_sum`: summability of `∫s ‖g k s‖`  via the model. ──────────────────────────────
  have gkSum : Summable
      (fun k => ∫ s, ‖∫ z, E (t - s) x z * ((-1 : ℝ) ^ (k + 1) * iterE E (k + 1) s z y)‖
        ∂(volume.restrict (Set.Ioc 0 t))) := by
    have hDssum : Summable (fun k => C ^ (k + 2) * iterKernelW (2 : ℝ) (0 : ℝ) (k + 2) t x y) := by
      have h := scaledIterKernelW_summable (2 : ℝ) (0 : ℝ) t C (by norm_num) le_rfl ht hC x y
      simpa [Function.comp] using h.comp_injective Nat.succ_injective
    refine Summable.of_nonneg_of_le
      (fun k => integral_nonneg (fun s => norm_nonneg _)) (fun k => ?_) hDssum
    obtain ⟨_, _, _, _, hIsg⟩ := hInt (k + 1) (by omega) t ht x y
    -- The model `s`-integrand is integrable on `Ioc 0 t`.
    have hDzOn : Integrable
        (fun s => ∫ z, C * baseKernelW (2 : ℝ) (0 : ℝ) (t - s) x z
          * (C ^ (k + 1) * iterKernelW (2 : ℝ) (0 : ℝ) (k + 1) s z y))
        (volume.restrict (Set.Ioc 0 t)) :=
      (intervalIntegrable_iff_integrableOn_Ioc_of_le ht.le).mp hIsg
    -- The a.e. pointwise bound `‖g k s‖ ≤ ∫z model`.
    have hbnd : (fun s => ‖∫ z, E (t - s) x z * ((-1 : ℝ) ^ (k + 1) * iterE E (k + 1) s z y)‖)
        ≤ᵐ[volume.restrict (Set.Ioc 0 t)]
        (fun s => ∫ z, C * baseKernelW (2 : ℝ) (0 : ℝ) (t - s) x z
          * (C ^ (k + 1) * iterKernelW (2 : ℝ) (0 : ℝ) (k + 1) s z y)) := by
      refine (ae_restrict_iff' measurableSet_Ioc).mpr ?_
      filter_upwards [compl_mem_ae_iff.mpr (show volume ({t} : Set ℝ) = 0 by simp)] with s hst
      intro hmem
      obtain ⟨hs0, hsle⟩ := hmem
      have hst2 : s < t := lt_of_le_of_ne hsle (by simpa using hst)
      calc ‖∫ z, E (t - s) x z * ((-1 : ℝ) ^ (k + 1) * iterE E (k + 1) s z y)‖
          ≤ ∫ z, ‖E (t - s) x z * ((-1 : ℝ) ^ (k + 1) * iterE E (k + 1) s z y)‖ :=
            norm_integral_le_integral_norm _
        _ ≤ ∫ z, C * baseKernelW (2 : ℝ) (0 : ℝ) (t - s) x z
              * (C ^ (k + 1) * iterKernelW (2 : ℝ) (0 : ℝ) (k + 1) s z y) :=
            integral_mono (fkszInt k s hs0 hst2).norm
              (by obtain ⟨_, _, _, hIg, _⟩ := hInt (k + 1) (by omega) t ht x y; exact hIg s)
              (fun z => hnormbd k s hs0 hst2 z)
    -- Integrate the bound, then evaluate the model integral in closed form.
    refine le_trans (integral_mono_ae (gkInt k).norm hDzOn hbnd) (le_of_eq ?_)
    -- `∫ s in Ioc, ∫z model = C^(k+2)·iterKernelW 2 0 (k+2) t x y`.
    have hconv : (∫ s, (∫ z, C * baseKernelW (2 : ℝ) (0 : ℝ) (t - s) x z
            * (C ^ (k + 1) * iterKernelW (2 : ℝ) (0 : ℝ) (k + 1) s z y))
          ∂(volume.restrict (Set.Ioc 0 t)))
        = ∫ s in (0 : ℝ)..t, ∫ z, C * baseKernelW (2 : ℝ) (0 : ℝ) (t - s) x z
            * (C ^ (k + 1) * iterKernelW (2 : ℝ) (0 : ℝ) (k + 1) s z y) :=
      (intervalIntegral.integral_of_le ht.le).symm
    rw [hconv]
    have hpull : ∀ s, (∫ z, C * baseKernelW (2 : ℝ) (0 : ℝ) (t - s) x z
              * (C ^ (k + 1) * iterKernelW (2 : ℝ) (0 : ℝ) (k + 1) s z y))
        = (C * C ^ (k + 1))
            * ∫ z, baseKernelW (2 : ℝ) (0 : ℝ) (t - s) x z
                * iterKernelW (2 : ℝ) (0 : ℝ) (k + 1) s z y := by
      intro s
      rw [← integral_const_mul]
      exact integral_congr_ae (ae_of_all _ (fun z => by ring))
    calc (∫ s in (0 : ℝ)..t, ∫ z, C * baseKernelW (2 : ℝ) (0 : ℝ) (t - s) x z
            * (C ^ (k + 1) * iterKernelW (2 : ℝ) (0 : ℝ) (k + 1) s z y))
        = ∫ s in (0 : ℝ)..t, (C * C ^ (k + 1))
            * ∫ z, baseKernelW (2 : ℝ) (0 : ℝ) (t - s) x z
                * iterKernelW (2 : ℝ) (0 : ℝ) (k + 1) s z y :=
          intervalIntegral.integral_congr (fun s _ => hpull s)
      _ = (C * C ^ (k + 1)) * ∫ s in (0 : ℝ)..t, ∫ z, baseKernelW (2 : ℝ) (0 : ℝ) (t - s) x z
                * iterKernelW (2 : ℝ) (0 : ℝ) (k + 1) s z y :=
          intervalIntegral.integral_const_mul _ _
      _ = (C * C ^ (k + 1))
            * heatConv (baseKernelW (2 : ℝ) (0 : ℝ)) (iterKernelW (2 : ℝ) (0 : ℝ) (k + 1)) t x y :=
          rfl
      _ = (C * C ^ (k + 1)) * iterKernelW (2 : ℝ) (0 : ℝ) (k + 2) t x y := by
          rw [show iterKernelW (2 : ℝ) (0 : ℝ) (k + 2)
                = heatConvK (baseKernelW (2 : ℝ) (0 : ℝ)) (iterKernelW (2 : ℝ) (0 : ℝ) (k + 1))
                from iterKernelW_succ (2 : ℝ) (0 : ℝ) (by omega : 1 ≤ k + 1)]
          rfl
      _ = C ^ (k + 2) * iterKernelW (2 : ℝ) (0 : ℝ) (k + 2) t x y := by ring
  -- ── ASSEMBLE the double interchange. ─────────────────────────────────────────────────────────
  simp only [heatConv, leviSeries]
  have hcongr : (∫ s in (0 : ℝ)..t,
        ∫ z, E (t - s) x z * (∑' k : ℕ, (-1 : ℝ) ^ (k + 1) * iterE E (k + 1) s z y))
      = ∫ s in (0 : ℝ)..t,
        ∑' k : ℕ, ∫ z, E (t - s) x z * ((-1 : ℝ) ^ (k + 1) * iterE E (k + 1) s z y) := by
    refine intervalIntegral.integral_congr_ae ?_
    filter_upwards [compl_mem_ae_iff.mpr (show volume ({t} : Set ℝ) = 0 by simp)] with s hst
    intro hmem
    rw [Set.uIoc_of_le ht.le] at hmem
    obtain ⟨hs0, hsle⟩ := hmem
    exact inner s hs0 (lt_of_le_of_ne hsle (by simpa using hst))
  calc (∫ s in (0 : ℝ)..t,
          ∫ z, E (t - s) x z * (∑' k : ℕ, (-1 : ℝ) ^ (k + 1) * iterE E (k + 1) s z y))
      = ∫ s in (0 : ℝ)..t,
          ∑' k : ℕ, ∫ z, E (t - s) x z * ((-1 : ℝ) ^ (k + 1) * iterE E (k + 1) s z y) := hcongr
    _ = ∫ s, (∑' k : ℕ, ∫ z, E (t - s) x z * ((-1 : ℝ) ^ (k + 1) * iterE E (k + 1) s z y))
          ∂(volume.restrict (Set.Ioc 0 t)) := intervalIntegral.integral_of_le ht.le
    _ = ∑' k : ℕ, ∫ s, (∫ z, E (t - s) x z * ((-1 : ℝ) ^ (k + 1) * iterE E (k + 1) s z y))
          ∂(volume.restrict (Set.Ioc 0 t)) :=
        (integral_tsum_of_summable_integral_norm gkInt gkSum).symm
    _ = ∑' k : ℕ, ∫ s in (0 : ℝ)..t,
          ∫ z, E (t - s) x z * ((-1 : ℝ) ^ (k + 1) * iterE E (k + 1) s z y) := by
        refine tsum_congr (fun k => ?_)
        exact (intervalIntegral.integral_of_le ht.le).symm

/-! ###############################################################################
    ### 2. THE GLOBAL COROLLARY (Sol's "one proof, two interfaces").
    ############################################################################### -/

/-- **★ THE BANKED GLOBAL STATEMENT, RE-DERIVED FROM THE LOCAL THEOREM.**  The exact statement of
    `LeviInterchange.heatConv_leviSeries_interchange`, recovered as a corollary: from a GLOBAL-in-`τ`
    fixed-`C` one-step bound `hEbound`, take the window `T := t` (so `hEbnd` and the `hglobal`
    every-ceiling family are both immediate from `hEbound` by dropping the `τ ≤ ·`), build the
    `LeviSeriesLocalData E C t` package (`leviSeriesLocalData_of_windowBound`), and apply the local
    theorem at `t ≤ t`.  One proof, two interfaces — the global bound is the API artifact.  NOT
    `a₁ = R/6`. -/
theorem heatConv_leviSeries_interchange_global'
    (E : ℝ → Point n → Point n → ℝ) (C : ℝ) (hC : 0 ≤ C)
    (hEbound : ∀ τ p q, 0 < τ → |E τ p q| ≤ C * baseKernelW (2 : ℝ) (0 : ℝ) τ p q)
    (hEzero : ∀ τ : ℝ, τ ≤ 0 → ∀ p q : Point n, E τ p q = 0)
    (hEmeas : StronglyMeasurable (fun q : ℝ × Point n × Point n => E q.1 q.2.1 q.2.2))
    (t : ℝ) (ht : 0 < t) (x y : Point n) :
    heatConv E (leviSeries E) t x y
      = ∑' k : ℕ, heatConv E (fun τ p q => (-1 : ℝ) ^ (k + 1) * iterE E (k + 1) τ p q) t x y := by
  have hEbnd : ∀ τ p q, 0 < τ → τ ≤ t → |E τ p q| ≤ C * baseKernelW (2 : ℝ) (0 : ℝ) τ p q :=
    fun τ p q hτ _ => hEbound τ p q hτ
  have hglobal : ∀ T' : ℝ, 0 < T' → ∃ CT : ℝ, 0 ≤ CT ∧
      ∀ τ p q, 0 < τ → τ ≤ T' → |E τ p q| ≤ CT * baseKernelW (2 : ℝ) (0 : ℝ) τ p q :=
    fun T' _ => ⟨C, hC, fun τ p q hτ _ => hEbound τ p q hτ⟩
  have data : LeviSeriesLocalData E C t :=
    leviSeriesLocalData_of_windowBound E C t hC ht hEbnd hEzero hEmeas hglobal
  exact heatConv_leviSeries_interchange_local E C t data t ht le_rfl x y

/-! ###############################################################################
    ### 3. THE `hInter` PROVIDER (exact v4 slot, from the `(0,T]` local bound + series data).
    ############################################################################### -/

/-- **★★ `hInter_from_local_data`.**  The exact `hInter` slot of
    `GateOpennessExport.a1_R6_of_residue_inf_v4`, produced from the residual's honest `(0,T]`-LOCAL
    inputs:

    * `hEbnd`   — the `(0,T]` fixed-constant one-step bound (the `gatedWitnessN1_package_open` output,
                  `C = C₀·(1+T)`; J4-197/203/204);
    * `hEzero`  — vanishing at nonpositive time;
    * `hEmeas`  — the base joint strong measurability (the HONEST named carry — Sol);
    * `hglobal` — the every-ceiling bound family (a genuine fact of the residual), which the package
                  builder needs to assemble the all-outer-time `IterConvIntegrableW`.

    Route: `leviSeriesLocalData_of_windowBound` assembles the `LeviSeriesLocalData E C T` package, then
    `heatConv_leviSeries_interchange_local` at `t ≤ T` supplies the interchange.  This CONVERTS the
    carried `hInter` of `a1_R6_of_residue_inf_v4` into the same `hEbnd`/`hEzero`/`hEmeas`/`hglobal`
    inputs the tower already runs on — `hEmeas` being the honest residue.  NOT `a₁ = R/6`. -/
theorem hInter_from_local_data
    (E : ℝ → Point n → Point n → ℝ) (C T : ℝ) (hC : 0 ≤ C) (hT : 0 < T)
    (hEbnd : ∀ τ p q, 0 < τ → τ ≤ T → |E τ p q| ≤ C * baseKernelW (2 : ℝ) (0 : ℝ) τ p q)
    (hEzero : ∀ τ : ℝ, τ ≤ 0 → ∀ p q : Point n, E τ p q = 0)
    (hEmeas : StronglyMeasurable (fun q : ℝ × Point n × Point n => E q.1 q.2.1 q.2.2))
    (hglobal : ∀ T' : ℝ, 0 < T' → ∃ CT : ℝ, 0 ≤ CT ∧
        ∀ τ p q, 0 < τ → τ ≤ T' → |E τ p q| ≤ CT * baseKernelW (2 : ℝ) (0 : ℝ) τ p q)
    (t : ℝ) (ht : 0 < t) (htT : t ≤ T) (x y : Point n) :
    heatConv E (leviSeries E) t x y
      = ∑' k : ℕ, heatConv E (fun τ p q => (-1 : ℝ) ^ (k + 1) * iterE E (k + 1) τ p q) t x y := by
  have data : LeviSeriesLocalData E C T :=
    leviSeriesLocalData_of_windowBound E C T hC hT hEbnd hEzero hEmeas hglobal
  exact heatConv_leviSeries_interchange_local E C T data t ht htT x y

end QIQTH.InterchangeLocalRebase

section AxiomChecks
open QIQTH.InterchangeLocalRebase
#print axioms heatConv_leviSeries_interchange_local
#print axioms heatConv_leviSeries_interchange_global'
#print axioms hInter_from_local_data
end AxiomChecks
