/-
  THE INTERACTING CHANNEL — einselection DERIVED: the pure-dephasing model whose
  time-averaged reduced dynamics IS the record channel (RC campaign, brick IC1).

  Brick RC1 (`RecordChannel.lean`) built the record channel and carried ONE named input —
  the pointer/record basis: the dephasing was IMPOSED in a chosen basis (its firewall said
  so explicitly).  THIS brick derives that input at the time-averaged level.  Couple the
  system `ι` to a finite environment `κ` through the pure-dephasing interaction

      `H_int = A ⊗ B`,   `A = diag a` (the monitored observable),  `B = diag b`,

  — the measurement limit (Zurek 1981/82, the exactly solvable einselection model) — with
  the environment in the diagonal state `ω = diag w`.  Proved here, axiom-free:

  • THE DYNAMICS — `intPhase` is the diagonal phase unitary `U_t = e^{−itH_int}` (defined
    directly by the entry formula, NO Stone theorem, NO matrix exponential — the house
    `Dynamics.lean` pattern), with `intPhase_zero`, the group law `intPhase_add`, unitarity
    `intPhase_mul_conjTranspose`/`intPhase_conjTranspose_mul`, and the genuine-calculus tie
    to the Hamiltonian: `intPhase_entry_hasDerivAt` — every entry solves the Schrödinger
    equation `U_t' = −i·H_int·U_t` (so `U_t = e^{−itH_int}` in the entrywise sense
    established by the derivative lemma).
  • THE EXACT REDUCED DYNAMICS — `reduced_entry`: the partial trace of the evolved joint
    state multiplies each coherence by the DECOHERENCE FACTOR
        `γ_{nm}(t) = Σ_k w_k·e^{−it(a_n − a_m)b_k}`,
    exactly (`reduced t ρ = [γ_{nm}(t)·ρ_{nm}]`).  The ledger is conserved BY THE
    INTERACTION (`reduced_diag`, `gamma_diag` — derived, not imposed; contrast RC1 where
    diagonal-freezing was built in), `‖γ_{nm}(t)‖ ≤ 1` (`gamma_norm_le_one`), the trace is
    preserved (`reduced_trace`, `joint_trace`), and positivity is preserved
    (`reduced_posSemidef` = Kronecker PSD + unitary conjugation + the held
    `partialTraceRight_posSemidef`).
  • THE EINSELECTION CAPSTONE — `timeAvg_reduced_tendsto_dephase`: under the
    GAPS-RESOLVED hypothesis (`(a_n − a_m)·b_k ≠ 0` for `n ≠ m`), the Cesàro time average
    `(1/T)∫₀ᵀ reduced t ρ dt` converges (entrywise, as `T → ∞`) to RC1's `dephase ρ` — the
    record channel EMERGES from the interaction: **the record basis is the eigenbasis of
    the monitored observable `A`, determined by the interaction Hamiltonian, not chosen.**
    The oscillatory-integral core is `cesaro_exp_tendsto` (closed-form FTC integral +
    squeeze), summed over the finite environment (`timeAvgGamma_tendsto_zero`).
  • EINSELECTION UNIQUENESS — `invariant_iff_record`: the states invariant under the
    interacting reduced dynamics at ALL times are EXACTLY the records (`dephase ρ = ρ`) —
    invariance forces the time average, the time average forces `dephase`.
  • THE NECESSITY GUARD — `no_resolution_no_einselection`: with a decoupled environment
    (`b ≡ 0`) NOTHING dephases (`reduced t ρ = ρ` for all `t, ρ`): the gaps-resolved
    hypothesis is load-bearing, machine-checked (the repo's guard-theorem house style).

  This grounds the entire RC tower (record semigroup RC1 → second law → E4 join →
  Born-jump unraveling RC3) on a DERIVED pointer basis, at the time-averaged level.

  ⚠ MANDATORY FIREWALL.  FINITE environment ⟹ RECURRENCES (the repo's own gate C,
  `QG/FiniteModularRecurrence.lean`, CITED): pointwise `t → ∞` dephasing is IMPOSSIBLE in
  finite dimensions — the honest derived statement is Cesàro/TIME-AVERAGED einselection
  (the finite-dimensional Zurek statement).  PURE-dephasing limit: the system's
  self-Hamiltonian is dropped — `[H_S, A] ≠ 0` pointer competition is a named follow-on,
  NOT treated here.  The environment spectrum `b`, environment state `w`, and the
  monitored observable `a` are model INPUTS: what is DERIVED is that the record basis =
  `A`'s eigenbasis — the basis comes from the coupling, not from RC1's fiat.  The
  coordinates are chosen in `A`'s eigenbasis (WLOG for a self-adjoint `A` — the
  diagonalization itself is standard spectral theory, not re-proved here).  Finite corner,
  single code; NOT bulk reconstruction, NOT the strong holographic principle, NOT quantum
  gravity.  No axioms, no `sorry`.
-/
import Mathlib
import QIQTH.RecordChannel
import QIQTH.Entropy.PartialTrace

namespace QIQTH.InteractingChannel

open QIQTH.Entropy QIQTH.RecordChannel
open scoped ComplexOrder Kronecker Matrix

set_option linter.unusedSectionVars false

variable {ι κ : Type*} [Fintype ι] [Fintype κ] [DecidableEq ι] [DecidableEq κ]
variable (a : ι → ℝ) (b : κ → ℝ) (w : κ → ℝ)

/-! ## IC1.1 — the interaction dynamics: the diagonal phase unitary `U_t = e^{−itH_int}` -/

/-- **The interaction phase unitary** `U_t = diag e^{−it·a_n·b_k}` — the time evolution
    generated by the pure-dephasing interaction `H_int = A ⊗ B` (`A = diag a` the monitored
    observable, `B = diag b` the environment coupling), defined directly by the entry
    formula (no Stone theorem, no matrix exponential — the house `Dynamics.lean`
    pattern).  The Hamiltonian tie is `intPhase_entry_hasDerivAt`. -/
noncomputable def intPhase (t : ℝ) : Matrix (ι × κ) (ι × κ) ℂ :=
  Matrix.diagonal fun p => Complex.exp ((-(t * a p.1 * b p.2) : ℝ) * Complex.I)

/-- Entry formula for the phase unitary. -/
theorem intPhase_apply (t : ℝ) (p q : ι × κ) :
    intPhase a b t p q
      = if p = q then Complex.exp ((-(t * a p.1 * b p.2) : ℝ) * Complex.I) else 0 := by
  rw [intPhase, Matrix.diagonal_apply]

/-- Diagonal entry of the phase unitary. -/
theorem intPhase_apply_eq (t : ℝ) (p : ι × κ) :
    intPhase a b t p p = Complex.exp ((-(t * a p.1 * b p.2) : ℝ) * Complex.I) := by
  rw [intPhase, Matrix.diagonal_apply_eq]

/-- `U_0 = 1`. -/
theorem intPhase_zero : intPhase a b 0 = 1 := by
  rw [intPhase,
    show (fun p : ι × κ => Complex.exp ((-((0 : ℝ) * a p.1 * b p.2) : ℝ) * Complex.I))
      = fun _ => (1 : ℂ) from funext fun p => by simp,
    Matrix.diagonal_one]

/-- **The group law** `U_{s+t} = U_s·U_t` (via `Complex.exp_add`). -/
theorem intPhase_add (s t : ℝ) :
    intPhase a b (s + t) = intPhase a b s * intPhase a b t := by
  rw [intPhase, intPhase, intPhase, Matrix.diagonal_mul_diagonal]
  congr 1
  funext p
  rw [← Complex.exp_add]
  congr 1
  push_cast
  ring

/-- The adjoint of the phase unitary is time reversal: `U_tᴴ = U_{−t}`. -/
theorem intPhase_conjTranspose (t : ℝ) : (intPhase a b t)ᴴ = intPhase a b (-t) := by
  rw [intPhase, intPhase, Matrix.diagonal_conjTranspose]
  congr 1
  funext p
  rw [Pi.star_apply, Complex.star_def, ← Complex.exp_conj]
  congr 1
  simp only [map_mul, Complex.conj_I, Complex.conj_ofReal]
  push_cast
  ring

/-- **Unitarity** (right): `U_t·U_tᴴ = 1` — conjugate diagonal phases cancel. -/
theorem intPhase_mul_conjTranspose (t : ℝ) :
    intPhase a b t * (intPhase a b t)ᴴ = 1 := by
  rw [intPhase_conjTranspose, ← intPhase_add, add_neg_cancel, intPhase_zero]

/-- **Unitarity** (left): `U_tᴴ·U_t = 1`. -/
theorem intPhase_conjTranspose_mul (t : ℝ) :
    (intPhase a b t)ᴴ * intPhase a b t = 1 := by
  rw [intPhase_conjTranspose, ← intPhase_add, neg_add_cancel, intPhase_zero]

/-- **The interaction Hamiltonian** `H_int = A ⊗ B = diag (a_n·b_k)` — the pure-dephasing
    (measurement-limit) coupling of the system to the environment.  Its eigenbasis in the
    system factor IS the eigenbasis of the monitored observable `A = diag a`: this is the
    basis that will be EINSELECTED below. -/
noncomputable def Hint : Matrix (ι × κ) (ι × κ) ℂ :=
  Matrix.diagonal fun p => ((a p.1 * b p.2 : ℝ) : ℂ)

/-- The interaction Hamiltonian is Hermitian (a real diagonal). -/
theorem Hint_isHermitian : (Hint a b).IsHermitian := by
  show (Hint a b)ᴴ = Hint a b
  rw [Hint, Matrix.diagonal_conjTranspose]
  congr 1
  funext p
  rw [Pi.star_apply, Complex.star_def, Complex.conj_ofReal]

/-- **The Hamiltonian tie — the entrywise Schrödinger equation** (genuine calculus, via
    `Complex.hasDerivAt_exp`): every diagonal entry of the phase unitary satisfies
    `d/dt U_t(p,p) = −i·H_int(p,p)·U_t(p,p)` — so `U_t = e^{−itH_int}` in the entrywise
    sense established by this derivative lemma (off-diagonal entries are identically 0 on
    both sides). -/
theorem intPhase_entry_hasDerivAt (t : ℝ) (p : ι × κ) :
    HasDerivAt (fun s : ℝ => intPhase a b s p p)
      (-(Hint a b p p) * Complex.I * intPhase a b t p p) t := by
  set c : ℂ := -((a p.1 * b p.2 : ℝ) : ℂ) * Complex.I with hcdef
  have hentry : (fun s : ℝ => intPhase a b s p p) = fun s : ℝ => Complex.exp (c * s) := by
    funext s
    rw [intPhase_apply_eq, hcdef]
    congr 1
    push_cast
    ring
  have hlin : HasDerivAt (fun s : ℝ => c * (s : ℂ)) c t := by
    simpa only [mul_one, id_eq] using ((hasDerivAt_id ((t : ℝ) : ℂ)).const_mul c).comp_ofReal
  have hexp : HasDerivAt (fun s : ℝ => Complex.exp (c * s)) (Complex.exp (c * t) * c) t :=
    (Complex.hasDerivAt_exp (c * (t : ℂ))).comp t hlin
  have hval : -(Hint a b p p) * Complex.I * intPhase a b t p p = Complex.exp (c * t) * c := by
    rw [Hint, Matrix.diagonal_apply_eq, intPhase_apply_eq, hcdef,
      show ((-(t * a p.1 * b p.2) : ℝ) : ℂ) * Complex.I
        = -((a p.1 * b p.2 : ℝ) : ℂ) * Complex.I * (t : ℂ) from by push_cast; ring]
    ring
  rw [hentry, hval]
  exact hexp

/-! ## IC1.2 — the evolved joint state and the exact reduced dynamics -/

/-- **The environment state** `ω = diag w` — the diagonal environment density (weights `w`;
    the hypotheses `0 ≤ w k` and `Σ w = 1` are carried where needed). -/
noncomputable def envState : Matrix κ κ ℂ :=
  Matrix.diagonal fun k => (w k : ℂ)

/-- Entry formula for the environment state. -/
theorem envState_apply (k l : κ) :
    envState w k l = if k = l then (w k : ℂ) else 0 := by
  rw [envState, Matrix.diagonal_apply]

/-- The environment state is positive semidefinite for nonnegative weights. -/
theorem envState_posSemidef (hw : ∀ k, 0 ≤ w k) : (envState w).PosSemidef := by
  rw [envState]
  exact Matrix.posSemidef_diagonal_iff.mpr fun k => Complex.zero_le_real.mpr (hw k)

/-- **The joint state** `ρ ⊗ ω` — the uncorrelated system–environment initial state
    (Kronecker product; entrywise `(ρ ⊗ ω)_{(n,k),(m,l)} = ρ_{nm}·ω_{kl}`). -/
noncomputable def joint (ρ : Matrix ι ι ℂ) : Matrix (ι × κ) (ι × κ) ℂ :=
  ρ ⊗ₖ envState w

/-- Entry formula for the joint state. -/
theorem joint_apply (ρ : Matrix ι ι ℂ) (p q : ι × κ) :
    joint w ρ p q = ρ p.1 q.1 * envState w p.2 q.2 := rfl

/-- The joint state of a PSD system state is PSD (Kronecker positivity). -/
theorem joint_posSemidef (hw : ∀ k, 0 ≤ w k) {ρ : Matrix ι ι ℂ} (hρ : ρ.PosSemidef) :
    (joint w ρ).PosSemidef :=
  hρ.kronecker (envState_posSemidef w hw)

/-- The joint state has the system trace (the environment weights sum to 1). -/
theorem joint_trace (hw1 : ∑ k, w k = 1) (ρ : Matrix ι ι ℂ) :
    (joint w ρ).trace = ρ.trace := by
  rw [Matrix.trace, Matrix.trace, Fintype.sum_prod_type]
  refine Finset.sum_congr rfl fun n _ => ?_
  have hterm : ∀ k : κ, (joint w ρ).diag (n, k) = ρ n n * (w k : ℂ) := fun k => by
    rw [Matrix.diag_apply, joint_apply, envState_apply, if_pos rfl]
  rw [Finset.sum_congr rfl fun k _ => hterm k, ← Finset.mul_sum,
    show (∑ k, (w k : ℂ)) = 1 from by exact_mod_cast hw1, mul_one, Matrix.diag_apply]

/-- **The evolved joint state** `U_t·(ρ ⊗ ω)·U_tᴴ` — the exact interacting Heisenberg
    picture (no weak-coupling, no Born–Markov approximation: the model is exactly
    solvable). -/
noncomputable def evolved (t : ℝ) (ρ : Matrix ι ι ℂ) : Matrix (ι × κ) (ι × κ) ℂ :=
  intPhase a b t * joint w ρ * (intPhase a b t)ᴴ

/-- Entry formula for the evolved joint state (diagonal conjugation collapses to phases). -/
theorem evolved_apply (t : ℝ) (ρ : Matrix ι ι ℂ) (p q : ι × κ) :
    evolved a b w t ρ p q
      = Complex.exp ((-(t * a p.1 * b p.2) : ℝ) * Complex.I)
        * (ρ p.1 q.1 * envState w p.2 q.2)
        * Complex.exp ((-(-t * a q.1 * b q.2) : ℝ) * Complex.I) := by
  rw [evolved, intPhase_conjTranspose]
  simp only [intPhase]
  rw [Matrix.mul_diagonal, Matrix.diagonal_mul, joint_apply]

/-- Pair-index entry formula (the projection-reduced instance used by the partial trace). -/
theorem evolved_apply_pair (t : ℝ) (ρ : Matrix ι ι ℂ) (n m : ι) (k l : κ) :
    evolved a b w t ρ (n, k) (m, l)
      = Complex.exp ((-(t * a n * b k) : ℝ) * Complex.I)
        * (ρ n m * envState w k l)
        * Complex.exp ((-(-t * a m * b l) : ℝ) * Complex.I) :=
  evolved_apply a b w t ρ (n, k) (m, l)

/-- The evolved joint state of a PSD state is PSD (unitary conjugation preserves PSD). -/
theorem evolved_posSemidef (hw : ∀ k, 0 ≤ w k) {ρ : Matrix ι ι ℂ} (hρ : ρ.PosSemidef)
    (t : ℝ) : (evolved a b w t ρ).PosSemidef := by
  rw [evolved]
  exact (joint_posSemidef w hw hρ).mul_mul_conjTranspose_same (intPhase a b t)

/-- **The reduced dynamics** — trace out the environment: `ρ ↦ Tr₂(U_t·(ρ ⊗ ω)·U_tᴴ)`
    (the held `partialTraceRight`, REUSED not redefined). -/
noncomputable def reduced (t : ℝ) (ρ : Matrix ι ι ℂ) : Matrix ι ι ℂ :=
  partialTraceRight (evolved a b w t ρ)

/-- **The decoherence factor** `γ_{nm}(t) = Σ_k w_k·e^{−it(a_n − a_m)b_k}` — the exact
    coherence-suppression coefficient of the pure-dephasing model. -/
noncomputable def gamma (t : ℝ) (n m : ι) : ℂ :=
  ∑ k, (w k : ℂ) * Complex.exp ((-(t * ((a n - a m) * b k)) : ℝ) * Complex.I)

/-- **THE EXACT SOLUTION** — the reduced dynamics multiplies every coherence by the
    decoherence factor: `(Tr₂ U_t(ρ ⊗ ω)U_tᴴ)_{nm} = γ_{nm}(t)·ρ_{nm}`.  The diagonal
    environment kills the off-fibre terms and each surviving fibre contributes the phase
    `e^{−it(a_n − a_m)b_k}` weighted by `w_k`. -/
theorem reduced_entry (t : ℝ) (ρ : Matrix ι ι ℂ) (n m : ι) :
    reduced a b w t ρ n m = gamma a b w t n m * ρ n m := by
  rw [reduced, partialTraceRight_apply, gamma, Finset.sum_mul]
  refine Finset.sum_congr rfl fun k _ => ?_
  rw [evolved_apply_pair, envState_apply, if_pos rfl,
    show Complex.exp ((-(t * a n * b k) : ℝ) * Complex.I) * (ρ n m * (w k : ℂ))
        * Complex.exp ((-(-t * a m * b k) : ℝ) * Complex.I)
      = (w k : ℂ)
        * (Complex.exp ((-(t * a n * b k) : ℝ) * Complex.I)
          * Complex.exp ((-(-t * a m * b k) : ℝ) * Complex.I)) * ρ n m from by ring,
    ← Complex.exp_add,
    show ((-(t * a n * b k) : ℝ) : ℂ) * Complex.I + ((-(-t * a m * b k) : ℝ) : ℂ) * Complex.I
      = ((-(t * ((a n - a m) * b k)) : ℝ) : ℂ) * Complex.I from by push_cast; ring]

/-- The decoherence factor is 1 on the diagonal (`Σ w = 1`). -/
theorem gamma_diag (hw1 : ∑ k, w k = 1) (t : ℝ) (n : ι) : gamma a b w t n n = 1 := by
  rw [gamma]
  have hterm : ∀ k : κ,
      (w k : ℂ) * Complex.exp ((-(t * ((a n - a n) * b k)) : ℝ) * Complex.I) = (w k : ℂ) := by
    intro k
    simp
  rw [Finset.sum_congr rfl fun k _ => hterm k]
  exact_mod_cast hw1

/-- **THE LEDGER IS CONSERVED BY THE INTERACTION** — diagonal (record) entries never move:
    `(reduced t ρ)_{nn} = ρ_{nn}`.  DERIVED from the coupling (contrast RC1, where diagonal
    freezing was built into the channel by hand). -/
theorem reduced_diag (hw1 : ∑ k, w k = 1) (t : ℝ) (ρ : Matrix ι ι ℂ) (n : ι) :
    reduced a b w t ρ n n = ρ n n := by
  rw [reduced_entry, gamma_diag a b w hw1, one_mul]

/-- The decoherence factor never exceeds 1 in modulus (triangle inequality:
    `‖Σ w_k·e^{iθ_k}‖ ≤ Σ w_k = 1`). -/
theorem gamma_norm_le_one (hw : ∀ k, 0 ≤ w k) (hw1 : ∑ k, w k = 1) (t : ℝ) (n m : ι) :
    ‖gamma a b w t n m‖ ≤ 1 := by
  rw [gamma]
  calc ‖∑ k, (w k : ℂ) * Complex.exp ((-(t * ((a n - a m) * b k)) : ℝ) * Complex.I)‖
      ≤ ∑ k, ‖(w k : ℂ) * Complex.exp ((-(t * ((a n - a m) * b k)) : ℝ) * Complex.I)‖ :=
        norm_sum_le _ _
    _ = ∑ k, w k := by
        refine Finset.sum_congr rfl fun k _ => ?_
        rw [norm_mul, Complex.norm_exp_ofReal_mul_I, mul_one, Complex.norm_real,
          Real.norm_eq_abs, abs_of_nonneg (hw k)]
    _ = 1 := hw1

/-- **The reduced dynamics is trace-preserving** (the conserved ledger sums to the
    trace). -/
theorem reduced_trace (hw1 : ∑ k, w k = 1) (t : ℝ) (ρ : Matrix ι ι ℂ) :
    (reduced a b w t ρ).trace = ρ.trace := by
  rw [Matrix.trace, Matrix.trace]
  refine Finset.sum_congr rfl fun n _ => ?_
  rw [Matrix.diag_apply, Matrix.diag_apply, reduced_diag a b w hw1]

/-- **The reduced dynamics is positivity-preserving**: joint PSD (Kronecker) + unitary
    conjugation + the held partial-trace positivity. -/
theorem reduced_posSemidef (hw : ∀ k, 0 ≤ w k) {ρ : Matrix ι ι ℂ} (hρ : ρ.PosSemidef)
    (t : ℝ) : (reduced a b w t ρ).PosSemidef :=
  partialTraceRight_posSemidef (evolved_posSemidef a b w hw hρ t)

/-! ## IC1.3 — the Cesàro time average and the oscillatory-integral core

FIREWALL (finite recurrences): the environment is FINITE, so `γ_{nm}(t)` is almost
periodic and pointwise `t → ∞` decay is IMPOSSIBLE — the repo's own gate C
(`QG/FiniteModularRecurrence.lean`, CITED not imported).  The honest finite-dimensional
einselection statement is the CESÀRO one: the time AVERAGE of every nonzero-frequency
phase dies like `1/T`. -/

/-- **The oscillatory-integral core**: for `θ ≠ 0` the Cesàro average of the phase
    `e^{−itθ}` vanishes at `T → ∞` — closed-form FTC integral
    `∫₀ᵀ e^{−itθ}dt = (e^{−iTθ} − 1)/(−iθ)` and the squeeze `‖·‖ ≤ 2/(|θ|·T) → 0`. -/
theorem cesaro_exp_tendsto {θ : ℝ} (hθ : θ ≠ 0) :
    Filter.Tendsto
      (fun T : ℝ => (1 / T : ℂ) * ∫ t in (0:ℝ)..T, Complex.exp ((-(t * θ) : ℝ) * Complex.I))
      Filter.atTop (nhds 0) := by
  set c : ℂ := -(θ : ℂ) * Complex.I with hc
  have hc0 : c ≠ 0 := by
    rw [hc]
    exact mul_ne_zero (neg_ne_zero.mpr (by exact_mod_cast hθ)) Complex.I_ne_zero
  have hfun2 : (fun T : ℝ =>
        (1 / T : ℂ) * ∫ t in (0:ℝ)..T, Complex.exp ((-(t * θ) : ℝ) * Complex.I))
      = fun T : ℝ => (1 / T : ℂ) * ((Complex.exp (c * T) - 1) / c) := by
    funext T
    congr 1
    rw [show (fun t : ℝ => Complex.exp ((-(t * θ) : ℝ) * Complex.I))
        = fun t : ℝ => Complex.exp (c * t) from funext fun t => by
      congr 1
      rw [hc]
      push_cast
      ring]
    rw [integral_exp_mul_complex hc0]
    simp
  have hg : Filter.Tendsto (fun T : ℝ => 2 / |θ| / T) Filter.atTop (nhds 0) :=
    Filter.Tendsto.div_atTop tendsto_const_nhds Filter.tendsto_id
  rw [hfun2]
  refine squeeze_zero_norm' ?_ hg
  filter_upwards [Filter.eventually_ge_atTop (1 : ℝ)] with T hT
  have hT0 : (0 : ℝ) < T := lt_of_lt_of_le one_pos hT
  have hnormc : ‖c‖ = |θ| := by
    rw [hc, norm_mul, norm_neg, Complex.norm_real, Complex.norm_I, mul_one, Real.norm_eq_abs]
  have hexp1 : ‖Complex.exp (c * (T : ℂ))‖ = 1 := by
    rw [show c * (T : ℂ) = ((-(T * θ) : ℝ) : ℂ) * Complex.I from by rw [hc]; push_cast; ring]
    exact Complex.norm_exp_ofReal_mul_I _
  have hnum : ‖Complex.exp (c * (T : ℂ)) - 1‖ ≤ 2 := by
    calc ‖Complex.exp (c * (T : ℂ)) - 1‖
        ≤ ‖Complex.exp (c * (T : ℂ))‖ + ‖(1 : ℂ)‖ := norm_sub_le _ _
      _ = 2 := by rw [hexp1, norm_one]; norm_num
  have h1T : ‖(1 / T : ℂ)‖ = 1 / T := by
    rw [norm_div, norm_one, Complex.norm_real, Real.norm_eq_abs, abs_of_pos hT0]
  have hmul : ‖Complex.exp (c * (T : ℂ)) - 1‖ / |θ| ≤ 2 / |θ| := by
    rw [div_eq_mul_inv, div_eq_mul_inv]
    exact mul_le_mul_of_nonneg_right hnum (inv_nonneg.mpr (abs_nonneg θ))
  calc ‖(1 / T : ℂ) * ((Complex.exp (c * T) - 1) / c)‖
      = ‖(1 / T : ℂ)‖ * ‖(Complex.exp (c * (T : ℂ)) - 1) / c‖ := norm_mul _ _
    _ = 1 / T * (‖Complex.exp (c * (T : ℂ)) - 1‖ / |θ|) := by rw [h1T, norm_div, hnormc]
    _ ≤ 1 / T * (2 / |θ|) := mul_le_mul_of_nonneg_left hmul (one_div_pos.mpr hT0).le
    _ = 2 / |θ| / T := by ring

/-- The single-frequency phase is continuous (integrability feedstock). -/
theorem continuous_phase (α β : ℝ) :
    Continuous fun t : ℝ => Complex.exp ((-(t * (α * β)) : ℝ) * Complex.I) := by
  have h1 : Continuous fun t : ℝ => -(t * (α * β)) := (continuous_id.mul continuous_const).neg
  exact Complex.continuous_exp.comp ((Complex.continuous_ofReal.comp h1).mul continuous_const)

/-- **The Cesàro time average of the decoherence factor**
    `γ̄_{nm}(T) = (1/T)∫₀ᵀ γ_{nm}(t) dt`. -/
noncomputable def timeAvgGamma (T : ℝ) (n m : ι) : ℂ :=
  (1 / T : ℂ) * ∫ t in (0:ℝ)..T, gamma a b w t n m

/-- The time-averaged decoherence factor splits over the (finite) environment modes —
    linearity of the interval integral over the finite sum. -/
theorem timeAvgGamma_eq_sum (T : ℝ) (n m : ι) :
    timeAvgGamma a b w T n m
      = ∑ k, (w k : ℂ)
          * ((1 / T : ℂ) * ∫ t in (0:ℝ)..T,
              Complex.exp ((-(t * ((a n - a m) * b k)) : ℝ) * Complex.I)) := by
  rw [timeAvgGamma]
  simp only [gamma]
  have hInt : ∀ k ∈ (Finset.univ : Finset κ), IntervalIntegrable
      (fun t : ℝ => (w k : ℂ) * Complex.exp ((-(t * ((a n - a m) * b k)) : ℝ) * Complex.I))
      MeasureTheory.volume 0 T := fun k _ =>
    (continuous_const.mul (continuous_phase (a n - a m) (b k))).intervalIntegrable 0 T
  rw [intervalIntegral.integral_finsetSum hInt, Finset.mul_sum]
  refine Finset.sum_congr rfl fun k _ => ?_
  rw [intervalIntegral.integral_const_mul]
  ring

/-- On the diagonal the time average is constantly 1 (for `T ≠ 0`). -/
theorem timeAvgGamma_diag (hw1 : ∑ k, w k = 1) {T : ℝ} (hT : T ≠ 0) (n : ι) :
    timeAvgGamma a b w T n n = 1 := by
  have hT' : (T : ℂ) ≠ 0 := Complex.ofReal_ne_zero.mpr hT
  rw [timeAvgGamma]
  simp only [gamma_diag a b w hw1]
  rw [intervalIntegral.integral_const, sub_zero, Complex.real_smul, mul_one, one_div,
    inv_mul_cancel₀ hT']

/-- **The off-diagonal time average DIES** — under the gaps-resolved hypothesis every
    frequency `(a_n − a_m)·b_k` is nonzero, so each mode's Cesàro average vanishes and the
    finite sum follows. -/
theorem timeAvgGamma_tendsto_zero
    (hres : ∀ n m : ι, n ≠ m → ∀ k, (a n - a m) * b k ≠ 0) {n m : ι} (hnm : n ≠ m) :
    Filter.Tendsto (fun T : ℝ => timeAvgGamma a b w T n m) Filter.atTop (nhds 0) := by
  rw [show (fun T : ℝ => timeAvgGamma a b w T n m)
      = fun T : ℝ => ∑ k, (w k : ℂ)
          * ((1 / T : ℂ) * ∫ t in (0:ℝ)..T,
              Complex.exp ((-(t * ((a n - a m) * b k)) : ℝ) * Complex.I)) from
    funext fun T => timeAvgGamma_eq_sum a b w T n m]
  have h := tendsto_finsetSum (Finset.univ : Finset κ)
    (fun k _ => (cesaro_exp_tendsto (hres n m hnm k)).const_mul ((w k : ℂ)))
  simpa using h

/-! ## IC1.4 — THE EINSELECTION CAPSTONE: the time-averaged reduced dynamics IS `dephase` -/

/-- **The Cesàro-averaged reduced dynamics** — defined entrywise as
    `γ̄_{nm}(T)·ρ_{nm}`; `timeAvgReduced_eq_integral` proves it equals
    `(1/T)∫₀ᵀ reduced t ρ dt` entrywise. -/
noncomputable def timeAvgReduced (T : ℝ) (ρ : Matrix ι ι ℂ) : Matrix ι ι ℂ :=
  fun n m => timeAvgGamma a b w T n m * ρ n m

/-- Entry formula for the averaged reduced dynamics. -/
theorem timeAvgReduced_apply (T : ℝ) (ρ : Matrix ι ι ℂ) (n m : ι) :
    timeAvgReduced a b w T ρ n m = timeAvgGamma a b w T n m * ρ n m := rfl

/-- **The agreement lemma**: the entrywise definition IS the Cesàro integral of the
    reduced dynamics, `timeAvgReduced T ρ = (1/T)∫₀ᵀ reduced t ρ dt` entrywise (via the
    exact solution `reduced_entry` and integral linearity). -/
theorem timeAvgReduced_eq_integral (T : ℝ) (ρ : Matrix ι ι ℂ) (n m : ι) :
    timeAvgReduced a b w T ρ n m
      = (1 / T : ℂ) * ∫ t in (0:ℝ)..T, reduced a b w t ρ n m := by
  simp only [reduced_entry]
  rw [intervalIntegral.integral_mul_const, timeAvgReduced_apply, timeAvgGamma]
  ring

/-- **THE EINSELECTION CAPSTONE — the record channel DERIVED.**  Under the gaps-resolved
    hypothesis, the Cesàro time average of the interacting reduced dynamics converges
    (entrywise, `T → ∞`) to RC1's `dephase`: diagonal entries are exactly conserved,
    off-diagonal coherences average to zero.  **The record basis EMERGES from the
    interaction Hamiltonian** — it is the eigenbasis of the monitored observable
    `A = diag a`, not RC1's chosen input — deleting the one named input of the record
    channel at the time-averaged level (pointwise `t → ∞` convergence is impossible in a
    finite environment: recurrences, gate C, see the module firewall). -/
theorem timeAvg_reduced_tendsto_dephase (hw1 : ∑ k, w k = 1)
    (hres : ∀ n m : ι, n ≠ m → ∀ k, (a n - a m) * b k ≠ 0)
    (ρ : Matrix ι ι ℂ) (n m : ι) :
    Filter.Tendsto (fun T : ℝ => timeAvgReduced a b w T ρ n m) Filter.atTop
      (nhds (dephase ρ n m)) := by
  by_cases h : n = m
  · subst h
    rw [dephase_apply_eq]
    have heq : ∀ᶠ T : ℝ in Filter.atTop, timeAvgReduced a b w T ρ n n = ρ n n := by
      filter_upwards [Filter.eventually_ge_atTop (1 : ℝ)] with T hT
      rw [timeAvgReduced_apply,
        timeAvgGamma_diag a b w hw1 (lt_of_lt_of_le one_pos hT).ne', one_mul]
    exact Filter.Tendsto.congr' (Filter.EventuallyEq.symm heq) tendsto_const_nhds
  · rw [dephase_apply_ne ρ h]
    have h0 := (timeAvgGamma_tendsto_zero a b w hres h).mul_const (ρ n m)
    rw [zero_mul] at h0
    exact h0.congr fun T => (timeAvgReduced_apply a b w T ρ n m).symm

/-! ## IC1.5 — EINSELECTION UNIQUENESS: the invariant states are exactly the records -/

/-- **EINSELECTION UNIQUENESS** — the states invariant under the interacting reduced
    dynamics at ALL times are EXACTLY the records: `(∀ t, reduced t ρ = ρ) ↔ dephase ρ = ρ`.
    (⟸ is unconditional in the resolution data: a record-diagonal state never moves;
    ⟹ uses the capstone — invariance forces the time average to be constantly `ρ`, and
    uniqueness of limits forces `ρ = dephase ρ`.) -/
theorem invariant_iff_record (hw1 : ∑ k, w k = 1)
    (hres : ∀ n m : ι, n ≠ m → ∀ k, (a n - a m) * b k ≠ 0) (ρ : Matrix ι ι ℂ) :
    (∀ t, reduced a b w t ρ = ρ) ↔ dephase ρ = ρ := by
  constructor
  · intro hfix
    ext n m
    have hconst : ∀ᶠ T : ℝ in Filter.atTop, timeAvgReduced a b w T ρ n m = ρ n m := by
      filter_upwards [Filter.eventually_ge_atTop (1 : ℝ)] with T hT
      have hT' : (T : ℂ) ≠ 0 :=
        Complex.ofReal_ne_zero.mpr (lt_of_lt_of_le one_pos hT).ne'
      rw [timeAvgReduced_eq_integral]
      simp only [hfix]
      rw [intervalIntegral.integral_const, sub_zero, Complex.real_smul, ← mul_assoc,
        one_div, inv_mul_cancel₀ hT', one_mul]
    have h1 : Filter.Tendsto (fun T : ℝ => timeAvgReduced a b w T ρ n m) Filter.atTop
        (nhds (ρ n m)) :=
      Filter.Tendsto.congr' (Filter.EventuallyEq.symm hconst) tendsto_const_nhds
    exact tendsto_nhds_unique (timeAvg_reduced_tendsto_dephase a b w hw1 hres ρ n m) h1
  · intro hd t
    ext n m
    by_cases h : n = m
    · subst h
      exact reduced_diag a b w hw1 t ρ n
    · have h0 : ρ n m = 0 := by
        rw [← hd]
        exact dephase_apply_ne ρ h
      rw [reduced_entry, h0, mul_zero]

/-! ## IC1.6 — THE NECESSITY GUARD: no resolution ⟹ no einselection -/

/-- **THE NECESSITY GUARD** — decoupled environment (`b ≡ 0`): the reduced dynamics is the
    IDENTITY at every time (`γ ≡ Σ w = 1`) — nothing dephases, no record basis is selected.
    The gaps-resolved hypothesis of the capstone is load-bearing, machine-checked (the
    repo's guard-theorem house style). -/
theorem no_resolution_no_einselection (hw1 : ∑ k, w k = 1) (t : ℝ) (ρ : Matrix ι ι ℂ) :
    reduced a (fun _ => 0) w t ρ = ρ := by
  ext n m
  rw [reduced_entry]
  have hγ : gamma a (fun _ => 0) w t n m = 1 := by
    rw [gamma]
    have hterm : ∀ k : κ,
        (w k : ℂ) * Complex.exp ((-(t * ((a n - a m) * (0 : ℝ))) : ℝ) * Complex.I)
          = (w k : ℂ) := by
      intro k
      simp
    rw [Finset.sum_congr rfl fun k _ => hterm k]
    exact_mod_cast hw1
  rw [hγ, one_mul]

end QIQTH.InteractingChannel
