/-
Copyright (c) 2026 PK. All rights reserved.
Released under Apache 2.0 license.

# P4-derivation Stage 1 — the modular Hamiltonian's spectral function

Toward deriving (P4) as a JLMS identity `K_∂R = A_edge/4ℓ_P² + K_bulk` (see `P4_DERIVATION_JLMS_PLAN.md`),
the first object is the **modular Hamiltonian** `K = −log Δ` of the RvD standard-subspace construction.  With
`R = P + Q` (`rvdRC`, bounded self-adjoint, `0 ≤ R ≤ 2`) and the RvD modular operator `Δ = (2−R)·R⁻¹`, the
modular flow is `Δ^{it} = u_t(R)` with character `u_t(r) = exp(i·t·log((2−r)/r))` (`modChar`, already built and
proved a strongly-continuous one-parameter unitary group).

Since `log Δ = log((2−r)/r)` on the spectrum, the modular Hamiltonian `K = −log Δ` has **spectral function**
`kFn(r) = −log((2−r)/r) = log(r/(2−r))` on `(0,2)`.  This file defines `kFn` and proves the **generator
identity** `Δ^{it} = e^{−itK}` at the spectral level (`modChar t r = exp(−i·t·kFn r)`), connecting `K` to the
existing modular flow.

Honest scope (plan §0–§2): the *unbounded operator* `K = kFn(R)` needs unbounded-self-adjoint-operator
infrastructure Mathlib does not yet have (the cited Tomita–Takesaki frontier); this Stage delivers the spectral
function and its identity with the flow — the bounded/form-level content that Stage 2's first law builds on.
Axiom-free.
-/
import QIQTH.ModularRelativeEntropy

namespace QIQTH.StandardSubspaceModular

open scoped ComplexConjugate
open MeasureTheory

variable {H : Type*} [NormedAddCommGroup H] [InnerProductSpace ℂ H] [CompleteSpace H]

/-- The **spectral function of the modular Hamiltonian** `K = −log Δ`.  On the spectrum `(0,2)` of `R` it is
    `kFn(r) = log(r/(2−r)) = −log((2−r)/r)`; outside (the endpoint convention) it is `0`, matching `modChar`. -/
noncomputable def kFn : ℝ → ℝ :=
  (Set.Ioo (0 : ℝ) 2).piecewise (fun r => Real.log (r / (2 - r))) (fun _ => 0)

theorem kFn_measurable : Measurable kFn := by
  apply Measurable.piecewise measurableSet_Ioo _ measurable_const
  exact Real.measurable_log.comp (measurable_id.div (measurable_const.sub measurable_id))

/-- `kFn` is real-valued by construction, so the modular Hamiltonian is (formally) self-adjoint: its spectral
    function is real. -/
theorem kFn_real (r : ℝ) : (kFn r : ℂ).im = 0 := by simp

/-- **The generator identity `Δ^{it} = e^{−itK}` at the spectral level.**  On the spectrum `(0,2)`, the RvD
    modular character equals `exp(−i·t·kFn r)` — i.e. the modular flow `Δ^{it} = u_t(R)` is generated by `−K`,
    where `K` has spectral function `kFn`.  This pins the modular Hamiltonian to the existing modular flow. -/
theorem modChar_eq_exp_neg_kFn (t : ℝ) {r : ℝ} (hr : r ∈ Set.Ioo (0 : ℝ) 2) :
    modChar t r = Complex.exp (-(Complex.I * (t : ℂ) * (kFn r : ℂ))) := by
  have hr0 : 0 < r := hr.1
  have hr2 : r < 2 := hr.2
  have h2r : 0 < 2 - r := by linarith
  rw [modChar, Set.piecewise_eq_of_mem _ _ _ hr, kFn, Set.piecewise_eq_of_mem _ _ _ hr]
  congr 1
  have hlog : Real.log (r / (2 - r)) = -Real.log ((2 - r) / r) := by
    rw [← Real.log_inv, inv_div]
  rw [hlog]
  push_cast
  ring

/-- **Sign of the modular energy** at the spectral level: `K = −log Δ` is nonpositive on the `Δ ≥ 1` half
    `(0,1)` and nonnegative on the `Δ ≤ 1` half `(1,2)` — the modular energy changes sign across the fixed
    point `r = 1` (`Δ = 1`), as it must for a KMS/thermal generator. -/
theorem kFn_nonpos_of_lt_one {r : ℝ} (hr : r ∈ Set.Ioo (0 : ℝ) 1) : kFn r ≤ 0 := by
  have h2r : (0 : ℝ) < 2 - r := by linarith [hr.2]
  have hmem : r ∈ Set.Ioo (0 : ℝ) 2 := ⟨hr.1, by linarith [hr.2]⟩
  rw [kFn, Set.piecewise_eq_of_mem _ _ _ hmem]
  apply Real.log_nonpos (div_nonneg hr.1.le h2r.le)
  rw [div_le_one h2r]; linarith [hr.2]

theorem kFn_nonneg_of_one_lt {r : ℝ} (hr : r ∈ Set.Ioo (1 : ℝ) 2) : 0 ≤ kFn r := by
  have h2r : (0 : ℝ) < 2 - r := by linarith [hr.2]
  have hmem : r ∈ Set.Ioo (0 : ℝ) 2 := ⟨by linarith [hr.1], hr.2⟩
  rw [kFn, Set.piecewise_eq_of_mem _ _ _ hmem]
  apply Real.log_nonneg
  rw [le_div_iff₀ h2r]; linarith [hr.1]

/-! ### Stage 2 — the first law: the modular relative entropy *is* the modular energy `S = ⟨K⟩`

The one-particle (CGP) modular relative entropy is `cgpEntropy S ξ = −∫ entropyDensity dμ^R_ξ`, with
`entropyDensity r = log((2−r)/r)` the spectral function of `log Δ`.  Since `kFn = −entropyDensity` (i.e.
`K = −log Δ`), the relative entropy equals the **modular-energy expectation** `∫ kFn dμ^R_ξ = ⟨ξ, K ξ⟩` — the
first-law identity `δS = δ⟨K⟩` in its sharpest form (here `S` *is* `⟨K⟩`; the von Neumann part is absorbed into
the CGP coherent-state functional).  Combined with Klein positivity (`cgpEntropy_nonneg`), this is the engine
Stage 4 uses to reduce the FQ *bound* to relative-entropy positivity. -/

/-- `kFn = −entropyDensity` on the spectrum interior `(0,2)`: the Stage-1 modular Hamiltonian density is minus
    the existing `log Δ` density.  (`K = −log Δ`.) -/
theorem kFn_eq_neg_entropyDensity {r : ℝ} (hr : r ∈ Set.Ioo (0 : ℝ) 2) :
    kFn r = -entropyDensity r := by
  rw [kFn, Set.piecewise_eq_of_mem _ _ _ hr, entropyDensity, ← Real.log_inv, inv_div]

/-- **Stage 2 — the first law `S = ⟨K⟩`.**  For a standard subspace whose modular spectrum avoids the endpoints
    (`hspec`, the separating/cyclic case), the modular relative entropy equals the modular-energy expectation:
    `cgpEntropy S ξ = ∫ kFn dμ^R_ξ` (`= ⟨ξ, K ξ⟩`, the integral of the modular Hamiltonian against the spectral
    measure).  So the relative entropy's first variation is the modular-energy variation — the boundary dual of
    the bulk Clausius relation used in the GR chain. -/
theorem cgpEntropy_eq_integral_kFn (S : StandardSubspace H) (ξ : H)
    (hspec : ∀ ω : spectrum ℝ (rvdRC S), (ω : spectrum ℝ (rvdRC S)).val ∈ Set.Ioo (0 : ℝ) 2) :
    cgpEntropy S ξ = ∫ ω, kFn (ω : spectrum ℝ (rvdRC S)).val ∂(rvdSpecMeasure S ξ) := by
  rw [cgpEntropy, ← integral_neg]
  refine integral_congr_ae (Filter.Eventually.of_forall (fun ω => ?_))
  exact (kFn_eq_neg_entropyDensity (hspec ω)).symm

end QIQTH.StandardSubspaceModular
