/-
  THE TOWER T3 (THE_TOWER_PLAN.md) — THE CENTERPIECE: `gibbsTower_awFingerprint_III₁`.

  **The first machine-checked contact with the Type III₁ wall**: the code tower's Gibbs
  eigenvalue family, with two frequencies occurring infinitely often at irrational ratio,
  satisfies the Araki–Woods III₁ fingerprint — an ARITHMETIC theorem about eigenvalue lists.

  THE THREE CITED OPERATOR FACTS (never proved here; the von Neumann algebra is not constructed
  here):
  (α) a ratio witnessed in infinitely many disjoint factors with weight uniformly ≥ δ lies in the
      asymptotic ratio set r∞ (Araki–Woods 1968, sufficiency/amplification lemma).
  (β) r∞ is closed in [0,∞) and r∞ ∩ (0,∞) is a closed multiplicative subgroup
      (Araki–Woods 1968).
  (γ) r∞ = [0,∞) is the definition of the III₁ class for ITPFI factors, and r∞ coincides with
      the Connes S-invariant for ITPFI (Araki–Woods 1968; Connes 1973).
  Given (α)(β)(γ), the fingerprint proved below implies — BY CITATION, not by proof — that the
  ITPFI factor of the tower is III₁. Faithfulness (all λ > 0) and D_k ≥ 2 make the tower
  legitimate ITPFI data.

  Plus the HYPOTHESIS-FREE instance (the vacuity guard): the alternating tower with frequencies
  {1, √2} and qubit cutoffs satisfies the fingerprint, via `irrational_sqrt_two`.
-/
import Mathlib
import QIQTH.Tower.AWFingerprint
import QIQTH.Tower.KroneckerDensity

namespace QIQTH.Tower

/-- A frequency occurring infinitely often contributes its EXACT negated value as a tail modular
    exponent (the (1,0) pair in each such factor; the Z cancels, so the accuracy is 0 ≤ ε). -/
theorem isTailModularExponent_of_frequently {D : ℕ → ℕ} {x : ℕ → ℝ} {a b s : ℝ}
    (ha : 0 < a) (hax : ∀ k, a ≤ x k) (hxb : ∀ k, x k ≤ b) (hD : ∀ k, 2 ≤ D k)
    (hs : ∀ N : ℕ, ∃ k ≥ N, x k = s) :
    IsTailModularExponent (fun k => gibbsEigen (D k) (x k)) (-s) := by
  have hea : Real.exp (-a) < 1 := by
    rw [Real.exp_lt_one_iff]
    linarith
  refine ⟨Real.exp (-b) * (1 - Real.exp (-a)), by positivity, ?_⟩
  intro ε hε N
  obtain ⟨k, hkN, hks⟩ := hs N
  have hDk := hD k
  refine ⟨k, hkN, ⟨1, by omega⟩, ⟨0, by omega⟩, ?_, ?_, ?_⟩
  · exact (gibbsEigen_one_bound hDk ha (hax k) (hxb k)).le
  · have h0 := gibbsEigen_zero_bound (by omega : 1 ≤ D k) ha (hax k)
    have hb1 : Real.exp (-b) ≤ 1 := by
      rw [Real.exp_le_one_iff]
      linarith [ha, hax k, hxb k]
    nlinarith
  · have hpos1 : 0 < gibbsEigen (D k) (x k) ⟨1, by omega⟩ :=
      gibbsEigen_pos (by omega) _ _
    have hpos0 : 0 < gibbsEigen (D k) (x k) ⟨0, by omega⟩ :=
      gibbsEigen_pos (by omega) _ _
    have hratio : Real.log (gibbsEigen (D k) (x k) ⟨1, by omega⟩)
        - Real.log (gibbsEigen (D k) (x k) ⟨0, by omega⟩) = -(x k) := by
      rw [← Real.log_div hpos1.ne' hpos0.ne', gibbsEigen_ratio hDk, Real.log_exp]
    rw [hratio, hks]
    simp [hε.le]

/-- **T3 CENTERPIECE — THE ARAKI–WOODS III₁ FINGERPRINT OF THE CODE'S GIBBS TOWER**: two
    frequencies occurring infinitely often with irrational ratio, uniform bounds
    `0 < a ≤ x_k ≤ b`, cutoffs `D_k ≥ 2` ⟹ the tower's eigenvalue family satisfies
    `AWFingerprintIII1` — the additive group generated by the witnessed tail modular exponents is
    dense in ℝ.

    This is an ARITHMETIC theorem about eigenvalue lists. Its operator reading rests on the three
    CITED facts (α)(β)(γ) in the module docstring (Araki–Woods 1968; Connes 1973): given those,
    the tower's ITPFI factor is of type III₁ — that inference is cited, never proved, and no von
    Neumann algebra is constructed in this development. -/
theorem gibbsTower_awFingerprint_III₁ {D : ℕ → ℕ} {x : ℕ → ℝ} {a b s t : ℝ}
    (ha : 0 < a) (hax : ∀ k, a ≤ x k) (hxb : ∀ k, x k ≤ b) (hD : ∀ k, 2 ≤ D k)
    (hs : ∀ N : ℕ, ∃ k ≥ N, x k = s) (ht : ∀ N : ℕ, ∃ k ≥ N, x k = t)
    (hirr : Irrational (s / t)) :
    AWFingerprintIII1 (fun k => gibbsEigen (D k) (x k)) := by
  have hks := isTailModularExponent_of_frequently ha hax hxb hD hs
  have hkt := isTailModularExponent_of_frequently ha hax hxb hD ht
  have hsub : ({-s, -t} : Set ℝ)
      ⊆ {κ | IsTailModularExponent (fun k => gibbsEigen (D k) (x k)) κ} := by
    intro y hy
    rcases Set.mem_insert_iff.mp hy with rfl | hy
    · exact hks
    · rw [Set.mem_singleton_iff.mp hy]
      exact hkt
  have hmono : AddSubgroup.closure ({-s, -t} : Set ℝ)
      ≤ AddSubgroup.closure
        {κ | IsTailModularExponent (fun k => gibbsEigen (D k) (x k)) κ} :=
    AddSubgroup.closure_mono hsub
  have hdense : Dense ((AddSubgroup.closure ({-s, -t} : Set ℝ)) : Set ℝ) := by
    refine dense_closure_pair ?_
    rw [neg_div_neg_eq]
    exact hirr
  exact hdense.mono hmono

/-- **The hypothesis-free instance (the vacuity guard)**: the alternating qubit tower with
    frequencies `{√2, 1}` satisfies the III₁ fingerprint — via `irrational_sqrt_two`, no
    hypotheses carried. -/
theorem gibbsTower_awFingerprint_III₁_sqrtTwo :
    AWFingerprintIII1
      (fun k => gibbsEigen 2 (if k % 2 = 0 then 1 else Real.sqrt 2)) := by
  have h12 : (1 : ℝ) ≤ Real.sqrt 2 := by
    rw [show (1 : ℝ) = Real.sqrt 1 from (Real.sqrt_one).symm]
    exact Real.sqrt_le_sqrt (by norm_num)
  refine gibbsTower_awFingerprint_III₁ (a := 1) (b := Real.sqrt 2)
    (s := Real.sqrt 2) (t := 1) one_pos ?_ ?_ (fun _ => le_rfl) ?_ ?_ ?_
  · intro k
    by_cases h : k % 2 = 0 <;> simp [h, h12]
  · intro k
    by_cases h : k % 2 = 0 <;> simp [h, h12]
  · intro N
    refine ⟨2 * N + 1, by omega, ?_⟩
    have : (2 * N + 1) % 2 = 1 := by omega
    simp [this]
  · intro N
    refine ⟨2 * N, by omega, ?_⟩
    have : (2 * N) % 2 = 0 := by omega
    simp [this]
  · rw [div_one]
    exact irrational_sqrt_two

end QIQTH.Tower
