/-
  THE TOWER T2 (THE_TOWER_PLAN.md) — Kronecker density.

  The arithmetic engine of the fingerprint: the additive subgroup of ℝ generated by two reals
  with IRRATIONAL ratio is dense. Via `AddSubgroup.dense_or_cyclic` (an additive subgroup of an
  archimedean group is dense or cyclic): in the cyclic case both generators are integer multiples
  of one element, forcing a rational ratio — contradiction.

  Classical Kronecker arithmetic and nothing else — no operator content anywhere in this file.
-/
import Mathlib

namespace QIQTH.Tower

/-- **Kronecker density**: the additive subgroup generated by two reals with irrational ratio is
    dense in ℝ. -/
theorem dense_closure_pair {s t : ℝ} (h : Irrational (s / t)) :
    Dense ((AddSubgroup.closure {s, t} : AddSubgroup ℝ) : Set ℝ) := by
  rcases AddSubgroup.dense_or_cyclic (AddSubgroup.closure {s, t}) with hd | ⟨a, ha⟩
  · exact hd
  · exfalso
    have hs : s ∈ AddSubgroup.closure ({s, t} : Set ℝ) :=
      AddSubgroup.subset_closure (by simp)
    have ht : t ∈ AddSubgroup.closure ({s, t} : Set ℝ) :=
      AddSubgroup.subset_closure (by simp)
    rw [ha, AddSubgroup.mem_closure_singleton] at hs ht
    obtain ⟨m, hm⟩ := hs
    obtain ⟨n, hn⟩ := ht
    have ht0 : t ≠ 0 := by
      intro h0
      exact h (by rw [h0, div_zero]; exact ⟨0, by norm_num⟩)
    have hn0 : n ≠ 0 := by
      intro h0
      rw [h0, zero_smul] at hn
      exact ht0 hn.symm
    have ha0 : a ≠ 0 := by
      intro h0
      rw [h0, smul_zero] at hn
      exact ht0 hn.symm
    apply h
    refine ⟨(m : ℚ) / (n : ℚ), ?_⟩
    push_cast
    rw [← hm, ← hn, zsmul_eq_mul, zsmul_eq_mul, mul_div_mul_right _ _ ha0]

end QIQTH.Tower
