/-
Copyright (c) 2026 PK. All rights reserved.
Released under Apache 2.0 license.

# PHOTON_FIELD_PLAN P9 — abstract boundary-flux sectors (the edge-mode center)

The last new piece of the photon's gauge/edge-mode tier (P6–P9), before the deferred continuum frontier
(P10).  The Gauss-law constraint gives the photon's regional algebra a **center** generated by the
boundary electric flux `E_⊥|_{∂R}`; its spectrum is the set `Q` of **boundary-flux sectors** (the labels
`q` of P8's centered decomposition `𝒜_R ≃ ⊕_q 𝓑(𝓗_{R,q})`).  A regional state induces a classical
probability distribution `p : Q → ℝ` over these flux sectors — the **edge-mode** degrees of freedom.

This module names that center's contribution and bounds it:

* `fluxEntropy p = Σ_q negMulLog(p_q) = H(p_q)` — the **boundary-flux (edge-mode / center) entropy**, the
  classical Shannon entropy of the flux distribution.  In P8's split
  `S(ρ_R) = H(p_q) + Σ_q p_q S(ρ_{R,q})`, this is exactly the edge-mode term (`photon_centered_entropy_eq`).
* `photon_flux_entropy_nonneg` — `H(p_q) ≥ 0` (the edge modes add positively at finite cutoff).
* `photon_flux_entropy_le_log_card` — **`H(p_q) ≤ log |Q|`**: the edge-mode/center capacity is bounded by
  the log of the number of distinguishable boundary-flux sectors — the "edge capacity ≤ boundary flux
  count" bound.  (Reuses the project's Gibbs/Jensen `shannon_le_log_card`.)

The flux observables are *central* records (they commute with the whole gauge-invariant algebra, P6), so
this `fluxEntropy` is the entropy of the **classical center**; the `−log p_q` central piece contributes to
the entropy/first-law but cancels from the *inner* modular flow (PHOTON_FIELD_PLAN §0).

HONEST scope: this is the abstract finite-sector model.  The concrete continuum boundary-flux algebra of
free Maxwell (the Gauss-law constraint surface + the heat-kernel/Kabat contact determinant fixing the
universal coefficient and its sign) is the deferred frontier P10.  Axiom-free (standard
`propext`/`Classical.choice`/`Quot.sound`).  No `sorry`.  Free Maxwell only.
-/
import QIQTH.Fock.Photon.PhotonEdgeModes

namespace QIQTH.Fock.Photon

open Real
open scoped BigOperators

variable {Q : Type*} [Fintype Q] {I : Q → Type*} [∀ q, Fintype (I q)]

/-- The **boundary-flux (edge-mode / center) entropy** `H(p_q) = Σ_q negMulLog(p_q)` — the classical
Shannon entropy of the boundary electric-flux distribution `p` over the sectors `Q`.  This is the edge-mode
term of the photon's centered entanglement entropy (P8). -/
noncomputable def fluxEntropy (p : Q → ℝ) : ℝ := ∑ q, Real.negMulLog (p q)

/-- **The edge-mode (boundary-flux) entropy is non-negative.**  For a flux probability distribution
(`0 ≤ p_q`, `Σ p_q = 1`), `H(p_q) ≥ 0`: at finite cutoff the boundary-flux edge modes add positively to
the regional entanglement entropy. -/
theorem photon_flux_entropy_nonneg (p : Q → ℝ) (hp : ∀ q, 0 ≤ p q) (h1 : ∑ q, p q = 1) :
    0 ≤ fluxEntropy p :=
  photon_edge_term_nonneg p hp
    (fun q => h1 ▸ Finset.single_le_sum (fun i _ => hp i) (Finset.mem_univ q))

/-- **The edge-mode/center capacity bound `H(p_q) ≤ log |Q|`.**  The boundary-flux (edge-mode) entropy is
bounded by the log of the number of distinguishable boundary-flux sectors — the "edge capacity ≤ boundary
flux count" bound for the photon's centered regional algebra.  (Gibbs/Jensen, via the project's
`shannon_le_log_card`.) -/
theorem photon_flux_entropy_le_log_card (p : Q → ℝ) (hp : ∀ q, 0 ≤ p q) (h1 : ∑ q, p q = 1) :
    fluxEntropy p ≤ Real.log (Fintype.card Q) := by
  rw [fluxEntropy, ← QIQTH.RecordContract.shannon_eq_sum_negMulLog Finset.univ p]
  exact QIQTH.RecordContract.shannon_le_log_card p hp h1

/-- **The centered entropy in terms of the flux entropy**: `S(ρ_R) = H(p_q) + Σ_q p_q S(ρ_{R,q})` with the
boundary-flux term named `fluxEntropy p`.  The P8 decomposition, with the edge-mode/center contribution
made explicit as the flux entropy. -/
theorem photon_centered_entropy_eq (p : Q → ℝ) (w : ∀ q, I q → ℝ) (hw : ∀ q, ∑ i, w q i = 1) :
    ∑ q, ∑ i, Real.negMulLog (p q * w q i)
      = fluxEntropy p + ∑ q, p q * ∑ i, Real.negMulLog (w q i) := by
  rw [fluxEntropy]; exact photon_edge_entropy_decomp p w hw

end QIQTH.Fock.Photon
